# Presentación {- #intro}

La regulación por parte de los gobiernos es una de las características principales de las economías modernas. Los mercados están sometidos a distintas reglas que afectan su funcionamiento y el de las empresas que en ellos actúan. A medida que las economías se desarrollan, las fallas de mercado imponen restricciones al funcionamiento de la economía que requieren ser atendidas, de forma de que puedan explotar todo su potencial. Por tanto, conocer los instrumentos regulatorios disponibles y entender cuáles son sus efectos sobre los mercados es clave para el adecuado diseño de las políticas públicas. Asimismo, no sólo hay que regular cuando es requerido, sino que hay que hacerlo de forma adecuada.


Este libro presenta los principales conceptos de la regulación económica en forma simple, concisa y a la vez rigurosa. Su objetivo es que el lector pueda familiarizarse con las herramientas regulatorias rápidamente evitando, en la medida de lo posible, las discusiones técnicas que subyacen los conceptos. Está dirigido a técnicos del sector público con independencia de su formación profesional. Asimismo, está escrito y diseñado con el objetivo de atender los problemas relevantes de los países en vías de desarrollo y, en particular, los países latinoamericanos. En él se describen los problemas que afectan a estos países, cuyas instituciones regulatorias son muchas veces débiles para enfrentar, de forma adecuada, la tarea de fomentar el funcionamiento de los mercados.

El texto tiene su origen en el Diploma en Regulación Económica que se dicta en la Universidad de la Habana, con el objetivo de formar técnicos en las principales herramientas del análisis económico regulatorio. El mismo se realiza y publica en el marco del programa de colaboración que el Departamento de Economía de la UdelaR desarrolla con la Facultad de Economía de la Universidad de la Habana, con el financiamiento de la Agencia Sueca Internacional de Cooperación al Desarrollo (ASDI). Asimismo, los dos últimos capítulos del libro están basados fuertemente en un trabajo realizado por Domingo y Zipitría para la Unidad Reguladora de los Servicios de Energía y Agua de Uruguay y que contó con financiamiento de la Cooperación Andina de Fomento (CAF).

El capítulo \@ref(reg-ec), escrito por Zipitría, introduce la temática de la regulación económica. Discute la racionalidad económica de la regulación y las distintas teorías que la explican. Se ilustra con distintas regulaciones de la realidad de Uruguay y cómo éstas se interpretan a la luz de las teorías descritas. Por último, desarrolla las características de los mercados de monopolio natural en los cuales se observa no sólo una importante regulación, sino también la presencia de empresas públicas en distintos países en vías de desarrollo. Los sectores de monopolio natural, en donde por razones tecnológicas participa una única empresa del mercado, son sensibles desde el punto de vista político debido a que sus productos son consumidos de forma masiva y existen impor tantes costos hundidos. A la vez, en ellos no es posible confiar en la competencia para que resuelva el funcionamiento eficiente del mercado.

En el capítulo \@ref(inst-reg), Zipitría introduce los principales instrumentos regulatorios y sus efectos sobre el mercado. Si bien el principal instrumento de evaluación del funcionamiento de los mercados es la eficiencia, el capítulo no cuestiona otros fines que pueda tener la regulación. Ello permite investigar los efectos, buscado y no buscados, que la aplicación de los instrumentos regulatorios tiene sobre el mercado. Muchas veces, en el diseño regulatorio, el énfasis se pone en el efecto directo que el instrumento tiene sobre el comportamiento que se busca modificar, cuando los efectos indirectos pueden alterar la conducta de los agentes en los mercados en sentido no previsto y empeorar el funcionamiento general del mismo. El análisis se realiza identificando la forma de regulación óptima en cada estructura de mercado —competencia perfecta, oligopolio y monopolio natural— y los efectos que la misma tiene sobre su eficiencia.

El capítulo \@ref(def-comp), del mismo autor, desarrolla los principales conceptos del análisis de defensa de la competencia. En aquellos mercados donde la competencia es factible, muchas veces las empresas privadas buscan evitar que esta opere y reduzca las rentas que obtienen. Por ello, se ha desarrollado un campo específico que intenta comprender el funcionamiento de los mercados y el efecto de las conductas que los agentes desarrollan. En la medida en que los países menos desarrollados tienen dificultades para recopilar y acceder a información detallada de la forma en la que operan los mercados, se presenta una discusión de los instrumentos que permiten comprender su funcionamiento y tomar decisiones fundamentadas sobre las acciones de los privados. Se desarrolla el concepto de mercado relevante, que es el primer paso de toda investigación de competencia, pero que es también una herramienta general que puede ser útil para entender el funcionamiento de los mercados. Posteriormente se analizan el abuso de posición dominante, la colusión, las restricciones verticales y las fusiones de empresas que son las conductas investigadas en esta materia. En cada caso, se expone las razones económicas de los agentes para adoptar cada una de ellas, así como sus efectos positivos y negativos sobre la eficiencia.

En el capítulo \@ref(instituciones-reg), Ponce desarrolla una serie de herramientas para el diseño de las instituciones regulatorias. La regulación de los agentes privados en general, y en las economías en desarrollo en particular, está sometida a una serie de problemas de información, restricciones técnicas y presupuestales que hay que tomar en consideración a la hora del diseño de dichas instituciones. En particular, existe el riesgo de la captura del regulador por parte del sector privado, un compromiso limitado y falta de credibilidad de los reguladores, poca rendición de cuenta de sus acciones, baja eficiencia para recaudar recursos fiscales que permita financiar las actividades reguladas, corrupción y baja capacidad de hacer cumplir las normas. Estos problemas alteran el diseño institucional óptimo de las agencias encargadas de actuar sobre el sector privado y, si no son tenidos en cuenta, pueden determinar que estos organismos se alejen en forma relevante de los fines perseguidos.

En el capítulo \@ref(reg-eepp), Domingo y Zipitría introducen la regulación de las empresas públicas. A diferencia de los países desarrollados, en los países en vías de desarrollo los Estados participan en la actividad productiva en muchos sectores de la economía. Las empresas públicas tienen características distintivas de las privadas, que requieren considerarse a la hora de analizar su eficiencia o su regulación. En particular, están fuertemente influenciadas por el sistema político el cual les adjudica múltiples roles. Esta multiplicidad de objetivos tiene impacto sobre le eficiencia del funcionamiento de estas empresas, así como sobre la posibilidad de evaluar el comportamiento y gestión de sus directores. Asimismo, algunas veces las empresas públicas están sometidas a restricciones presupuestales blandas, lo que afecta también en forma negativa su eficiencia. Por otra parte, las restricciones que enfrentan sus directores se traducen en mecanismos particulares de control de su actuación, de forma de evitar que sean utilizadas con fines espúreos. 

Por último, el capítulo \@ref(eepp-uy) de los mismos autores presenta una descripción de las empresas públicas en América Latina en general, y un detalle de estas empresas y su regulación en Uruguay. El objetivo es ilustrar con ejemplos concretos las múltiples dimensiones del análisis de este tipo de empresas, así como la dinámica política a la cual están sometidas. Asimismo, sirve para comprender los reveses que han enfrentado los reguladores cuando tienen que regular a este tipo de empresas.

Esperamos que este texto, por la presentación llana de los conceptos, sirva de guía y de manual de referencia tanto para los participantes del Diploma en Regulación Económica, como para los formuladores de políticas.

\
\
<div style="text-align: right"> Los autores. </div>