# Regulación económica {#reg-ec}

Leandro Zipitría

\

La esencia del funcionamiento libre del mercado es que a los agentes les está permitido tomar sus propias decisiones [@Viscusi2005, 357]. En términos generales, el mercado
^[Un mercado es el lugar donde se intercambian derechos de propiedad. Los derechos de propiedad incluyen cuatro derechos: (i) al uso; (ii) a obtener los retornos del bien; (iii) a transferir el bien; y (iv) a hacer cumplir los derechos de propiedad.] 
asigna en forma eficiente los recursos en mercados perfectamente competitivos. Por ello, no existe motivo para intervenir en los mercados, dado que las decisiones privadas de los agentes coinciden con el bienestar social. Los mercados por sí solos resuelven el problema de la asignación de recursos.

En algunos casos, sin embargo, el mercado no asigna en forma eficiente los recursos y se producen **fallas de mercado**, las que pueden ser de distinto tipo:

1. **Externalidades**: refieren a costos o ingresos que los agentes no internalizan cuando toman una decisión. Una externalidad negativa se da, por ejemplo, cuando una empresa contamina un río y no considera los costos que acarrea limpiarlo o mejorar su proceso productivo para reducir la contaminación al elegir su nivel de producción. Una externalidad positiva ocurre cuando se crea conocimiento básico, ya que el científico o la institución financiadora no puede apropiarse completamente de los ingresos que este conocimiento genera. En ambos casos, los mercados no asignan en forma eficiente los recursos y tenderán a sobre (sub) producir si la externalidad es negativa (positiva).

1. **Bienes públicos**: son aquellos no excluibles (no se puede excluir a los agentes de su consumo) y no rivales (el consumo de una unidad del bien no disminuye la cantidad disponible para los demás consumidores).
^[Los bienes económicos tradicionales son excluibles y rivales.] 
Ejemplo de este tipo de bienes es el conocimiento, el aire o la defensa de una nación.

1. **Poder de mercado**: define la capacidad de una empresa o conjunto de empresas de fijar el precio de forma rentable por encima del nivel competitivo, conducta que conduce a pérdidas del bienestar social [@Carlton2004, p. 8]. La existencia de poder de mercado determina mercados no competitivos. Este texto analiza la regulación de este tipo de falla de mercado.

1. **Asimetrías de información**: se da cuando las partes que intervienen en las
transacciones no cuentan con la misma información sobre el producto, el servicio o el activo objeto de la transacción. Los problemas de asimetría de información impregnan las relaciones económicas entre agentes y puede hacer colapsar a los mercados. La idea clásica refiere a una situación en donde existen distintas calidades de bienes pero los demandantes no conocen la calidad específica que ofrece cada agente. En estas circunstancias, para determinadas valoraciones de compradores y vendedores, se puede demostrar que sólo serán transados los de peor calidad [@Wolfstetter1999, pp. 244-245]. En el sector financiero y en la salud la asimetría de información es un problema relevante que determina que se necesiten instrumentos regulatorios específicos para mitigarla.

En las economías modernas, los gobiernos en forma rutinaria toman decisiones que buscan afectar la forma en la que los agentes económicos se comportan y modificar tanto el bienestar de los mismos como el de la sociedad. En particular, en su rol de reguladores, los gobiernos restringen el conjunto de acciones disponibles para los agentes. Por regulación se entiende las limitaciones impuestas a los agentes respecto de la discreción de las decisiones que pueden tomar, materializadas a través del uso de instrumentos legales y bajo la amenaza de alguna sanción. Los gobiernos, a diferencia de los demás agentes sociales, tienen el monopolio del poder de coerción,
^[Esta idea está basada en [@Weber1921].]
en particular, de hacer cumplir las normas que ellos mismos dictan.
^[El lenguaje dice mucho de los pueblos; el idioma inglés tiene una palabra para “hacer cumplir las normas”, enforcement, que el idioma español carece.]

Cuando se regula un mercado su resultado en términos de eficiencia asignativa y productiva está co-determinado por las fuerzas del mercado y el proceso administrativo.
^[No se consideran en este análisis elementos que refieren a si las normas son justas o éticas como justificación de la regulación, sólo si son eficientes desde el punto de vista económico. Para una discusión y crítica de esta visión, véase [@Baldwin2011, capítulo 3].]
Las regulaciones pueden ser de distinto tipo, y a los efectos de este texto se dividen en:

1. **Económicas**: aquellas que afectan la eficiencia asignativa —y productiva—
de los mercados, como ser la fijación de precios o cantidades, el número de
competidores, la entrada o salida del mercado.

1. **Sociales**: incluyen las regulaciones medioambientales, las condiciones laborales, la protección del consumidor, y la seguridad de productos, entre otras. Entre ellas podemos encontrar las regulaciones que establecen requerimientos sobre la forma en la que se eliminan sustancias tóxicas en el ambiente, la información que deben tener los productos alimenticios o medicamentos sobre sus componentes, o los controles que se establecen sobre los lugares donde se venden los productos.

No por ser las más importantes, sino porque es el eje central del texto, nos vamos a concentrar en las regulaciones económicas. Sin embargo, las regulaciones sociales también tienen justificación económica y deben ser consideradas a la hora de formular las distintas políticas, ya que no sólo son relevantes en sí mismas, sino que también tienen impactos sobre las variables económicas. Las regulaciones económicas pueden, a su vez, dividirse entre:

1. **Regulaciones de estructura**: incluyen normas que alteran la estructura del mercado, como ser las que afectan la libre entrada y salida de empresas o agentes del mercado.

1. **Regulaciones de conducta o comportamiento**: afectan variables como el precio, la calidad de los productos, la cantidad que se transa en los mercados, la publicidad que pueden llevar a cabo las empresas, entre otros.

En los últimos años ha surgido una importante literatura denominada economía del comportamiento, que se encarga de analizar los determinantes psicológicos de la conducta de los agentes, en particular consumidores. La misma enfatiza que los individuos no son lo racionales que la teoría económica sugiere, e impulsa regulaciones de comportamiento que afectan la forma en la que los agentes procesan la información que reciben y toman las decisiones, llamados “empujones” o nudges en inglés. En la medida en que esta literatura está enfocada a modificar la conducta de los demandantes, este texto no abordará la regulación de comportamiento, la que se puede encontrar en textos como [@Sunstein2009 o @Kanheman2015].

La regulación es una las características distintivas de los Estados. Hay normas generales relativas a: defensa de la competencia; defensa del consumidor; quiebra de empresas; sociedades comerciales; habilitaciones para locales comerciales e industriales; normas bromatológicas sobre la calidad de los productos o procesos de producción de alimentos; entre otras. También se dictan normas específicas o sectoriales, como las vinculadas a: las telecomunicaciones; la banca; la energía eléctrica; el transporte aéreo, terrestre y marítimo; los productos lácteos, cárnicos y semillas; y un muy largo etcétera.

En Uruguay, los instrumentos regulatorios utilizados son, básicamente, de dos tipos:

1. Regulación de precios: se fija el precio de la leche fresca; el valor del taxi y del transporte urbano; las cuotas mutuales y el valor de los tiques moderadores en el sector de la salud; el precio de la energía eléctrica;^[En este caso es tenue la línea que separa la regulación de la fijación de precios por parte de la empresa monopólica.] los precios máximos en el mercado del gas licuado de petróleo (GLP) y el de los combustibles, entre otros.
^[En América Latina en general, y en Uruguay en particular, las regulaciones de precio se basan en normas asociadas a las llamadas leyes de abastecimiento, que buscan regular directamente la oferta y el precio de los productos, sancionando penalmente el acaparamiento, entre otras prácticas. En Uruguay, se encuentra vigente la Ley No. 10.940 de setiembre de 1947 (sobre la base de la Ley No. 10.075 de 1941 que regulaba los artículos de primera necesidad) que creó el Consejo Nacional de Subsistencias y Contralor de Precios. Esta norma permite, bajo ciertos parámetros, que el Poder Ejecutivo intervenga y fije el precio de los productos e intervenir empresas y secuestrar sus productos, bajo ciertos supuestos (artículo 13). En la actualidad, Venezuela cuenta con un control similar, a través de la Ley de Precios Justos, que fija el precio para los artículos de primera necesidad. En este caso los controles los realiza la Superintendencia de Precios Justos. También Argentina cuenta con leyes de este tipo desde 1974, con modificaciones introducidas en 2010, véase la [ley No. 20.680](http://infoleg.mecon.gov.ar/infolegInternet/anexos/55000-59999/58603/texact.htm).]

1. Controles a la entrada y salida de los mercados: en el mercado bancario, operan importantes regulaciones —prudenciales— a la entrada y salida de bancos, que incluyen autorización previa por parte del Banco Central del Uruguay (BCU); en la telefonía celular, para entrar al mercado hay que acceder a una frecuencia que la otorga la Unidad Reguladora de los Servicios de Comunicaciones (URSEC); en la telefonía fija está prohibida la entrada a operadores del sector privado; en la habilitación a las farmacias, existe una ley que prohíbe que las mismas se instalen a menos de 300 metros de otra ya existente; en el establecimiento de cualquier emprendimiento de venta de productos alimenticios y de uso doméstico (supermercado) de más de 200 metros cuadrados, la Ley de Protección de la Micro, Pequeña y Mediana Empresa Comercial y Artesanal, establece que se requiere consultar a una comisión asesora del Intendente municipal quien expide la autorización final; en la habilitación a carnicerías se requiere, entre otros, aprobación expresa del Instituto Nacional de Carne (INAC).

Pero ¿cuál es la justificación de la regulación económica? 
^[En esta temática se sigue fundamentalmente a @Viscusi2005, capítulo 10; @Hertog1999; y @Noll1989.] 
En este capítulo se presentan distintas explicaciones desde la ciencia económica, aunque en la actualidad este campo también lo trata la ciencia política. La primera justificación proviene de la teoría del interés público, que establece que el gobierno actúa en forma benevolente para resolver fallas de mercado. 

La segunda se basa en la teoría de la captura regulatoria, en sus distintas versiones, para la cual la regulación es un instrumento utilizado por los grupos de poder para redistribuir renta a su favor. En tercer lugar, se introduce una mirada que va más allá de las particularidades del mercado en sí mismo y la regulación económica se vincula a la interrelación entre el Estado y el sector privado y, en particular, a la forma que tiene el Estado de controlar la convivencia social. Por último, se realiza un detallado análisis de las características de la regulación de monopolios naturales.


## La teoría del interés público

El principal fundamento para la intervención del gobierno en los mercados se basa en la idea de que existen situaciones en las cuales los mercados no conducen al máximo bienestar social, en particular, cuando se producen fallas de mercado. Según esta teoría, la regulación persigue el bienestar general cuando existen fallas de mercado y su objetivo es corregirlas. El gobierno que diseña y ejecuta estas regulaciones lo hace con espíritu benevolente, y no existen costos de transacción para implementarlas. Antes de continuar, conviene discutir qué se entiende por costos de transacción. 

Este concepto tiene distintas definiciones, la más amplia de las cuales establece que son los costos que se incurren para realizar un intercambio económico. Los costos de transacción incluyen: (i) los costos de búsqueda e información, es decir, determinar si el producto está disponible en el mercado, cuál es su precio, quién lo tiene disponible, etc.;(ii) los costos de negociación entre las partes para alcanzar un acuerdo; y (iii) los costos de vigilar y hacer cumplir el contrato refrendado entre las partes. Como puede apreciarse, en la realidad es muy difícil encontrar situaciones en las cuales los costos de transacción entre las partes sean cero.

Esta teoría recibe, al menos, dos críticas. La primera refiere a la propia existencia de una potencial ganancia de eficiencia —condición necesaria para la regulación—, puesto que no explica cómo se logra alcanzar esta ganancia a través de la intervención del gobierno. En otros términos, cómo se pasa de una demanda pública a un resultado concreto normativo con su consiguiente beneficio social. 

En efecto, como señala @Noll1989, existen mecanismos alternativos a la regulación como, por ejemplo, otorgar dinero a las familias de menores recursos en lugar de fijar precios máximos a los bienes. Si ello no es posible, es porque existen otras restricciones o los costos de transacción no son cero. Sin embargo, no hay razón teórica para que los problemas de información que enfrentan los privados, asociados a estos costos de transacción, los puede superar el gobierno. 

Asimismo, regular tiene costos. Estos están vinculados a la necesidad de contratar una burocracia que analice el mercado y monitoree su desempeño, así como a las ineficiencias que pueda generar la propia regulación en el mercado (por ejemplo, menores incentivos al ingreso de empresas si se limita el precio). Otras veces la regulación tiene una inercia propia que dificulta el ajuste de la misma a los cambios en las condiciones de mercado. 

A vía de ejemplo, en Uruguay existe históricamente un precio máximo a la leche fresca, producto del desabastecimiento que sufrió la ciudad de Montevideo en la década del 30 [@Marti2013]. Aun cuando las condiciones de mercado cambiaron sustancialmente, esta regulación se ha mantenido casi por un siglo.
^[Dos problemas adicionales surgen en este análisis. En primer lugar, si por alguna consideración política esta regulación fuera necesaria, ¿qué bienes integran la canasta de productos de primera necesidad, cuyo monitoreo es necesario? En segundo lugar, ¿por qué se regula el precio de la leche, como artículo de primera necesidad, y no se regulan los otros productos que integran esta canasta como la harina o el pan? Las fallas de mercado no explican el porqué de esta regulación.] 
Asimismo, no queda claro que el instrumento elegido (precio máximo) sirva como solución al problema original (desabastecimiento).

La segunda crítica refiere a que se debería observar la regulación sólo en aquellos sectores con fallas de mercado, lo que no siempre se cumple. En muchos países se regulan mercados potencialmente competitivos como el de transporte. En Estados Unidos (EUA) las críticas a este enfoque fueron más fuertes. En la década de los 60, una serie de estudios demostraron que la regulación, más que subsanar las fallas de mercado, tendía a aumentar los beneficios de las industrias. 

El problema radica en que el gobierno no está exento de la falta de información, ni de los costos de transacción antes mencionados, por lo que nada asegura que se puedan alcanzar los resultados óptimos a través de la intervención estatal. Los procesos técnico-políticos que llevan a la conformación de las decisiones gubernamentales son complejos y en ellos, generalmente, intervienen muchos actores con intereses diversos.

Uno de los problemas fundamentales es que regular implica redistribuir riqueza entre los agentes —ya sea productores o consumidores— y ello lo convierte en un mecanismo muy atractivo para que los diversos actores busquen participar en su diseño o implementación.
^[A vía de ejemplo, la Ley de Grandes Superficies que mencionáramos anteriormente tiene como objetivo explícito defender a la micro, pequeña y mediana empresa comercial y artesanal, uno de los miembros de la comisión asesora del Intendente es un representante de estos emprendimientos.]


## La teoría de la captura regulatoria

La evidencia empírica en EUA mostró que, hasta la década de los 60, la regulación no estaba necesariamente correlacionada con las fallas de mercado, sino todo lo contrario. Es decir, muchas regulaciones más que resolver fallas de mercado estaban dirigidas a la protección de las empresas instaladas. Ello llevó al desarrollo de la Teoría de la Captura Regulatoria, la que sostiene que o bien la regulación se realiza en respuesta a las demandas de la industria (los legisladores están capturados por la industria) o las agencias regulatorias, con el paso del tiempo, terminan siendo controladas por las industrias que deberían regular.

@Stigler1971 señala que la regulación es uno de los caminos que tienen los grupos de interés para incrementar su bienestar, utilizando al Estado para que redistribuya riqueza a su favor a costa de otros grupos sociales. El Estado es un agente atractivo para redistribuir riqueza debido a que dispone del poder de coerción. Por tanto, las regulaciones a la entrada de los mercados, o las que imponen costos excesivos o innecesarios a las nuevas empresas, son, según esta teoría, el resultado de la captura del proceso económico por parte de los instalados.

En Uruguay existen distintos ejemplos de normas que se ajustarían a esta teoría. En primer lugar, la [Ley No. 17.715](http://www.parlamento.gub.uy/leyes/AccesoTextoLey.asp?Ley=17715&Anchor=) estableció una distancia mínima parael establecimiento de nuevas farmacias respecto a las ya instaladas y, como resultado, disminuye la competencia potencial de nuevos entrantes sobre los precios de los instalados. En segundo lugar, las leyes [No. 17.188](http://www.parlamento.gub.uy/leyes/AccesoTextoLey.asp?Ley=17188&Anchor=) y [No. 17.657](http://www.parlamento.gub.uy/leyes/AccesoTextoLey.asp?Ley=17657&Anchor=) instauraron restricciones para el establecimiento de grandes superficies (mayores a 200 metros cuadrados). Las mismas crearon una comisión asesora al Intendente de cada departamento, que debe elaborar un informe preceptivo —pero no vinculante— respecto de la conveniencia de la instalación de nuevos supermercados, atendiendo a la demanda excedente, la creación neta de empleos y la desaparición de establecimientos tradicionales. Por último, en el sector de las telecomunicaciones se observa en los últimos años un involucramiento relativamente laxo por parte del órgano regulador (URSEC) a investigar y sancionar posibles prácticas anticompetitivas que realice la empresa estatal ANTEL.

Sin embargo, tampoco es claro que toda la regulación sea el producto de las acciones de los agentes ya instalados en los mercados, como lo demuestra la existencia de subsidios cruzados entre consumidores. En Uruguay, por ejemplo, la regulación fija precios únicos para algunos bienes o servicios, lo que limita la capacidad de las empresas para fijar precios. El ejemplo más claro es el del servicio de taxímetro en el cual la tarifa está regulada (fija), lo que impide que las empresas suban los precios en los momentos de mayor demanda. 

Otras veces, este sesgo surge, más que en las normas en sí mismas, en su aplicación. A las empresas grandes, a veces, se las controla de forma más fuerte y efectiva que a las pequeñas, en el cumplimiento de las normas. A vía de ejemplo, la empresa papelera UPM (ex BOTNIA) ha tenido que cumplir con exigentes normativas para poder construir su planta y existen distintos puntos de monitoreo, a lo largo del Río Uruguay, para estudiar la calidad del agua. En el otro extremo, el control de la contaminación de los ríos ha sido históricamente un objetivo de segundo orden por parte de las autoridades departamentales [@Caffera2004]. En efecto, la Intendencia Municipal de Montevideo —al menos en el pasado— ha evitado sancionar a empresas que contaminan los ríos, evitando su posible cierre, con el objetivo de proteger el empleo.

Entonces la pregunta parece ser ¿qué mercados serán los regulados? @Peltzman1976 desarrolla un enfoque teórico que presenta tres componentes: (i) la regulación redistribuye riqueza; (ii) los legisladores actúan guiados por el interés de mantener su puesto, lo que implica que las normas que aprueban están diseñadas para maximizar el apoyo político que reciben; (iii) los grupos de interés
^[Entendidos en sentido amplio: consumidores, empresas establecidas, competidoras, proveedores, trabajadores, etc.] 
compiten para ofrecer apoyo político a cambio de una legislación favorable.

El resultado al que llega es que la regulación estará sesgada a favor de aquellos grupos que estén mejor organizados o ganen más con una legislación favorable, los que estarían más dispuestos a invertir recursos para lograr el apoyo político a sus propuestas. Más específicamente, la regulación beneficiará a pequeños grupos con preferencias más homogéneas a costa de grandes grupos con preferencias heterogéneas, en la medida en que las primeras tienen mayor facilidad para alcanzar consensos relativamente estables entre sus componentes. 

Tras estos argumentos está el efecto del parasitismo: grupos pequeños en los cuales cada miembro tiene mucho para ganar con la legislación, tienen más incentivos para apoyar políticamente la redacción, discusión y aprobación de una ley. Por su parte, los grupos grandes —en general de consumidores— están menos informados sobre el alcance de la normativa e individualmente pierden poco, en relación con lo que gana cada integrante del grupo que se beneficia con la regulación. A la vez, los costos de oponerse a la iniciativa son altos y terminan beneficiando a terceros que no incurren en dichos costos. En este sentido, los costos de organizar grupos numerosos con intereses difusos, donde la acción que pueda desplegar alguno de sus integrantes genera beneficios al resto de los componentes del grupo, hace que sean más vulnerables a la hora de oponerse a iniciativas de los grandes grupos empresariales.

@Peltzman1976 presenta un modelo de fijación de precios por parte de un legislador/regulador que busca maximizar el apoyo político. La función de apoyo político es una función decreciente del precio (porque los consumidores reducen el apoyo si el precio sube) y creciente en los beneficios de la empresa. Por otro lado, los beneficios de las empresas son crecientes en el precio, hasta que alcanzan el valor de monopolio. En este modelo, el precio de equilibrio que elegirá el regulador es aquél que maximice el apoyo político y, a la vez, esté sobre la frontera de beneficios de las empresas. Por tanto, se cumple que el precio de equilibrio estará entre el competitivo y el de monopolio. Como el precio está entre los “extremos” se puede concluir que las industrias que tenderán a estar reguladas son aquellas relativamente competitivas (a demanda de las empresas) o aquellas relativamente monopolísticas (a demanda de los consumidores).Según @Viscusi2005 esta situación es la que se observa en EUA, donde se regulan mercados monopólicos como la telefonía local y de larga distancia, la transmisión de gas y electricidad y los ferrocarriles; o sectores relativamente competitivos como el transporte carretero, los taxis y la producción de energía o gas.

En esta línea, @Noll1989 presenta una vinculación interesante entre la regulación y su retroalimentación con los grupos de interés. En efecto, los sectores regulados, que generalmente obtienen beneficios extraordinarios, construyen a su vez, dentro de las empresas, espacios de negociación de las cuasi rentas obtenidas entre dueños y empleados. Esto no sólo genera distorsiones en la asignación de recursos e ineficiencias productivas (concepto que se desarrollará más adelante), sino que genera resistencia por parte de los propios empleados a modificaciones de las normas regulatorias. Esto es particularmente interesante para Uruguay, donde la oposición a la desregulación de los mercados de combustibles, telecomunicaciones o agua, provino principalmente de los propios empleados de las empresas monopólicas, que posteriormente volcaron a los consumidores a su favor.

Por último, @Becker1983 sostiene que la regulación se da en un contexto de competencia entre grupos de interés. La regulación, según esta visión, es utilizada por aquellos grupos más poderosos para incrementar su bienestar. En última instancia, todos los grupos de interés generan alguna presión para intentar influir sobre las políticas y, a la vez, tienen que vencer el problema del parasitismo. El modelo que desarrolla Becker tiene algunos resultados de política. 

En primer lugar, las políticas regulatorias que se implementarán serán aquellas que mejoran la eficiencia, debido a que las ganancias que obtienen los grupos de interés los inducirán a producir una mayor presión para que se regule. En segundo lugar, y vinculado a lo anterior, los sectores que tenderán a estar regulados son aquellos con más fallas de mercado. Por último, no sólo se regularán los sectores con fallas de mercado, sino también aquellos donde los grupos de interés sean más eficientes para ejercer su presión. En otros términos, no sólo la ganancia de eficiencia determina el resultado, sino la tecnología que utilizan los grupos de presión para obtener su cometido.


## Impuestos a través de la regulación

La regulación no sólo es un instrumento para corregir fallas de mercado o para que grupos de interés obtengan renta a su favor. @Posner1971 sostiene que los gobiernos utilizan la regulación para redistribuir rentas entre consumidores, vía subsidios cruzados en la venta de productos. Ello puede obedecer a distintos factores. Un servicio donde es clásico el subsidio entre sectores es el transporte urbano de pasajeros. Bajo este servicio, que en muchos países tiene características de servicio público, se fija un único precio en todo el transporte, lo que se transforma en un subsidio implícito desde los recorridos de mayor demanda a los de menor demanda. 

Como se verá en el capítulo \@ref(inst-reg), ello tiene efectos sobre la calidad del servicio, en la medida que, para que el mecanismo de subsidio cruzado se pueda sostener, se requiere impedir la entrada a los mercados más rentables, lo que en economía se conoce como el descreme de los mercados. Al existir dos demandas, el precio debería ser menor en el mercado donde la demanda es mayor, debido a que las posibilidades de oferta serán también mayores y los consumidores tienen más oportunidades de arbitraje, mientras que en los mercados con menor demanda habrá menos oferentes y el precio será mayor.

En telefonía, este tipo de subsidio cruzado se le conoce como servicio universal. Por ejemplo, en la telefonía fija, existe una tarifa única en ciudades de alta y baja demanda, cuando el costo unitario de la red es mucho más alto en las ciudades con menor densidad. En este caso, la regulación de único precio —unida a la restricción de entrada al mercado, para evitar el descreme de los consumidores— se utiliza como un instrumento que sustituye a los impuestos, como mecanismo que permite financiar las inversiones. En efecto, los altos costos asociados a la telefonía serán difíciles de recaudar en mercados donde la densidad o los ingresos son menores y, por tanto, un subsidio cruzado vía precio permite que el gobierno realice inversiones en aquellos mercados donde no tiene capacidad de recaudación, y que los consumidores con mayor capacidad los subsidien.

Fijar impuestos a través de la regulación es una práctica factible cuando la tecnología o las instituciones impositivas son débiles, ya sea porque la base tributaria es pequeña, o porque son altos los costos de recaudar, las distorsiones que conlleva la tributación o la evasión. En cualquiera de estos casos, en lugar de fijar un impuesto, recaudarlo, separar el dinero y pagar a la empresa, es más fácil y sencillo que la propia empresa cobre el dinero directamente a través del precio. Ello genera los incentivos adecuados a la empresa para cobrar por el producto. Sin embargo, por otro lado, esta regulación genera barreras a la entrada al mercado que luego son difíciles de alterar.


## Regulación y cumplimiento de las normas

Las teorías anteriores presentan una visión de la regulación como un instrumento en sí mismo, aislado de otros disponibles por los gobiernos para controlar el accionar de las empresas en los mercados. Sin embargo, @Djankov2003 y @Shleifer2005 presenta una visión diferente de la regulación. Sostienen que si la sociedad quiere, por alguna razón, controlar a las empresas privadas dispone de cuatro estrategias diferentes, las que presentan una tensión entre los poderes del Estado y las libertades individuales. Esta tensión, en última instancia, se refleja en que a menor intervención del Estado, mayores son las pérdidas sociales debidas a la expropiación privada (la denominan desorden), mientras que a mayor intervención del Estado mayores son las pérdidas debido a la expropiación del Estado (la denominan dictadura). Si el Estado se retira de la vida privada, los agentes quedan a merced del desorden, pero se minimizan los riesgos de dictadura, mientras que al aumentar la participación del Estado se reduce el desorden, pero aumentan los riesgos de dictadura. En otros términos, los agentes privados pueden expropiarse unos a otros, pero el Estado también puede expropiar a los privados.
^[Esta visión está muy vinculada a las ideas de los derechos de propiedad. Para que estos puedan ejercerse se requiere un Estado que los haga cumplir. Sin embargo, si el Estado no tiene contrapesos, también puede apropiarse de los derechos de los privados.] 

Los cuatro instrumentos de que dispone una sociedad para controlar al sector privado son: (i) la disciplina de mercado; (ii) los litigios judiciales entre privados; (iii) la regulación; y (iv) la propiedad pública. Estas estrategias no son mutuamente excluyentes, dado que en muchas sociedades conviven entre sí. En Uruguay, por ejemplo, existe propiedad pública en el sector de telecomunicaciones, el que a su vez está regulado por un órgano regulador específico, los privados pueden llevar a juicio civil a la empresa pública y, en última instancia, pueden dejar de comprarle. El uso creciente de los instrumentos regulatorios balancea la forma en que la sociedad pondera los riesgos asociados al desorden y la dictadura. La clave es que, a medida que se hace más complejo para la sociedad controlar al sector privado (desorden), se comienza a recorrer un arco de posibilidades que implican una mayor intervención del Estado.

¿Por qué distintas sociedades resuelven un mismo problema de forma diferente? Esta pregunta no tiene una única respuesta. Las capacidades institucionales para regular de los países difieren entre sí. Se observan diferencias en relación con lo que las normas permiten hacer a los reguladores, la capacidad sancionatoria, el grado de tecnificación de la burocracia y la permeabilidad del sistema político a las presiones del sector privado. Asimismo, lo que algunas sociedades toleran que se resuelva a través del Sistema Judicial, otras requieren de una intervención directa del Estado [@Alesina2005]. Lo interesante de este enfoque es que permite comprender en forma amplia la existencia de regulación y empresas públicas. Hay teorías que abordan el tema de las empresas públicas como un asunto político [@Shleifer1994], donde los políticos utilizan a las empresas públicas para mantenerse en el poder. Sin embargo, @Shleifer2005 presenta una visión que fundamenta la existencia de empresas públicas como una solución eficiente desde el punto de vista institucional: dadas las restricciones que enfrentan los Estados, el avance en una dirección regulatoria representa la mejor solución posible para controlar el desorden.


## La regulación de monopolios naturales

Esta sección se centra fundamentalmente en estudiar la regulación de aquellos sectores que no están sometidos a competencia debido a que es eficiente que la producción la lleve a cabo una única empresa. En algunos sectores de la economía —en particular en transmisión de energía, agua potable, saneamiento, vías férreas, o transmisión de datos— la tecnología de producción de bienes y servicios se caracteriza por la existencia de importantes inversiones fijas y hundidas.
^[Las inversiones hundidas son aquellas que una vez realizadas no pueden asignarse a otros usos más allá de los previstos originalmente.]

Ello determina que la provisión de ciertos servicios públicos sea eficiente si la realiza un número limitado de oferentes y, en algunos casos, sólo si lo hace una única empresa. La necesidad de contar con activos fijos que tienen un costo muy importante y que en sí mismos permiten atender a toda la demanda, implica que la duplicación de esta infraestructura sea ineficiente desde el punto de vista económico. Uno de los supuestos que explica la existencia de mercados competitivos es que las empresas que en ellos operan tienen un tamaño tal que con una infraestructura dada no pueden atender a toda la demanda.
^[Los supuestos se completan con la libre entrada y salida de los mercados, la perfecta homogeneidad de los bienes, la ausencia de costos de transacción, información perfecta por parte de los agentes y, en el largo plazo, igual acceso a la tecnología de producción.]
Ello permite que varias empresas puedan coexistir para atender el mercado. Por su parte, cuando es eficiente que una única empresa atienda a todo el mercado se entiende que existe un monopolio natural.
^[Para un desarrollo sencillo de la teoría de monopolio natural ver @Viscusi2005, capítulo 11.]

Para avanzar en este concepto, hay que considerar que la eficiencia económica es un fenómeno que tiene múltiples dimensiones.
^[En @Viscusi2005, capítulo 4, se presenta una exposición del concepto de eficiencia. Para un desarrollo en profundidad ver @Motta2004, capítulo 2.]
Eficiencia refiere a la forma en la que se utilizan los recursos para obtener un determinado nivel de producción. Sin embargo, este concepto tiene dos dimensiones según si la mirada es de corto o largo plazo. En el corto plazo, esto es cuando se considera un mercado o tecnología de producción dada, se define la **eficiencia estática**. 

Por su parte, **la eficiencia dinámica** es un concepto de largo plazo que refiere a la forma en la que se introducen nuevos productos o nuevos procesos de producción. A vía de ejemplo, cuando se habla de eficiencia en el mercado de la telefonía fija se está analizando la eficiencia estática del sector, el producto está dado y la tecnología de producción también. Por su parte, cuando se estudia la introducción de fibra óptica al mercado de transmisión de datos, dado que éste es un producto nuevo que crea un mercado con características diferentes a los existentes —permite brindar más servicios que la tecnología tradicional—, se analiza la eficiencia dinámica.

Este último tipo de eficiencia, implica estudiar los incentivos que tienen los agentes para llevar a cabo actividades de investigación y desarrollo (I+D) que permitan introducir nuevos procesos productivos o desarrollar nuevos productos. La clave está en el proceso por el cual se generan nuevos mercados, sea de productos o procesos de producción. La eficiencia dinámica es esencial en aquellos mercados, como el de las telecomunicaciones, donde la norma es la introducción permanente de nuevas tecnologías. Estas nuevas tecnologías pueden provocar cambios en los mercados existentes y hacer que muchos de ellos desaparezcan o se transformen en forma radical en períodos breves.

A su vez, el énfasis en cada tipo de eficiencia tiene asociada una visión diferente de la competencia. Cuando se analiza la eficiencia estática se está estudiando la competencia **en el mercado**, mientras que si se analiza la eficiencia dinámica el énfasis está en la competencia **por el mercado**. Las competencias en y por el mercado tienen lógicas diferentes aunque en ambas subyace la misma noción de empresas compitiendo entre sí.
^[La importancia de la competencia en el desarrollo económico ha sido desarrollada por @Aghion2005.]

La eficiencia estática se centra en comprender cómo compiten las empresas y cómo utilizan sus recursos productivos en un mercado dado con una tecnología de producción específica; y tiene dos miradas:

1. **eficiencia asignativa** que refiere al excedente o bienestar económico que genera una determinada estructura de mercado. Un mercado competitivo genera un excedente mayor que una estructura monopólica debido a que el monopolio tiene incentivos a restringir la oferta, de forma de aumentar el precio de mercado y sus beneficios. Por tanto, el monopolio genera una ineficiencia asignativa o pérdida de eficiencia asignativa. 

1. **eficiencia productiva** que analiza la forma en la que se utilizan los insumos para generar un nivel de producto dado. La clave es determinar si existe derroche de recursos. Este análisis tiene a su vez dos niveles. Por un lado, si existen diversas tecnologías disponibles, cuál es la que permite obtener un nivel dado de producto al menor costo posible. Por otro lado, para un nivel dado de tecnología, si la misma se utiliza en todo su potencial. En el análisis de la eficiencia productiva surgen diversos factores que determinan que una empresa sea ineficiente. Puede ser el resultado de una mala elección de la tecnología, por ejemplo vender servicios de transmisión de datos utilizando
un par trenzado (cable de cobre) en vez de fibra óptica; 
^[Véase http://es.wikipedia.org/wiki/Medio_de_transmisi%C3%B3n#Medios_de_transmisi.C3.B3n_guiados]
o puede ser el resultado de utilizar fibra óptica pero llegar a pocos clientes y, por tanto, que el servicio sea muy costoso.

La clave en el análisis de la eficiencia productiva está en que la elección de la tecnología y su uso dependen de los incentivos que enfrenten las empresas [@Nickell1997]. En general, la competencia en el mercado se transforma en un incentivo suficiente para que las empresas utilicen la mejor tecnología disponible y la usen al máximo de su potencial, ya que de otra forma corren el riesgo de quebrar.
^[Véase @Motta2004, sección 2.3.2.]
En estos casos la competencia se transforma en un mecanismo de selección de tipo darwinista en el cual sólo sobreviven las empresas más eficientes. Otras veces, la forma de propiedad sirve como incentivo al uso eficiente de los recursos. Si la empresa cotiza sus acciones en la Bolsa y es ineficiente, entonces obtendrá menores beneficios de los potenciales y, por ello, corre el riesgo de perder valor para sus accionistas. Por lo tanto, es más probable que sus gerentes sean despedidos, mecanismo que tienen los accionistas para proteger su inversión.
^[@Laffont1993 señalan que las empresas públicas pueden también sufrir el relevo de sus directivos, o del propio gobierno, pero las causas son generales -no dependen del funcionamiento específico de la empresa- y los incentivos de los políticos a mirar el resultado de la empresa son menores a los de los inversores.]

La existencia de un monopolio natural en determinados mercados, se explica por la eficiencia productiva. Cuando resulta eficiente que la producción del bien o servicio se realice en una única empresa —los costos de producción son menores respecto a fragmentar la producción en varias firmas—, entonces existe un monopolio natural. Es claro que esta característica de la función de costos depende, también, de la forma de la demanda. Cuanto menor sea la demanda más factible es que la inversión realizada por una única empresa alcance para atenderla. En Uruguay, una única planta de refinamiento de petróleo es suficiente para abastecer a todo el mercado interno, lo que resultaría imposible en el caso de Argentina, que cuenta con unas diez refinerías de petróleo.

Cuando es eficiente que una única empresa sirva al mercado (eficiencia productiva), esta única empresa, si maximiza beneficios, se comportará como un monopolista. A menor competencia en el mercado, donde el monopolio es la expresión extrema, más restringirán las empresas su producción de forma tal que los productos resulten escasos y los consumidores paguen precios mayores por los mismos. 

Por tanto, estos mercados conllevan un compromiso entre eficiencias que tienen direcciones opuestas: por un lado, la eficiencia productiva —costos— favorece la existencia de una única empresa en el mercado; por otro, la eficiencia asignativa —poder de mercado— implica que surja el riesgo de abuso de posición de dominio por parte del único oferente. La forma en la que los Estados han resuelto este compromiso es permitir la existencia de una única empresa, pero regular su precio para evitar abusos. Este balance explica el surgimiento de la regulación por parte del Estado.

Los servicios públicos, generalmente, se encuentra en mercados donde al menos un componente de la actividad constituye un monopolio natural. Estos servicios se caracterizan por: (i) un alto monto y especificidad de los activos involucrados; (ii) la existencia de economías de escala o de variedad; y (iii) el consumo masivo de muchos de los bienes y servicios que producen. Las **economías de escala** implican que los costos unitarios de producción decrecen a medida que la producción se expande, mientras que las **economías de variedad** indican que la producción conjunta de determinados bienes presenta costos menores que si se producen en forma separada [@Bergara2003]. Ambas economías explican la existencia de monopolios naturales.

Asimismo, en la provisión de muchos servicios públicos se observa sectores de onopolio natural que conviven con segmentos potencialmente competitivos. Por ejemplo, el servicio de electricidad tiene distintos componentes: generación, transmisión y distribución. Mientras la transmisión eléctrica es un ejemplo típico de monopolio natural, tanto la generación como la distribución son segmentos donde puede operar la competencia.
^[Una descripción detallada del sector eléctrico se puede encontrar en @Viscusi2005,capítulo 12.]
Por su parte, la fibra óptica —que tiene características de monopolio natural— es un insumo necesario para actividades que se desarrollan en mercados que pueden ser competitivos como la transmisión de datos, ya sea telefonía, internet o televisión para abonados.
^[No hay estudio para Uruguay que concluya que la fibra óptica sea un monopolio natural, aunque existen pistas de que si podría serlo en muchos mercados geográficos.]

A modo de resumen, en el Tabla \@ref(tab:cuadro1) se presentan los principales tipos de eficiencia y su impacto sobre la estructura de mercado.
  
\

```{r cuadro1, echo=FALSE}

base <- read.csv("bases/cuadro1.csv")
knitr::kable(base, col.names = c("Tipo de eficiencia","Tipo de competencia","Categorías","Características","Efecto de la competencia"), caption = 'Tipos de eficiencia, características e impacto sobre estructuras de mercado.')

```

Fuente: elaboración propia.

La regulación surge como un mecanismo para controlar los incentivos que tienen las empresas monopólicas a cobrar precios abusivos a los consumidores, es decir resolver una falla de mercado. Como resultado de la misma, el mercado se suplanta por un mecanismo burocrático que define varias de las variables relevantes: el precio, la calidad de los productos, o las inversiones que puede o no realizar la empresa. La regulación no es una solución perfecta, en la medida en que los reguladores tienen en general menos información que la empresa regulada y ello puede impedir alcanzar resultados de primer óptimo.
^[El resultado de primer óptimo es el que se obtendría si el regulador tuviera el mismo nivel de información que la empresa. Si ello no es así, entonces ese resultado no se puede implementar, y se deben establecer valores de las variables que induzcan a las empresas a revelar su información y a reducir, en la medida de lo posible, las distorsiones de eficiencia.]
Sin embargo, es aceptado que en el caso de los monopolios naturales es preferible un mecanismo que concentre la producción en una empresa —eficiencia productiva— y que regule las demás variables relevantes para evitar el abuso vía precio —eficiencia asignativa.

La regulación tiene en sí misma complejos problemas de implementación: ¿cuál es la discrecionalidad óptima del regulador?; ¿cómo se debe fijar y revisar las tarifas?; ¿qué costos deben considerarse?; ¿cuál es la tasa de retorno adecuada de los proyectos?; ¿qué mínimos de calidad se deben exigir a las empresas?; ¿qué justificaciones se aceptan para los apartamientos?; ¿se prevé la expropiación de la empresa o no?; ¿se puede introducir nueva competencia en mercados relacionados? Todos estos elementos determinan la forma en la que se diseñan las instituciones regulatorias e involucran un fino balance entre flexibilidad y expropiación [@Bergara2003; @Spiller2013].
^[La regulación de servicios públicos, por su naturaleza, presenta dificultades a la hora de fijar reglas claras y hacerlas cumplir, siendo el marco institucional que delimita estas actividades un ingrediente clave para alcanzar los objetivos regulatorios [@Bergara2003].]

Por otra parte, el órgano regulador dispone de diversos instrumentos a los efectos de evaluar y sancionar a las empresas que no cumplan con las regulaciones establecidas. En primer lugar, partiendo del paradigma tradicional regulatorio, donde las empresas tienen como objetivo claramente establecido maximizar los beneficios que obtienen por realizar la actividad productiva [@Armstrong2007], un instrumento sencillo, a los efectos de alinear los objetivos de las empresas a los del regulador en las variables relevantes, es la aplicación de sanciones pecuniarias. Toda vez que la empresa incumpla con los términos del servicio, el regulador impone una sanción que reduce los beneficios de la empresa. Si la sanción es mayor al beneficio que obtiene la empresa por no cumplir con los objetivos impuestos por el regulador, entonces, evitará incurrir en estos comportamientos.
^[Véase [@Becker1968]]

Un segundo elemento que incide en el comportamiento de las empresas privadas es su reputación. Si la empresa cotiza en Bolsa, esto es, obtiene su financiamiento a través del mercado de capitales, cualquier sanción que efectúe el regulador tendrá no sólo el efecto directo sobre los beneficios de la empresa, sino también sobre el valor de las acciones para sus titulares, lo que impacta en las decisiones que adoptan los gerentes.

Un tercer elemento, que recoge la historia de las empresas públicas en Uruguay, refiere a la amenaza de estatizar los servicios públicos. En efecto, si la calidad de los servicios prestados es deficiente, o si la empresa incumple lo establecidoen el contrato de concesión, entonces existe la posibilidad de que el Estado asuma la responsabilidad de la prestación del servicio, desplazando a la empresa privada. En la medida en que los servicios públicos tienen características de monopolio natural y el Estado es el responsable de que los mismos se brinden en forma adecuada a sus ciudadanos, si fallan los instrumentos regulatorios para alcanzar este objetivo, entonces el Estado debe hacerse cargo del servicio en cuestión. En estos tres casos, la regulación puede incidir sobre el accionar de la empresa privada a través de las sanciones económicas.

Asimismo, la provisión de servicios públicos por parte de empresas privadas implica alguna relación contractual entre el gobierno y la empresa proveedora. Esta relación puede establecerse a través de una concesión, una licencia, una autorización, u otra figura jurídica. En general, estos contratos establecen los objetivos generales de la tarea que debe realizar la empresa como operador, y el rol regulador y planificador del gobierno. 

Sin embargo, la lógica regulatoria es diferente en el caso de empresas públicas. Estas empresas pueden perseguir objetivos distintos a la eficiencia y, por tanto, la regulación de empresas privadas y públicas encuentra límites diferentes. Sin embargo, la regulación de empresas públicas se encuentra con políticas cuya aplicación puede ser discutible y, por tanto, los instrumentos regulatorios tradicionales no pueden aplicarse en esos casos.


## Conclusiones

La regulación es uno de los instrumentos con los que cuentan los Estados para intervenir en los mercados. Las regulaciones pueden obedecer a factores económicos o sociales. Si bien su origen ha estado vinculado a las fallas de mercado, también puede deberse a problemas redistributivos.
^[Es decir, las fallas de mercado no son condición necesaria ni suficiente para la regulación.]
Las teorías queexplican la regulación van desde una visión optimista del Estado, en términos de su accionar desinteresado para resolver los problemas del mercado, hasta hipótesis que explican la regulación como el resultado de un proceso de captura por parte de la industria para obtener rentas. 

En cualquier caso, la regulación es un proceso complejo [@Dixit1998]. Involucra el diseño de una institución reguladora, dotarla con fondos necesarios para llevar a cabo su tarea y con funcionarios capacitados para cumplir sus objetivos. Sus cometidos requieren un adecuado balance para que las instituciones sean efectivas. Por un lado, tienen que estar diseñados de forma lo suficientemente amplia para atender los problemas que motivaron su creación, evitando el arbitraje regulatorio por el cual las empresas eluden controles si pueden realizar acciones que no están reguladas, pero que generan los mismos efectos sobre el mercado que las que sí lo están . Por otro, estos controles deben ser lo suficientemente específicos para evitar que los reguladores se extralimiten en sus tareas o persigan otros intereses a los previstos.

No debe olvidarse que los reguladores, por más bien intencionados que puedan estar y aunque dispongan de recursos adecuados, contarán siempre con menos información que las empresas que deben regular. Ello determina que siempre estén un paso atrás de las empresas. Asimismo, como se verá en el capítulo \@ref(inst-reg), la decisión de regular un mercado afecta a un conjunto de variables y ello debe ser considerado a la hora del diseño regulatorio. Muchas veces fijar una variable altera los incentivos de los agentes y tiene impacto sobre otras de ellas, lo que puede más que compensar el efecto positivo original de la regulación.
^[Un típico ejemplo son los precios máximos en mercados competitivos, que generan escasez.]
Por último, cuando el Estado regula será responsable, tanto de los buenos como de los malos resultados del mercado. La regulación genera siempre efectos sobre la eficiencia de los mercados.