# Defensa de la competencia ^[Este capítulo fue escrito sobre la base de diversos cursos que el autor dictó en universidades (Facultad de Ciencias Sociales – UdelaR, Universidad de la Habana, Universidad de Montevideo) y organismos (Ministerio de Economía y Finanzas – Uruguay). En general está construido basándose en los textos de Buccirossi (2008), @Motta2004 y @Viscusi2005. Sin embargo, la referencia concreta de cada cita se ha perdido con el tiempo, por lo que el lector debe considerar que en su mayoría este no es un texto original y que el material corresponde a los autores citados.] {#def-comp}


Leandro Zipitría


\


Las economías modernas asignan un rol fundamental a los mercados en la asignación de recursos. En general, se considera que estos asignan los recursos en forma eficiente. Sin embargo, en otros casos el accionar de los agentes impide que los mercados alcancen por sí mismos la máxima eficiencia posible. Las bondades de la competencia, que permiten a los consumidores obtener productos a los mejores precios y de la mayor calidad posible, requiere de políticas públicas que la incentiven y la protejan. 

Mientras que la regulación busca suplantar al mercado en la determinación de alguna de las variables relevantes, defensa de la competencia busca impedir que las empresas eviten o impidan el accionar del mercado. En otros términos, a través del instrumento de defensa de la competencia no se establecen las variables de mercado, las que serán determinadas en última instancia por la oferta y la demanda. Esta herramienta busca desalentar aquellas acciones que realizan las empresas que impidan el ajuste de mercado. 

En competencia perfecta el mercado ajusta —principalmente porque los bienes son homogéneos, no hay barreras a la entrada y la salida, y los agentes están atomizados— y permite alcanzar el mejor resultado desde el punto de vista social. Sin embargo, en la realidad las empresas enfrentan barreras para entrar a los mercados, los bienes no son homogéneos, y las empresas no están atomizadas. Ello genera mercados oligopólicos en los cuales algunas de las empresas tienen la capacidad de manejar el mercado para favorecerlas.

Esas acciones son las que defensa de la competencia busca corregir. Desde el punto de vista metodológico, defensa de la competencia es un instrumento que permite analizar los mercados y determinar cuáles son los principales cuellos de botella que enfrenta la competencia. Por tanto, es una herramienta cuya utilidad trasciende los límites de las investigaciones puntuales y sirve para comprender cómo funcionan los mercados. Es un instrumento válido, aún si los países no cuentan con normas de defensa de la competencia.

Los orígenes de la defensa de la competencia se remontan al Siglo XVI en Inglaterra. Previamente, durante la Edad Media, la regla era el otorgamiento de monopolios o licencias para el desarrollo de la actividad económica por parte de los gobernantes. Esto les permitía a los empresarios obtener parte de las rentas monopólicas de la actividad que desarrollaban. En 1599 en Inglaterra, un Tribunal declara nula una licencia monopólica otorgada por la Corona Británica a un empresario, en el fallo del “caso de los monopolios”.
^[Véase el caso [Darcy vs. Allein](https://en.wikipedia.org/wiki/Darcy_v_Allein).]
Posteriormente, en 1890 en Estados Unidos de América (EUA) se dicta el Acta _Sherman_, la que supone una de las primeras normativas que buscan prevenir el accionar de las empresas monopólicas.
^[En realidad la primer norma de defensa de la competencia fue la _[Act for Prevention and Supression of Combinations Formed in Retraint of Trade](https://www.competitionbureau.gc.ca/eic/site/cb-bc.nsf/eng/04427.html)_, de Canadá del año 1889.]
A partir de allí, las normas de defensa de la competencia se han expandido en el mundo y, en la actualidad, la mayoría de los países cuentan con este tipo de legislación.

Defensa de la competencia se aplica caso a caso, para conductas concretas. Mientras que la regulación fija una variable en un sector de actividad, como por ejemplo el precio del transporte colectivo o el de la energía eléctrica, en defensa de la competencia se analiza si una conducta concreta en un mercado determinado constituye o no una limitación a la competencia. Cualquier decisión que se tome será contingente a esta situación particular y, si bien será indicativa de otras similares, su extensión a otros sectores o empresas requiere de un nuevo análisis.

Antes de desarrollar los conceptos, corresponde realizar una advertencia. La temática de defensa de la competencia ha tenido un desarrollo explosivo en las últimas décadas. Están disponibles en la web cientos de casos tratados por decenas de organismos de defensa de la competencia de múltiples países. Cuando se comienza una investigación concreta, revisar los antecedentes internacionales siempre es valioso ya que permite construir una composición de lugar sobre una situación particular, en general desconocida. Sin embargo, estos antecedentes deben inscribirse en su justo contexto. Las legislaciones de diferentes países varían en el énfasis que ponen en la aplicación de las normas, las que dependen no sólo de lo que la norma establezca sobre prácticas prohibidas o permitidas, sino también del contexto político particular que puede pautar la forma en que la misma se aplica. 

En la medida en que las normas de defensa de la competencia son ambiguas y generales, los procesos de aplicación concreta están sujetos a grandes variaciones entre países. Asimismo, cada caso concreto se puede alejar, a veces en forma importante, de lo que la teoría establece respecto a una conducta en particular (por ejemplo, en el caso de la fijación de precios de reventa en la Unión Europea). En otros casos, existe discrecionalidad respecto a los umbrales de dominancia (¿a partir de qué punto una empresa es dominante?). Aún más, las legislaciones difieren en la forma en la que se analiza una conducta, como por ejemplo en el caso de precios predatorios. Todos estos elementos hacen que los antecedentes internacionales sean útiles, siempre y cuando se analicen en contexto.

¿Cuál es el objetivo de la defensa de la competencia? Existen diferencias entre lo que postula la teoría y lo que cada legislación establece. En teoría, la defensa de la competencia busca proteger el funcionamiento del mercado, entendido como un instrumento para asignar recursos en la economía. Este decide, en teoría, cuantos bienes se producen y cuál debe ser su precio. En los mercados, el precio se transforma en la señal que los agentes —demandantes y oferentes— miran para comprar los bienes o asignar recursos productivos. Pero con defensa de la competencia ¿qué es lo que específicamente se protege? En particular, los mercados son un mecanismo eficiente de asignación de recursos, por tanto el objetivo de la defensa de la competencia es proteger la eficiencia. En particular, se busca sancionar conductas que reducen el bienestar de los agentes, donde el bienestar está medido en términos de excedente del consumidor y del productor. El análisis de estas variables económicas permite hacer una evaluación del impacto de cada conducta. 

Sin embargo, algunas conductas tienen distintos impactos según si se miden en términos de excedente del consumidor o excedente total. Esta diferencia entre las medidas de bienestar ha provocado discrepancia en la aplicación de las normas de competencia, aunque parece existir una convergencia a nivel mundial a utilizar el excedente del consumidor
como regla general [@Motta2004, capítulo 2]. 

El impacto de la conducta de los agentes sobre la eficiencia se refleja en el mercado de forma bastante simple. Las prácticas que se analizan —anticompetitivas— son aquellas que tienen impacto sobre los precios o sobre la variedad de productos y tienen un impacto negativo sobre el bienestar económico. A vía de ejemplo, supongamos que se produce un incremento en el precio de un producto. Si este incremento obedece a un aumento en la demanda, entonces se verifica el ajuste natural del mercado. Sin embargo, si el incremento se produce debido al acuerdo entre los oferentes para mejorar sus márgenes —un cartel—, entonces el mecanismo competitivo ha dejado de actuar y las empresas deben ser sancionadas. Por tanto, una buena regla para entender el funcionamiento del mercado es investigar las razones económicas que están detrás de los fenómenos observados.

Las normas de competencia se aplican de distintas formas. Por un lado, los órganos de defensa de la competencia pueden realizar estudios de mercados y sugerir criterios que atiendan a un funcionamiento más eficiente. Otras veces, estudian las regulaciones del gobierno y sugieren cambios que reduzcan barreras innecesarias a la entrada o restricciones al normal funcionamiento de los mercados. Por último, la aplicación a casos concretos, en general, se realiza a través de un procedimiento que puede ser judicial o administrativo, y que es similar a un juicio. En estos casos, se inicia un expediente y se presentan pruebas respecto a la conducta investigada, se analiza el mercado y con posterioridad se falla. Sobre este fallo surgen luego recursos administrativos o judiciales hasta que la sentencia final queda firme. Es decir, es un proceso largo y complejo.

A su vez, las normas de defensa de la competencia pueden ser interpretadas de dos formas. Por un lado, las normas pueden tener una interpretación estricta, conocida como per se, a través de las cuáles las conductas se sancionan en sí mismas por el sólo hecho de ser llevadas a cabo y con independencia de sus efectos. Por otro, las normas pueden estar sujetas a la regla de la razón, 4 por el cual se establece que las normas de defensa de la competencia no pueden ser interpretadas en forma literal, sino que debe analizarse si las conductas realizadas restringen el comercio, es decir se analiza sus efectos.

La metodología de defensa de la competencia busca comprender el funcionamiento de los mercados y determinar los cuellos de botella que permiten a las empresas obtener rentas extraordinarias. En principio, todas aquellas conductas que realizan las empresas y que les permite obtener renta sin trasladar beneficios a los consumidores son susceptibles de perjudicar el bienestar y pueden considerarse conductas anticompetitivas. 

El primer paso en el análisis es tratar de determinar si las empresas pueden, a través de sus conductas, ejercer un poder de mercado. Este concepto económico es difícil de determinar en la práctica, y por ello se aproxima a través de mecanismos indirectos. El mercado relevante es un instrumento útil para comprender el funcionamiento del mercado, entender sus componentes en términos de productos y áreas geográficas y comprender la cadena vertical que permite que los consumidores accedan a los productos. En última instancia, comprender la competencia en el mercado. 
Diversas son las conductas anticompetitivas que se investigan en defensa de la competencia. La más importante es el abuso de posición dominante que permite a las empresas comportamientos monopólicos. Por otra parte, las canastas o la discriminación de precios son conductas que en ciertos contextos facultan a las empresas a aumentar sus precios a los consumidores. La depredación, por su parte, busca directamente eliminar la competencia y aumentar los precios a los consumidores. Estas acciones consolidan una posición innecesaria para las empresas desde el punto de vista social.

Por otra parte, aun cuando las empresas no sean lo suficientemente grandes como para imponer sus condiciones al mercado, pueden lograr un cometido similar si logran restringir la competencia entre sí. Cuando dos empresas compe-
tidoras acuerdan no competir, están coludiendo en el mercado. Las licitaciones se acuerdan para perjudicar a gobiernos y empresas, los clientes se reparten para restringir sus alternativas, las mejoras se evitan ya que la competencia no es necesaria. Estos acuerdos destruyen la propia esencia del mercado y son de las conductas más perjudiciales.

En las economías modernas los procesos productivos que llevan a que los consumidores disfruten de ciertos bienes y servicios son muy complejos. En muchos de estos procesos intervienen un conjunto de empresas en distintos niveles de la cadena de producción y distribución. La interrelación entre estas empresas lleva a un complejo entramado contractual que puede afectar el precio o la calidad de los productos a que accede el consumidor. A veces, las empresas pueden tener dificultades para acceder a insumos para fabricar sus productos, o a los minoristas para exhibirlos. Estas restricciones verticales pueden afectar la competencia en los mercados, con el consiguiente perjuicio a los consumidores.

Las empresas pueden crecer —vertical u horizontalmente— introduciendo mejoras en sus productos, expandiendo la capacidad o expandiendo sus puntos de venta. Otras veces, para alcanzar los mismos fines se fusionan con empresas relacionadas. Sin embargo, ello produce distintos resultados que pueden afectar la competencia en el mercado. Una fusión horizontal puede mejorar y hacer más eficiente la capacidad de producción, pero también elimina un competidor y puede permitir cobrar precios mayores. Una fusión vertical puede permitir internalizar procesos y mejorar su control, pero también puede impedir que empresas rivales accedan a insumos estratégicos. Otras fusiones, sin embargo, se realizan entre empresas que no están en capacidad de afectar a los mercados.

En las secciones siguientes se desarrolla la temática de defensa de la competencia. En primer lugar, se analiza la importancia que tiene investigar el funcionamiento del mercado y la participación de los agentes. En las siguientes tres secciones se desmenuzan distintas conductas que realizan las empresas en los mercados: abuso de posición dominante, colusión e integración vertical. En estas secciones no se presentarán los modelos teóricos que explican los efectos anticompetitivos de las conductas, que se pueden encontrar desarrollados en @Motta2004. En cada caso, el énfasis estará en los aspectos prácticos de las conductas y sus efectos, pero inscriptos en su racionalidad económica. Por último, se analizan las fusiones y adquisiciones, conductas que afectan la estructura del mercado.


## Mercado relevante y poder de mercado

El principal objetivo de defensa de la competencia es evitar conductas de empresas que les permita ejercer o incrementar su poder de mercado, que es la capacidad que tienen de fijar precios por encima del precio de competencia. Para entender este concepto hay que comparar la situación actual con una alternativa. El menor precio que se puede fijar en un mercado se observa cuando el mercado es perfectamente competitivo. Toda vez que el mercado se aleja de esta situación, los precios tienden a ser mayores, siendo el monopolio la estructura de mercado con el precio más alto posible. Es decir, cuanto menor es la competencia más fácil es para las empresas aumentar el precio. O a la inversa, la competencia permite que los precios de los productos se reduzcan.

Por tanto, la pregunta que sobrevuela el análisis en defensa de la competencia es: ¿permite la conducta de la empresa aumentar o mantener los precios de sus productos? Evaluar el impacto de una conducta sobre el mercado, en general, y los precios, en particular, puede ser complejo. Hay que establecer un vínculo causal entre un fenómeno y un determinado resultado en el mercado. Por un lado, puede ser que la conducta anticompetitiva de la empresa no se haya materializado y, por tanto, no hay evidencia concreta del impacto de la misma. Por otro, muchas veces confluyen múltiples factores en forma simultánea que pueden explicar un mismo fenómeno: hay un aumento de salarios, la demanda externa se resiente, los costos aumentan, entre otros. 

Aislar estos fenómenos de aquel bajo estudio —la supuesta conducta anticompetitiva— es una tarea compleja e intensiva en información. Sin embargo, algunas veces sí puede identificarse con relativa certidumbre la relación entre dos fenómenos, como cuando aumentan los precios de un producto luego de que los productores se han puesto de acuerdo.

La evaluación directa del efecto de una conducta sobre el precio es más un hecho excepcional que lo normal en defensa de la competencia. La sofisticación técnica de estos análisis —no sólo para su realización, sino también para la adecuada interpretación de sus resultados— determina que el más utilizado, para determinar la ilicitud de una determinada conducta, sea establecer el mercado relevante. La determinación del mercado relevante es parte de una alternativa metodológica que intenta analizar los efectos de las conductas de los agentes en los mercados. Básicamente, consiste en construir un discurso que, a través del análisis del mercado (empresas, características del producto, barreras a la entrada) y el tipo de conducta, permita concluir sobre los efectos perjudiciales de esta última. 

Implica, también, considerar explicaciones alternativas a la conducta y los efectos que ella podría tener sobre el mercado, así como los posibles beneficios de la conducta, ya que son pocas las conductas que son siempre perjudiciales. En resumen, el mecanismo alternativo para determinar el poder de mercado de la empresa involucra: (i) determinar el mercado relevante; (ii) determinar las cuotas de mercado de las empresas en el mercado
definido previamente; y (iii) analizar la importancia de las barreras a la entrada en ese mercado.


### Mercado relevante

El mercado relevante es el mercado en el cual es vendido un producto particular. El origen de este concepto está en el modelo de empresa dominante, uno de los modelos específicos de la organización industrial.
^[Véase @Landes1981]
Este modelo es un monopolio atenuado, donde existe una empresa dominante y un conjunto de empresas pequeñas que se comportan como precio aceptantes (franja competitiva). La empresa dominante fija el precio en el mercado, pero toma en cuenta a la franja competitiva en la medida en que sabe que si aumenta los precios inducirá a las empresas pequeñas a aumentar la oferta. El poder de mercado en este modelo —es decir, la capacidad de aumentar los precios sobre los competitivos— depende de varios factores. En primer lugar, cuanto más elástica sea la demanda —mayor la respuesta de la cantidad demandada ante cambios en los precios— menor será el poder de mercado de cualquier empresa. 

En segundo lugar, cuanto mayor sea la cuota de mercado de la empresa dominante, más fácilmente podrá subir los precios. Por último, cuanto menor sea la respuesta de la franja competitiva, también mayor será la posibilidad de que la empresa dominante pueda aumentar sus precios. Este último resultado puede deberse a: (i) la franja competitiva está operando sobre el máximo de su capacidad instalada; (ii) existen barreras que impiden a nuevas empresas entrar al mercado; u (iii) operan restricciones a la importación del mismo producto de otras
regiones. 

Por tanto, este modelo sienta las bases para el análisis del mercado relevante del bien o servicio bajo estudio.
Antes de formalizar la determinación del mercado relevante, debe reiterarse que es una herramienta que permite deducir el poder de mercado de la o las empresas investigadas. No es una finalidad de la investigación determinar el mercado relevante, sino que sirve para determinar la posición de mercado de las empresas. 

El mercado relevante tiene dos componentes: (i) el mercado relevante de producto, y (ii) el mercado relevante geográfico. En ambos, la clave para su determinación es considerar los productos sustitutos, tanto desde el
punto de vista de la oferta como de la demanda.

La Unión Europea establece que el mercado relevante de producto “se compone de todos aquellos bienes o servicios que los consumidores ven como intercambiables o sustituibles ya sea por las características del producto, su precio
o uso” [@UE1997]. Esta definición está sesgada a considerar factores desde el lado de la demanda del producto, aunque en la realidad también se considera la posibilidad de sustituir oferentes (recordar el modelo de empresa dominante anteriormente señalado). 

Hay productos donde la demanda es relativamente clara: muchos tratamientos médicos cuentan con un número limitado de alternativas (diálisis para los pacientes con insuficiencia renal crónica; insulina para los pacientes diabéticos); en la construcción se puede utilizar algunos insumos pero no otros (hormigón armado en vez de madera, o hierro para los pilotes de la estructura); las computadoras requieren un sistema operativo para poder funcionar. En otros casos la línea es más tenue, pero igualmente puede afinarse el análisis para determinar el mercado específico objeto de estudio. Un ejemplo clásico es el de los automóviles, donde existen múltiples calidades y precios. En estos casos, corresponde analizar un mercado más pequeño, como ser los de alta gama o los de bajo precio, dado que en general atienden a consumidores distintos y no se solapan entre sí. Sin embargo, en otros casos la sustituibilidad puede ser asimétrica: la cerveza premium en Uruguay puede tener como sustituta al vino de calidad preferente (VCP), pero el vino VCP puede ser sustituido con cerveza común o con otras bebidas alcohólicas. 

No hay regla en este análisis, dado que dependerá de las preferencias —gustos— de los consumidores, las que son relativamente estables pero pueden variar en el mediano plazo. Además, varían también entre países dependiendo de las costumbres y las culturas.

Comenzando el análisis de la sustituibilidad del producto por el lado de la demanda, corresponde luego determinar la misma por el lado de la oferta. En particular, ¿las empresas en el mercado tienen capacidad ociosa?; ¿pueden entrar otras empresas al mercado, ya sea porque se pueden dedican a producir otros bienes o porque son entrantes nuevos, con relativa facilidad? La interesante es establecer cómo opera este mecanismo para determinar el mercado relevante de producto. 

Supongamos que el mercado que se analiza es el del papel para producir hojas para utilizar en máquinas impresoras. Desde el punto de vista de la demanda es un mercado relativamente determinado: para imprimir se requiere determinado tipo de hojas, con una dimensión y espesor dado para que cumpla su función. Sin embargo, desde el punto de vista de la oferta, las empresas pueden sustituir fácilmente papel de distintos tamaños y gramajes a la hora de producir, dado que la tecnología de producción lo permite. Supongamos, también, que los productores de cartón pueden pasar en forma rápida a producir papel para impresión, si a alguna empresa se le ocurre subir el precio. Entonces: (i) por el lado de la demanda la sustituibilidad está acotada; (ii) por el lado de la oferta, se puede incorporar al mercado de producto los demás papeles de la industria (agrandar el mercado); y (iii) también se puede incorporar a los productores de cartón, dado que ellos pueden pasar a producir el bien de forma rápida. En este ejemplo, el mercado de producto estará constituido por los productores de papel y cartón, es decir, el mercado relevante será el más grande de los mercados definidos por la oferta y la demanda.

Una vez determinado un mercado relevante de producto, corresponde restringir el área geográfica donde operan las empresas. La clave en este caso es la posibilidad de sustituir o no oferta de otros lugares geográficos, ya sea por parte de oferentes o demandantes. Hay productos que son locales, como por ejemplo el corte de cabello; otros son globales, como los aviones. La diferencia entre ambos es que en el primer caso, los costos de transporte son muy altos con relación al producto (no tiene mucho sentido viajar sólo para cortarse el cabello), mientras que en el segundo es a la inversa (transportar un avión es relativamente barato en comparación a construirlo). 

La @UE1997 define el mercado relevante geográfico como “el área en el cual las empresas están involucradas en la oferta y demanda de productos o servicios, y en los cuales las condiciones de competencia son lo suficientemente homogéneas que pueden distinguirse de áreas vecinas”. En estos casos, el rol de las importaciones, los aranceles y los costos de transporte son clave para determinar la extensión del mercado geográfico. Asimismo, también dependerá de las características del producto: si el producto es el servicio de diálisis no parece correcto tomar un espacio geográfico mayor a una ciudad (y en algunos casos esto sería excesivo); si el producto es hormigón armado, este tiene un tiempo de desplazamiento antes de comenzar a fraguar; si el producto es cerveza, si la distancia que debe trasladarse es muy importante, entonces el producto se encarece fuertemente respecto a su costo de producción y deja de ser competitivo. 

Es difícil establecer una regla general para determinar el mercado geográfico, ya que dependerá de las características del producto y del país.

En conclusión, definir el mercado relevante no es una tarea sencilla. Implica conocer cómo actúan los consumidores, las características intrínsecas del producto, su proceso productivo, los costos de almacenamiento y transporte así como los aranceles, la forma en la que se distribuye y llega al público, y un largo etcétera. Sin embargo, estos elementos pueden ser construidos a través de evidencia cualitativa, como entrevistas a informantes calificados o encuestas a consumidores. 

También se puede analizar evidencia cuantitativa si se dispone de alguna información básica. Para recolectar evidencia respecto al mercado relevante, una primera aproximación es la que puedan aportar informantes calificados. Todos los mercados cuentan con agentes que tienen información sobre su funcionamiento, ya sean públicos o privados, que pueden ayudar a entender cómo opera. El único problema en estos casos es determinar si estas declaraciones son producto de un agente imparcial o si este tiene intereses en el asunto en cuestión. Estos informantes permiten también clarificar donde se encuentra el nudo del problema, o qué información puede estar disponible para complementar los estudios.

Como alternativa a esta aproximación, se pueden realizar encuestas a los consumidores o experimentos. Ambas estrategias deben estar bien diseñadas para que sus conclusiones sean válidas y, en general, son costosas. Los experimentos son mejores a las encuestas, ya que permiten estudiar el comportamiento de los consumidores en situaciones reales, mientras que las últimas refieren a situaciones hipotéticas.
^[Un experimento interesante es el de @Conlon2013.]

Es importante tener una guía respecto a qué información se quiere obtener,pero el procedimiento para alcanzarla debe ser flexible, de forma de poder lidiar con los múltiples obstáculos que surgen en una investigación de defensa de la competencia. No toda la información necesaria estará disponible, lo importante es analizar la consistencia de la información útil para la investigación con la que sí está disponible. En muchos casos, esa consistencia estará dada por los distintos modelos económicos que explican el comportamiento de los agentes en el mercado. Estos modelos tienen una lógica que permite predecir cómo se comportarán los agentes, y a ellos se recurre para interpretar la realidad.

El análisis cualitativo puede completarse con un análisis cuantitativo. Existen algunos métodos sencillos que permiten aportar información sobre el mercado relevante con relativamente poca información.
^[Véase @Haldrup2003 como referencia general a estos modelos.]
Por ejemplo, si dos bienes están en el mismo mercado relevante, los precios de los bienes deberían evolucionar de forma similar. Supongamos que la cerveza y el vino forman parte del mismo mercado, es decir son sustitutos cercanos.
^[Basado en @Zipitria2010.]
Entonces el precio de la cerveza y el vino deberían tener comportamientos similares: si los productores de cerveza suben el precio (o a la inversa), los consumidores se pasan al vino y el precio del vino sube. 

Las series de precio estarán correlacionadas y el coeficiente de correlación mide el grado de relación lineal entre las dos variables. Este estadístico varía entre –1 y 1. Si toma el valor 0, entonces las series son independientes; si toma el valor 1 las series son perfectamente idénticas. El signo positivo o negativo refiere al tipo de relación: si es positivo, las dos series varían en la misma dirección, si es negativo varían en dirección contraria. Si dos bienes pertenecen al mismo mercado, se debería esperar una fuerte correlación positiva. Por el contrario, si la correlación es negativa, los bienes son complementarios antes que sustitutos: si aumenta el precio de un bien cae su demanda y, por tanto, la demanda del bien complementario, lo que reduce el precio de este bien, o sea, los precios tienen trayectorias opuestas. 

Esta correlación negativa debe ser fuerte porque en las series de precio agregadas existe una fuerte inercia entre los precios de los productos, como resultado de la inflación o de la propia tendencia general de precios de la economía. Este test, en función de los coeficientes de correlación, se utilizan fundamentalmente para descartar que los bienes pertenezcan al mismo mercado, en el caso de que la correlación sea negativa o baja (menor a 0,8). En cambio, si la correlación es alta, no se puede sacar ninguna conclusión ya que esta relación puede obedecer a otros factores, como insumos comunes o a la tendencia general de precios de la economía. Es decir, en caso de que el test de correlación sea positivo la relación puede resultar espúrea.

Un test más sofisticado es el de cointegración. Si las series son no estacionarias, lo que en estadística implica que tienen una tendencia aleatoria, entonces se puede investigar si dos o más series de precio tienen un sendero aleatorio común.
^[Véase @Haldrup2003.]
A diferencia del test anterior, este sí permite concluir si dos productos pertenecen al mismo mercado, a lo que se llega si se puede determinar que los precios de los productos tienen un sendero aleatorio común. Estos test, el de correlación y el de cointegración, sirven para aportar información o reforzar la construcción realizada con el análisis cualitativo. Buscan sumar evidencia respecto a si dos o más productos pertenecen o no a un determinado mercado. Por tanto, deben leerse en su conjunto y en forma coherente.

El análisis reseñado puede utilizarse para determinar mercados tanto en el análisis de conductas de los agentes, donde está implícita que alguna de las empresas tiene posición dominante, como en el análisis de fusiones, donde el principal peligro es que, como resultado, las empresas fusionadas puedan aumentar los precios. En el caso de fusiones, también se utiliza el test SSNIP (_Small but Significative Non-Transitory Increase in Price_, por sus siglas en inglés) o test del monopolista hipotético, uno de los más usados en defensa de la competencia.
^[Este surge con los [lineamientos de fusiones](https://www.justice.gov/archives/atr/1982-merger-guidelines) del Departamento de Justicia y la Federal Trade Commission de EUA, en 1982]
En primer término, se presentará el test y luego se discutirán las limitaciones que el mismo presenta para su utilización en casos que no involucren fusiones. 

El test es bastante sencillo. Se basa en la siguiente pregunta: ¿puede una empresa, hipotética monopolista, subir los precios de sus productos de forma permanente y de modo sustancial (por ejemplo 5-10% real)? Si la respuesta es afirmativa, entonces el mercado relevante está definido por esa empresa. Si la respuesta es negativa, entonces existe alguna otra empresa o producto que impide este incremento y, en consecuencia, se los debe incorporar al análisis para determinar el mercado.

Este es un proceso iterativo en el que se siguen incorporando bienes hasta que la respuesta sea afirmativa. Este proceso no está exento de problemas ya que muchas veces el orden en el que se incorporan productos cambia el resultado y, con ello, el mercado relevante. El objetivo del test SSNIP es establecer el menor grupo de productos y área geográfica en el cual un hipotético monopolista que lo controle, pueda mantener precios superiores a los competitivos.

La literatura es unánime respecto a que el test SSNIP es el correcto para determinar mercados. Sin embargo, es muy intensivo en información, ya que se requiere información de precios de muchos mercados para poder construir un modelo que pueda determinar este efecto. En muchos casos se utiliza una pregunta a los informantes calificados, “¿puede la empresa X subir sus precios un 5-10% en forma no transitoria si ocurre tal conducta?” Es un test que sirve fundamentalmente para fusiones, y su uso en casos de abuso de posición dominante no permite obtener resultados confiables por dos razones. 

En primer lugar, muchas veces las empresas realizan acciones no para aumentar su poder de mercado sino para mantenerlo. Por ejemplo, si una empresa dominante impide que otra entre al mercado, el statu quo se mantendrá y, por lo tanto, el precio del producto no se altera. El problema en este caso, es que con una mayor competencia el precio bajaría, lo que no ocurre porque el potencial entrante no ingresa al mercado. En segundo lugar, y vinculado a lo anterior, cuando las empresas tienen posición dominante no tienen incentivos a seguir subiendo el precio, dado que ya lo han establecido en el mayor valor posible. Por tanto, preguntarse si el precio seguiría subiendo no tiene sentido porque ya llegó al límite. 

Además, hay otro elemento interesante que proviene del análisis de la demanda que ayuda a entender este fenómeno. Cuando el precio de un producto es bajo, en general, los sustitutos son pocos. Sin embargo, cuando el precio comienza a aumentar, también surgen productos sustitutos que antes no existían. Por ejemplo, cuando un mensaje de texto por celular cuesta U\$S 0,2, los sustitutos de este mensaje serán pocos, quizá un correo electrónico o una llamada breve. Pero si mandar un mensaje de texto costara U\$S 1.500, se podría viajar casi a cualquier parte del mundo y entregar el mensaje personalmente. 

Por tanto, la primer defensa de cualquier empresa con posición dominante es aducir que existen múltiples sustitutos a sus productos, aunque esto sea consecuencia de tener tal posición. 

A los efectos del test SSNIP este problema implica que, si no se está alerta, se incorporarán productos al
mercado cuando ello no corresponde, porque la empresa ya tiene posición dominante y, por tanto, siempre pasa el test, ya que nunca querrá aumentar los precios más de lo que ya lo ha hecho. Esta situación se conoce como “Falacia
del Celofán”,
^[El caso es [United States vs. E.L du Pont de Nemours & Co.](https://supreme.justia.com/cases/federal/us/351/377/), resuelto por la Corte Suprema de EUA en 1956.]
debido a un caso de defensa de la competencia en EUA donde se cometió el error de agrandar el mercado relevante a una empresa con posición dominante en el mercado del celofán, en el entendido de que existían múltiples sustitutos para sus productos.

Tan importante es el test SSNIP que en EUA algunos autores abogan por abandonar directamente la definición del mercado relevante. Kaplow (2010) pone sobre el tapete algunas de las limitaciones que tiene utilizar este test para definir mercados relevantes. Sin embargo, Werden (2012) señala que el mercado relevante es una herramienta que permite consolidar una narrativa consistente, así como distinguir los elementos centrales de los secundarios.

Después de esta discusión, quizá el lector esté desorientado respecto a cómo proceder para determinar un mercado relevante. Por ello, a continuación se presentan algunas pistas:

* En primer lugar, hay que mantener la perspectiva en el producto que adquiere el consumidor. Muchas veces los problemas de competencia acontecen en algún lugar de la cadena de valor, por ejemplo a nivel minorista. Pero el producto no cambia por ello. Es decir, no se puede confundir el mercado donde ocurre la conducta, con la conducta en sí misma.

* En segundo lugar, y aunque parezca contradictorio, la conducta aporta elementos hacia donde enfocar el problema. Por ejemplo, si el problema está en la distribución hay que analizar cómo afecta ese problema puntual el acceso del consumidor al producto. No tiene sentido hacer el análisis en el eslabón de la producción, dado que allí no está actuando la restricción competitiva. O si la restricción se observa en un determinado mercado geográfico, no tiene sentido estudiar lo que pasa en los mercados de otras regiones, salvo que sean sustitutos geográficos y, por tanto, integran el mismo mercado geográfico relevante.

* En tercer lugar, si bien el objetivo es encontrar el mínimo mercado donde ocurre una determinada conducta, muchas veces el mercado puede agrandarse si las condiciones competitivas son similares. Por ejemplo, en un caso de distribución de helados en Alemania se presentaban restricciones al acceso de unos productores a las heladeras de las tiendas. Las tiendas eran relativamente pequeñas, por lo que el mercado geográfico relevante debería alcanzar a un pequeño círculo con centro en la tienda, quizá no mayor a medio kilómetro. Sin embargo, como la conducta se manifestaba igual en todo el territorio y este tipo de tienda era la regla en todo el país, el mercado se definió como todo el país. Ello no cambiaba la dominancia relativa de la empresa y hace más sencillo el análisis.


### Evaluación del poder de mercado

Una vez definido el mercado relevante —de producto y geográfico— hay que determinar la posición de mercado de las empresas que en él operan. Recuérdese que la definición del mercado relevante es un instrumento para deducir la capacidad que tienen las empresas de fijar precios en el mercado. En esta etapa hay que describir el mercado y contextualizar la competencia. Para ello, en primer lugar, se debe medir la concentración en el mercado relevante, para lo que se utilizan dos indicadores: (i) el Indicador de Concentración y (ii) el Indicador de Herfindahl-Hirschman (HHI).

**El Indicador de Concentración**, calcula cuanto representa en el total del mercado la participación de las empresas más importantes. Un típico indicador de concentración es el $C_4$ que mide la cuota de mercado de las cuatro empresas más grandes de ese mercado. Sin embargo, este indicador no dice mucho si hay pocas empresas, lo que ocurre a menudo en economías pequeñas.

El indicador HHI es la suma del cuadrado de las cuotas de mercado de cada empresa: $HHI = \sum s_i^2$, donde $\sum$ indica la suma de todas las cuotas, y $s_i^2$ es la cuota de mercado de la empresa i al cuadrado. El HHI varía entre 0, cuando la competencia es perfecta y hay infinidad de empresas en el mercado, y 10.000 cuando hay una única empresa —monopolio— con el 100% del mismo. Este indicador tiene algunas propiedades deseables: (i) penaliza la concentración, en la medida que si una empresa tiene una cuota muy importante, entonces el indicador —al estar elevado al cuadrado— presentará valores mayores; (ii) permite comparar entre mercado, si en un mercado el HHI es 3.000 y en otro es 5.000, podemos decir que el segundo mercado está más concentrado que el primero.

Tanto el índice de concentración como el HHI se pueden construir para distintas variables, que pueden arrojar distinta información relevante. Tres variables son las utilizadas para comparar la concentración del mercado: (i) la capacidad de producción, (ii) el valor de la producción, o (iii) la cantidad producida. Analizar la capacidad de producción permite conocer si hay empresas que tienen capacidad ociosa que pueden usar para satisfacer la demanda. 

Si el HHI de la capacidad de producción es mayor al HHI del valor de la producción, entonces las empresas más importantes del mercado tienen capacidad ociosa, o sea tienen una mayor capacidad de la que utilizan para producir. Esto puede ser un indicador de capacidad de crecimiento de estas empresas en el mercado, pero también puede implicar la capacidad de represalia de estas empresas o la posibilidad de inundar al mercado y, en consecuencia, reducir los precios en forma importante. 

Por otra parte, si se compara el HHI en valores respecto al de cantidades, se tiene una fotografía de cómo juegan los precios. Si el indicador en valor es mayor al de cantidades, las empresas más grandes están cobrando mayores precios por sus productos, lo que es otro indicador de poder de mercado. El indicador de cantidades producidas debe construirse para productos homogéneos, por ejemplo si se calcula el volumen de agua vendido en el mercado o las toneladas de papel. Si los productos no son homogéneos, entonces las cantidades no se podrán agregar, a menos que se utilice el precio y se calculen los valores.

Una vez determinado el mercado relevante y la concentración del mismo, hay que evaluar las posibles barreras a la entrada. Dos mercados idénticos, con igual concentración, pueden determinar niveles de competencia diferentes si
las barreras a la entrada difieren. Las barreras a la entrada son uno de los conceptos más complejos de definir en economía, ya que existen diferentes definiciones [@McAfee2004]. La definición más aceptada es la que establece que una barrera a la entrada es un costo que tiene que pagar la empresa que entra al mercado, pero que no paga la que ya está instalada. 

Sin embargo, existen múltiples costos a incurrir para entrar en el mercado, ¿cuáles son los relevantes? Los costos hundidos son los más importantes a la hora de entrar a un mercado. Estos costos son aquellos que, una vez incurridos, no pueden ser recuperados. Ejemplos de estos costos son la capacitación del personal, la publicidad o la instalación de activos específicos —maquinaria— para realizar una determinada actividad. 

Cuanto más específicos sean los activos, menos líquidos serán en caso de que el emprendimiento fracase, lo que incrementa los riesgos de entrar al mercado. Por ejemplo, en el mercado de las bebidas gaseosas, el ingreso es relativamente fácil para una empresa que ya produce agua embotellada. Sin embargo, para competir en ese mercado se requiere construir una marca, que a su vez requiere cuantiosas inversiones en publicidad. Por tanto, ingresar a ese mercado puede ser sencillo, pero no va a permitir constituir una alternativa importante a las empresas dominantes del mercado. 

Cuanto mayores sean las barreras a la entrada, más difícil será que nuevas empresas limiten el poder de mercado de la o las empresas instaladas. Por tanto, las barreras a la entrada pueden ser un síntoma del poder de mercado.
Cuando se analizan las barreras a la entrada no hay que perder de vista que sólo se deben considerar aquellos que pagan los entrantes, pero no los instalados, quienes, muchas veces, ya los pagaron. 

Este es el tema central en este análisis. En el ejemplo anterior de las bebidas gaseosas, las empresas que ya construyeron una marca pagaron los costos que ello implica. Cuando una empresa instalada invierte en un sistema de distribución específico para sus productos también está invirtiendo en un activo específico. Cuando una empresa instalada realiza cursos de capacitación a su personal también está incurriendo en costos específicos. Muchas veces, estas inversiones permiten mejorar la calidad o precio de los productos, pero otras veces buscan dificultar el acceso al mercado de potenciales rivales, que deben ponerse a la altura de las instaladas para poder competir. 

Atacar estos comportamientos no sólo es complejo, sino que puede ser contraproducente. Tomemos el caso de la publicidad. Las empresas la realizan para generar demanda para sus productos. Los gobiernos tienden a regularla para que no se engañe a los consumidores. Pero determinar cuál es el volumen de publicidad adecuado es complejo. Un
gobierno podrá decir si debe haber o no publicidad, pero poner un límite respecto a cuánta realizar es impensable.


### Aplicación

El objetivo de la defensa de la competencia es impedir que las empresas ejerzan su poder de mercado. A veces, medir el poder de mercado es sencillo: si una empresa saca a otra del mercado y luego sube los precios, producto de una menor competencia, el poder de mercado se observa en forma sencilla. Sin embargo, muchas veces es difícil medir directamente el impacto de una determinada conducta sobre la capacidad de las empresas de fijar el precio. Si la evaluación directa no es posible, hay que recurrir a métodos indirectos.

El mercado relevante es un instrumento que permite inducir, a partir de evidencia sistemática, el poder de mercado de una empresa. Como todo instrumento indirecto es falible. Además, es difícil de contrastar con la realidad, dado que si la evidencia del poder de mercado fuera fácilmente obtenible, entonces la delimitación del mercado relevante sería innecesaria. Determinar el mercado relevante es un ejercicio que implica analizar en profundidad el mercado donde actúan las empresas investigadas y comprender su funcionamiento. 

Una vez delimitados los mercados de producto y geográfico, se analiza la concentración en el mercado y las barreras a la entrada. Con estos elementos se puede tener una composición de lugar de la importancia relativa de cada  empresa en el mercado.A continuación se presenta el detalle de la determinación de un mercado relevante en el mercado del pan lactal en Argentina.
^[Fusión entre Bimbo y Fargo analizada por la Comisión Nacional de Defensa de la Competencia. Dictamen 395 de 10 de setiembre de 2004. Disponible [aquí](http://cndc.produccion.gob.ar/sites/default/files/cndcfiles/395_0.pdf)]

Esta presentación no pretende fijar los estándares mínimos respecto a cómo debe delimitarse un mercado, ya que este proceso es bastante artesanal, ni implica estar de acuerdo con el procedimiento seguido en este caso o con sus conclusiones. Se presenta solamente a efectos ilustrativos, teniendo en cuenta que el dictamen presentado plantea la información que resulta coherente con una determinada decisión y que puede haber otra información relevante no incorporada que pudiera llevar a un dictamen opuesto.

Este caso surge a raíz de que dos empresas de pan lactal anuncian, en 2004, su fusión en Argentina: Bimbo y Fargo. Como en muchos otros países del mundo, cuando dos empresas importantes del mercado quieren fusionarse tienen que solicitar autorización a los organismos de defensa de la competencia. El mercado de pan en Argentina tiene dos segmentos: el mercado de pan artesanal, con un consumo de 70 kilos por persona al año, y el pan industrial, con un consumo de 3,8 kilos por persona al año. El pan industrial incluye el pan de molde y la bollería (pan para panchos —salchicha o hotdog— o hamburguesas). Mientras que el pan artesanal se vende directamente al público por las empresas que las producen —en general pequeñas—, el pan industrial se distribuye a través de minoristas. En esta categoría, el 49% de la distribución corresponde a hipermercados o supermercados, el 28% a almacenes y el 22% a autoservicios.

La pregunta clave es si el pan industrial y el artesanal forman parte del mismo mercado relevante de producto.
Si se analiza la demanda, existen diferencias en las características del producto que corresponde señalar: el pan industrial tiene conservantes; su duración es de 12 días, frente a los 4 días del pan artesanal; el pan industrial se vende envasado, el pan artesanal se vende al peso; el pan industrial se diferencia por marca; sólo un 2% de los consumidores compran pan artesanal en forma diaria, mientras que el 75% de los consumidores compra pan artesanal todos los días. Por otra parte, el pan artesanal se consume principalmente en las comidas (almuerzo y cena, 67%), mientras que el pan industrial se consume en las colaciones (desayuno y merienda, 62%). Por tanto, por sus características y la costumbre, ambos panes tienen distinto uso.

Otros elementos que indicarían diferencias entre estos productos son: (i) el precio del pan industrial es el doble del artesanal; (ii) la correlación de precios entre ambos productos es baja; (iii) el consumidor de pan industrial tiene un nivel socio económico mediano a alto; y (iv) la declaración de varias empresas de que el pan industrial no compite con el pan artesanal. La Comisión concluye que “dadas las significativas diferencias entre precios, características, durabilidad, presentación, momentos de consumo y percepción de los actores del mercado del pan industrial y artesanal, no se puede afirmar que son sustitutos por el lado de la demanda”. 

En principio, el pan artesanal y el pan industrial están en dos mercados de producto diferentes. Sin embargo, ¿puede el mercado ser más acotado? El pan industrial tiene tres componentes: el pan blanco (38%), el pan negro (33%) y la bollería (29%). El pan negro contiene ingredientes propios (salvado, harina integral, cereales y centeno) y se utiliza para hacer dieta. La bollería se utiliza para combinar con salchichas o hamburguesas. Asimismo, la correlación de precios entre los tres productos es no significativa (cero) o tiene
signo negativo. Por tanto, desde el punto de vista de la demanda habría tres mercados de producto diferentes: pan blanco, pan negro y bollería. 

Por el lado de la oferta, el expediente incluye una descripción detallada del proceso productivo que “comienza con la preparación de una esponja líquida que consiste en una mezcla de harina, levadura, agua, alimento para levadura, oxidantes y enzimas. Esta esponja luego es fermentada durante 2 horas y media o 3 y enfriada. Como paso posterior se le agrega harina fresca, emulsionantes, agua y conservantes en una mezcladora. Luego la masa es dividida y depositada en moldes que son sometidos a vapor para una nueva fermentación durante aproximadamente una hora. La masa ya fermentada en los moldes es horneada, desmoldada y enfriada para luego ser embolsada”. 

En cuanto al proceso de producción, Bimbo produce cada producto (pan blanco, negro y bollería) en distintas líneas de producción en una única planta. Las líneas de producción no comparten equipo entre ellas. Fargo, por su parte, tiene cinco plantas de producción: en una produce pan y bollería; en otra sólo pan y en una tercera sólo bollería; en otras dos plantas tiene líneas de producción dual (pan y bollería). 

Desde el punto de vista de la oferta, las diferencias entre los panes (negro y blanco) son únicamente los ingredientes; mientras que entre el pan y la bollería están el armado de los bollos, los moldes y el embolsado. Concluyen que, mientras desde el punto de vista de la demanda hay tres mercados de producto (pan blanco, pan negro y bollería), desde el punto de vista de la oferta hay sólo dos: pan industrial y bollería. Por tanto, hay dos mercados de producto.

La definición del mercado geográfico, dados los mercados de producto, es más sencilla. Las empresas operan en todo el país, aunque sus principales plantas de producción están en la Provincia de Buenos Aires. Por tanto, las empresas enfrentan los mismos costos de transporte para distribuir sus productos al resto del país. Asimismo, el 63% de las ventas se da en la capital y el gran Buenos Aires. Concluyen que, dadas las similitudes, el mercado geográfico es Argentina.


## Abuso de posición dominante

La primera conducta que se analiza, es el abuso de posición dominante. Esta terminología es la que se utiliza en la Unión Europea, mientras que en EUA se la conoce como monopolización. A pesar de la diferencia en los nombres, la jurisprudencia ha ido convergiendo [@Motta2004, sección 1.2]. Las prácticas de abuso de posición dominante se pueden dividir en dos.

Las prácticas **explotativas** son aquellas en las que una empresa cobra precios excesivos a los consumidores. Sin embargo, surgen múltiples problemas con este tipo de práctica. En primer lugar, existe un problema de medida: ¿excesivos respecto a qué? Las comparaciones nunca están exentas de problemas. En segundo lugar, si efectivamente se concluye que los precios son excesivos, este resultado puede ser motivo de la elección de los propios consumidores. Por ejemplo, Microsoft vende un sistema operativo (Windows) mientras que existen otros sistemas gratuitos (Linux). Sin embargo, la gente prefiere pagar por un producto que obtener el otro sin costo. Si bien existen muchas explicaciones para este resultado, hay una que resulta sencilla: Microsoft comercializa un producto de calidad que para muchos clientes es mejor que el producto de acceso gratuito. Por lo tanto, los precios elevados son simplemente el pago a la calidad del producto Microsoft. 

En tercer lugar, el precio es la señal de mercado que miran las empresas para entrar en ellos. Si nada más pasa, entonces precios altos son una señal para que otras empresas entren al mercado y disputen las rentas de la empresa instalada. Por ello, las prácticas explotativas tienden a no ser sancionadas, ya que afectan las señales de mercado y, lo más importante, transforman las agencias de competencia en agencias reguladoras, lo que no es su función. Las agencias de competencia establecen que conductas son lícitas o no, pero no fijan las variables del mercado.

Por su parte, las prácticas **exclusorias** buscan impedir la entrada o forzar la salida de rivales y, en última instancia, tienen un efecto positivo sobre el precio de las empresas. 

Las acciones de defensa de la competencia no están dirigidas hacia el precio de los bienes o servicios, sino contra las acciones que tienen un impacto sobre el mismo. Una pregunta clave en el análisis de esta conducta: ¿cuándo es dominante una empresa dominante? ¿Cuál es el umbral que debe pasar una empresa para que sus comportamientos se miren con lupa? Las legislaciones difieren en los umbrales, aunque existen ciertas reglas generales. 

En la Unión Europea, el caso United Brands estableció dominancia con cuotas de mercado de 40-45%; mientras que en el caso Akzo se estableció que una cuota de mercado mayor al 50% es indicador de dominancia, salvo prueba en  contrario.
^[AKZO Chemie BV vs. Commission, Caso C62/86 de 1993 ([Akzo](https://eur-lex.europa.eu/resource.html?uri=cellar:4905ac67-5a02-44a0-ae93-7724be6073b0.0008.02/DOC_1&format=PDF)) y United Brands Company and United Brands Continental BV vs. EC Commission, caso 27/76 de 1978 ([United Brands](https://eur-lex.europa.eu/legal-content/ES/TXT/PDF/?uri=CELEX:61976CJ0027&from=EN))]

Los Lineamientos de la Comisión Europea (Unión Europea, 2009) establecen que “Según la experiencia de la Comisión, no es probable que haya dominación si la cuota de mercado de la empresa en el mercado de referencia es inferior al 40%.” Por su parte, en EUA cuotas menores al 40% tampoco se consideran dominantes, pero mayores al 70% son evidencia de dominancia. Debe recordarse que además de las cuotas de mercado hay que considerar otros factores para establecer la dominancia, como por ejemplo las barreras a la entrada.

Las normativas de la Unión Europea y EUA difieren en la forma en la que tipifican la conducta. Mientras en la Unión Europea se persigue el abuso de la posición dominante, en EUA se prohíben los intentos de monopolización. El artículo 82 del Tratado de la Comunidad Europea establece que “será incompatible con el mercado común y quedará prohibida, en la medida en que pueda afectar a los Estados miembros, la explotación abusiva, por parte de una o más empresas, de una posición dominante en el mercado común o en una parte sustancial del mismo”. Es interesante notar que lo que la legislación no prohíbe tener una posición dominante, sino ejercer un abuso de tal posición. En Europa existe la idea de que las empresas dominantes tienen una especial responsabilidad en mantener las condiciones de competencia sin distorsiones. 

Sin embargo, estas categorías requieren de una definición, ya que son muy amplias. Sucesivas decisiones de la Comisión de la Comunidad Europea han dado forma a cada uno de los conceptos. La posición dominante es una posición de poder económico que ostenta una empresa y que le permite la facultad de obstaculizar una competencia efectiva en el mercado de referencia, proporcionándole la posibilidad de comportamientos, en medida apreciable, independientes respecto de sus competidores, sus clientes y, en definitiva, de los consumidores.
^[Establecido en las Decisiones sobre Europemballage Corporation and Continental Can Company Inc. vs. Commission of the European Communities, Caso 6-72 de 1973 ([Continental Can](https://eur-lex.europa.eu/legal-content/ES/TXT/PDF/?uri=CELEX:61972CJ0006&from=EN)) y Hoffman-La Roche & Co. AG vs. EC Commission, Caso 85/76 de 1979 ([Hoffman-La Roche](https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX:61976CJ0085:EN:PDF))]

Por su parte, la Comisión señala que la posición dominante es un concepto objetivo que refiere a las actividades de una empresa en situación de posición dominante que pueden influir en la estructura de un mercado en el que, debido justamente a la presencia de la empresa en cuestión, la intensidad de la competencia se encuentra ya debilitada, y que producen el efecto de obstaculizar, recurriendo a medios diferentes de los que rigen una competencia normal de productos o servicios basada en las prestaciones de los agentes económicos, el mantenimiento del grado de competencia que aún exista en el mercado o el desarrollo de dicha competencia.
^[Decisión sobre Hoffman La Roche antes mencionada.]

Por su parte, la legislación de EUA es el [Acta Sherman](https://www.law.cornell.edu/uscode/text/15/1) de 1890 que, en su sección 2, establece que “toda persona que monopolice o intente monopolizar, o se combine, o conspire con cualquier otra persona, o personas, para monopolizar cualquier parte del comercio o de la industria entre los diversos Estados, o con naciones extranjeras, será considerado culpable de falta grave (...)”. Sin embargo, la interpretación de la doctrina rápidamente estableció que dicha norma no puede interpretarse en forma literal ya que “el criterio que debe seguirse en cualquier caso para verificar si se ha producido una violación a la sección (2) es la regla de la razón (...)” 16 Es decir, la sanción aplica si se utilizan métodos ilícitos para monopolizar o intentar monopolizar un mercado.

Entre las posibles conductas de abuso de posición dominante, se presentan las tres principales: depredación, canastas y discriminación de precios.


### Depredación

De las prácticas anticompetitivas, la depredación de precios debe ser una de las más conocidas, aun cuando en la realidad se haya verificado pocas veces. Ocurre cuando una empresa dominante busca eliminar a la competencia fijando precios por debajo de su costo de producción, sacrificando beneficios en el corto plazo, de forma de obtener beneficios en el largo plazo. Debe aclararse que si una empresa es más eficiente y vende por debajo del costo de otra establecida —ineficiente—, esta es una práctica válida. Uno de los objetivos de la competencia es la eficiencia, lo que equivale a que los productores que sean ineficientes terminarán saliendo del mercado.

Esta práctica anticompetitiva tiene tres ingredientes fundamentales: (i) pérdidas que enfrenta la empresa que la realiza; (ii) poder de mercado para recuperar sus beneficios en el largo plazo; y (iii) barreras a la entrada que permitan consolidar la renta de la empresa depredadora. El énfasis en cada uno dependerá de las circunstancias, ya que la propia acción de depredación se transforma en una barrera, si los potenciales entrantes esperan una actitud hostil de la empresa instalada.

La depredación es una conducta específica, que se verifica en ciertas circunstancias. No es idéntico a vender por debajo del costo. Es relevante aclarar que la conducta de vender por debajo del costo refiere al costo que incurre la empresa en cuestión. Sin embargo, algunas veces, la venta por debajo de su propio costo puede ser una actividad legítima, como cuando se realizan ventas de final de temporada o para liquidar stock. También es una estrategia que utilizan muchas empresas que entran a los mercados como forma de atraer clientes. Toda empresa que quiera ingresar a un mercado se va a encontrar en desventaja frente a las instaladas, ya que estas tienen la clientela y una reputación en el mercado. Ingresar con precios por debajo del costo puede ser una estrategia interesante para estas empresas, de forma de atraer a los clientes que son sensibles al precio. Es una alternativa a la realización de campañas publicitarias.

El objetivo, cuando existe una denuncia por precios predatorios, es intentar desentrañar si es una conducta que puede afectar al mercado o beneficiarlo. Ello no es trivial, ya que la sanción implica que la empresa que lleva a cabo la conducta deba subir los precios, lo que parece un sinsentido para la política de competencia. Para llegar a este extremo, el riesgo de que la conducta permita que la empresa cobre precios monopólicos tiene que ser muy grande. Un reporte de la International Competition Network (ICN), señala que la metodología utilizada para analizar este tipo de conductas difiere entre los países en el énfasis que se pone en la recuperación de las pérdidas por parte de la empresa predatoria, y en la determinación del costo respecto del cual el precio es menor, entre otros. Asimismo, establece que —excluyendo a Corea del Sur que tiene un número inusual de casos— 33 países reportan 126 denuncias de precios predatorios, de los cuales sólo 24 fueron sancionados, es decir menos del 20% [@ICN2008]. Ello refleja, por un lado, la dificultad de aplicar este tipo de procedimiento y, por otro, el problema que genera a las agencias de competencia tener que impedir que las empresas rebajen sus precios.

Desde el punto de vista teórico, esta conducta fue muy resistida. Varios artículos trataron el tema en la década de los 50, y @Selten1978 presentó la paradoja de la irracionalidad de la predación en un modelo con información completa.
^[Este trabajo le valió el Premio Nobel en Economía en 1994.]
Posteriormente, en la década de los 80, surgieron distintos modelos que incorporaron información asimétrica al análisis y demostraron que la depredación puede ser una conducta racional.

Si bien no existen metodologías aceptadas en todas las legislaciones, una de las referencias en el análisis de la predación es la desarrollada por @Joskow1979. La misma se basa en realizar un test en dos etapas: en la primera, se analiza el mercado para determinar si en él se podría verificar la predación; si se pasa esta etapa, se analizan los costos. 

La primera etapa implica una evaluación de las características del mercado de forma de deducir si es racional una conducta predatoria. Por ejemplo, se analiza las barreras a la entrada, el número de empresas en el mercado, la diferenciación de productos, etc. También se analiza si la empresa que realiza la conducta tiene posición dominante. Si el mercado es disputable fácilmente por empresas entrantes, o si la empresa que realiza la conducta no es dominante, entonces el caso se cierra sin pasar a la siguiente etapa. Si por el contrario, existe riesgo de monopolización por parte de la empresa que realiza la conducta, se pasa a analizar los costos de la misma. 

Aquí surge un nuevo problema, en la medida en que no es claro por debajo de qué costo debe estar el precio. Los autores establecen la siguiente regla: (i) si el precio es mayor al costo medio total (costo total dividido la cantidad producida), entonces nunca puede ser predatorio; (ii) si el precio está entre el costo variable medio (costo total excluidos los costos fijos, sobre el total de la producción) y el costo medio total, entonces puede ser predatorio sólo en circunstancias excepcionales; y (iii) si el precio es menor al costo variable medio, entonces es predatorio, salvo justificación económica en contrario.

La Unión Europea establece, por su parte, que el elemento sustancial a probar en este tipo de conducta es el sacrificio, es decir la pérdida que incurre la empresa que realiza la conducta. En particular “La Comisión considerará que la conducta entraña un sacrificio si la empresa dominante, al aplicar un precio más bajo a toda o a una determinada parte de su producción, durante el período de referencia, o al aumentar su producción durante el período de referencia, incurrió o está incurriendo en pérdidas que podrían haberse evitado” (@UE2009, p. C 45/16). 

El sacrificio o la pérdida se calcula utilizando el Costo Medio Evitable, que es “la media de los costos que se podrían haber evitado si la empresa hubiera fabricado una modesta cantidad de producción (adicional), en este caso, a la cantidad presuntamente objeto de la conducta abusiva” (@UE2009, nota al pie 2, p. C 45/11). En particular, si el precio es menor al Costo Medio Evitable, entonces hay evidencia de sacrificio. Otro elemento que aporta es que no es necesario demostrar que como consecuencia de la conducta predatoria, los competidores salen del mercado.


### Canastas

Las canastas son una práctica comercial más común de lo que parece. Al igual que en el caso anterior, y en todos los casos de abuso de posición dominante, tiene efectos positivos y negativos sobre el mercado. Existen diversos tipos de canastas: (i) puras, cuando dos productos se venden en proporciones fijas; (ii) línea completa forzosa, cuando los productos se venden en proporciones variables; y (iii) mixta, cuando los productos se pueden vender tanto juntos como separados. 

Un automóvil es una canasta pura, ya que es un bien que es una canasta de sus componentes en una proporción que no admite alterar las proporciones. Otra canasta pura es la computadora que incluye el sistema operativo. Una tercera es el producto que ofrece las empresas de televisión por cable, en donde el conjunto de señales básicas no pueden ser elegidas por el consumidor. La línea completa forzosa se da cuando se compra un teléfono celular y este viene con minutos de alguna compañía. Por otra parte, la canasta mixta es utilizada en las ventas de temporadas de espectáculos o en los abonos deportivos, donde el cliente puede comprar tanto la temporada entera del mismo, o alguna función particular.

Las canastas se pueden utilizar como un mecanismo de discriminación de consumidores. Por ejemplo, a los consumidores que son fanáticos del ballet se les puede vender toda la temporada con un pequeño descuento, mientras que aquellos que quieren ver alguna función en particular tienen que pagar un sobre precio por esa función. Las empresas de televisión por cable agrupan distintas señales de forma de llegar a diferentes públicos, a los cuáles les cobran proporcionalmente más por el conjunto de señales de lo que estarían dispuestos a pagar si se vendieran por separado. 

Otra forma es atar el producto al mercado posventa (_aftermarket_) como en el caso de las impresoras y los cartuchos. En este caso, supongamos que hay dos tipos de consumidores, los que usan mucho la impresora y los que la usan poco. Si el productor no puede identificar cuál es cuál, como ocurre generalmente, entonces puede atar la impresora —a menor precio— a los cartuchos —a mayor precio— de forma de que los consumidores que usen poco la impresora elijan esta canasta.

Asímismo, la estrategia de atar productos puede ser utilizada por una empresa para excluir rivales del mercado. Por ejemplo, supongamos una empresa que tiene el monopolio de un producto en el mercado A, mientras que enfrenta competencia en el mercado B. Los productos de los mercados A y B son complementarios, por lo que se necesitan ambos para que funcionen. La empresa que tiene el monopolio en A puede atar los productos A y B como forma de extender su posición dominante del mercado A al B.

La Unión Europea considera que este tipo de conductas puede tener efectos anticompetitivos, si se aplican con el objetivo de cerrar el mercado a competidores. En particular, considera si la empresa es dominante en el mercado vinculante, y se cumple además que: (i) los productos vinculantes y vinculado son distintos y, (ii) es probable que la vinculación dé lugar a un cierre anticompetitivo del mercado [@UE2009, p. C 45/15]. Establece que “dos productos son distintos sí, no existiendo una vinculación o venta por paquetes, un número sustancial de clientes compraría o habría comprado el producto vinculante sin comprar también al mismo proveedor el producto vinculado, lo que haría posible producir de forma independiente tanto el producto vinculante como el vinculado” (ibid). Es decir, son productos distintos si se puede utilizar uno sin necesidad de comprar el otro. El riesgo de cierre anticompetitivo de mercado está vinculado a la duración de la conducta o a la posibilidad de que el mercado vinculado esté regulado.

Una variación relevante es cuando las empresas ofrecen descuentos multi-producto para canastas. En estos casos, las empresas pueden utilizar alguna ventaja en su cartera de productos para limitar la expansión de sus rivales, si estos no pueden imitar los descuentos, aun siendo igual de eficientes, porque no cuentan con los mismos bienes en la cartera. Sobre este tema se volverá cuando se analice las restricciones verticales, ya que las canastas pueden ofrecerse tanto a consumidores finales como a empresas intermediarias.


### Discriminación de precios

Toda vez que un productor cobra precios diferentes por productos que tienen el mismo costo, se dice que hay discriminación de precios. Una definición alternativa establece que existe discriminación cuando el cociente entre el precio y el costo de los productos difiere. Este es un instrumento utilizado para incrementar los beneficios de las empresas, cobrando precios mayores a los consumidores que tienen mayor disposición a pagar por el producto. La clave es impedir que los consumidores puedan arbitrar entre sí el precio diferencial que establece el productor. En principio, este tipo de prácticas se puede asociar tanto a las explotativas como a las exclusorias.

La discriminación perfecta se conoce como de primer grado, e implica que el productor puede cobrar a cada consumidor el máximo que está dispuesto a pagar por el producto. Es un escenario ideal para el productor, ya que implica que conoce perfectamente al consumidor. En la realidad, el consumidor tiene incentivos a ocultar su disposición a pagar, por lo que el productor necesita recurrir a mecanismos alternativos. Sin embargo, permite extraer algunas conclusiones generales sobre el fenómeno. 

La primera es que el productor está, en general, mejor bajo discriminación que sin ella, ya que obtiene beneficios mayores. La discriminación implica que el productor, en vez de cobrar un único precio por sus productos, cobra distintos precios que pueden ser mayores o menores al precio único. Por tanto, la discriminación genera un efecto ambi- guo sobre los consumidores. Mientras algunos pagan más por el producto que ya compraban, otros acceden al mismo porque pagan menos y antes no podían comprarlo. Por este motivo, impedir la discriminación puede resultar en que un número menor de consumidores accedan al producto y empeorar el bienestar, en vez de mejorarlo.

Si no es posible conocer con exactitud las preferencias de cada uno de los consumidores, falla la discriminación de primer grado y el productor puede utilizar dos mecanismos alternativos para obtener mayores beneficios. El primero es la discriminación por autoselección, donde la empresa ofrece al consumidor un menú de alternativas de forma de que, si están bien diseñadas, este revele su disposición a pagar. Son múltiples las expresiones de este tipo de discriminación. 

Están, por un lado, las tarifas no lineales, como los descuentos por cantidad, en las cuales los consumidores pagan precios diferentes según la cantidad del bien que compren. Ello puede expresarse a través de precios diferentes según distintas unidades (un precio para la primer unidad y otro si se compran a partir de tres, la segunda unidad a mitad de precio, etc.) o a través del envase en el que se presenta (las bebidas gaseosas tienen precios diferentes según si el envase es de 600 cc, litro, litro y medio, etc.). Los cines ofrecen precios diferenciados según el día y la hora de la función. Algunos libros aparecen en edición de tapa dura y blanda con precios distintos. Hay productos que se venden dañados como forma de discriminar, como por ejemplo el sistema Windows en distintas versiones (licencia para una unidad no transferible, licencia para una unidad transferible, etc.) o con limitaciones (las antiguas netbook contenían una versión de Windows que no permitía cambiar el fondo de escritorio, si se quería cambiar había que comprar una nueva versión del sistema). El Ipad tiene distintos precios según la cantidad de memoria que tenga incorporada, donde la diferencia en el precio es muy superior al costo de instalar tal memoria. En todos los casos, el productor ofrece distintas opciones sabiendo que los consumidores valoran diferente el producto, y cuando este elije le está revelando su disposición a pagar.

El segundo es la discriminación por indicadores donde la empresa puede segmentar a los consumidores según alguna característica observable. Hay poblaciones que tienen características similares, como los estudiantes o los jubilados y, por tanto, se puede ofrecer descuentos a este tipo de grupos para incentivar su demanda. La característica de estos grupos es que su demanda es más elástica, es decir, responde en forma más intensa a cambios en el precio. Sin embargo, para impedir el arbitraje, el productor tiene que incorporar restricciones, como requerir documentos que prueben la situación del consumidor o vender servicios con nombre para que sólo estos puedan utilizarlo.

La discriminación también puede ser utilizada para excluir a otros productores del mercado, tal el caso cuando operan acuerdos exclusivos, que también se observan en el contexto de las relaciones verticales entre empresas. La compra exclusiva obliga a un cliente a comprar únicamente a una empresa, en general dominante. Otra forma de discriminación es otorgar descuentos condicionales, donde se recompensa a los clientes por una determinada conducta de compra. Este premio se puede establecer en forma retroactiva, es decir sobre todas las compras del consumidor actuales y previas; si las compras del consumidor pasan determinados umbrales; o sobre las compras incrementales. En ambos casos, la empresa discrimina a determinados consumidores con el objetivo de excluir a competidores del mercado.

Una conducta discriminatoria relacionada es la negativa al suministro. En este caso, la discriminación es total, en la medida en que una empresa se niega a tratar con otra. Este problema surge, fundamentalmente, cuando las empresas están vinculadas entre mercados verticales. Esta práctica incluye la denegación de suministro a clientes; la negativa a conceder licencias de derecho de propiedad intelectual; o la negativa al acceso a una red o a una facilidad esencial. Estas conductas discriminatorias aumentan el poder de mercado de la empresa que la realiza, a través del desplazamiento de los posibles competidores y, por tanto, pueden ser anticompetitivas.

Un último comentario refiere al análisis de las facilidades esenciales, que representan activos indispensables para competir en un mercado, como un puerto, aeropuerto o las líneas de transmisión de electricidad. Si la empresa transporta pasajeros o se dedica a la pesca, necesita acceso al puerto para amarrar sus barcos; si transporta pasajeros en aviones, tiene que tener acceso a un aeropuerto para que el avión aterrice; si genera energía eléctrica, tiene que tener acceso a la línea de transmisión eléctrica para llegar a los consumidores.

Impedir el acceso a estas plataformas puede resultar en la exclusión de competidores del mercado. Sin embargo, entregar el acceso en forma irrestricta genera incentivos al parasitismo
^[Traducción del término free rider en inglés.]
de las inversiones, es decir esperar a que otro la haga y pague el costo para poder utilizarla. Por ello, la jurisprudencia de EUA señala que las facilidades esenciales deben cumplir con cuatro requisitos:
^[Véase caso [MCI Communications Corp. vs. American Tel. & Tel. Co.](https://law.justia.com/cases/federal/appellate-courts/F2/708/1081/330445/), 708 F.2d 1081, 1132-33 (7th Cir. 1982), 464 U.S. 891 (1983).]
(i) el control de la misma debe estar en manos de un monopolista; (ii) el competidor debe ser incapaz de duplicarla en forma razonable; (iii) se debe verificar la negativa al uso de la instalación al competidor por parte del monopolista; y (iv) debe ser factible para el monopolista dar acceso a la instalación al competidor. Si estos cuatro elementos se cumplen, entonces se puede obligar a dar acceso a competidores a esta facilidad esencial. El problema en estos casos es establecer la tarifa de acceso a la misma, ya que no existe un mercado para el servicio y el monopolista tiene incentivos a excluir al competidor cobrando un precio excesivo.


## Colusión

El abuso de posición dominante es una conducta que lleva a cabo una única empresa. Sin embargo, a veces son varias las empresas que realizan acciones anticompetitivas. En esta sección se analiza una de estas acciones colectivas que ocurre cuando empresas que deberían competir entre sí, no lo hacen. @Cabral2017 señala que la colusión son acuerdos entre empresas con el objetivo de aumentar su poder de mercado. Por su parte, @Motta2004 las define como prácticas que permiten a las empresas ejercer un poder de mercado que de otra forma no tendrían, restringiendo la competencia y el bienestar. De todas las interacciones que pueden tener empresas competidoras —por ejemplo, cooperando en investigación y desarrollo—, el énfasis estará en aquellas relaciones que explícitamente buscan reducir la competencia. 

Hasta la década de los 70 la economía no había encontrado una teoría que pudiera explicar por qué las empresas querrían formar un cartel. Los principales modelos que explican la colusión suponen que las empresas que participan del mercado fijan el precio —o la cantidad— con independencia unas de otras. En estos modelos no hay un acuerdo tácito, sino que este es implícito. Sin embargo, en la realidad, las empresas se comunican entre sí para lograr coordinar acciones. 

Estos modelos económicos explican por qué —y bajo qué condiciones— se alcanza la colusión, para lo que requieren de un entorno dinámico, en el cuál las empresas interactúan a lo largo del tiempo. En cada momento, tienen que decidir si participan del cartel o traicionan a sus compañeros. La situación más extrema del mercado, el monopolio, se presenta cuando hay una única empresa que controla toda la demanda y no enfrenta competencia y, por lo tanto, tiene la posibilidad de generar escasez de forma de aumentar el precio de sus productos y obtener beneficios extraordinarios. Cuando en el mercado hay más de una empresa, la competencia entre ellas las incentivará a aumentar la producción respecto a la situación de monopolio. 

La colusión implica que las empresas que participan del cartel se comportarán como un monopolista, es decir producirán menos de lo que querrían, de forma de aumentar sus beneficios. Ello se logra si y sólo sí todas las empresas cumplen el acuerdo, de forma de que el precio suba debido a la escasez. Ahora bien, ¿por qué la traición sería una acción posible? El aumento de precio que resulta si opera el cartel, es la tentación de cada participante para traicionar a sus compañeros y, dado que todos los demás están produciendo menos, expandir unilateralmente la producción y ganar beneficios.
^[Una alternativa es que las empresas acuerden fijar un precio de monopolio, en vez de fijar la cantidad. Pero la tentación se presenta de nuevo, bajo la forma de arbitrar el precio de los rivales. Mientras ellas están fijando un precio alto, un participante del cartel puede rebajar el precio de los demás y expandir en forma importante sus ventas.]

Si la decisión fuera por única vez, entonces no se podría sostener la colusión: todos querrían decir que participan del cartel y, mientras esperan que los demás reduzcan la producción, traicionarlos aumentándola.  Lo que sucede siempre que hay traiciones es la represalia. En estos modelos, la represalia se presenta como la pérdida de beneficios que enfrentan las empresas, producto de una intensificación de la competencia una vez que descubren que han sido traicionadas.

Cuando se introduce el tiempo en este análisis se impone un costo sobre los beneficios futuros de las empresas, ya que estas no valoran igual los beneficios actuales que los futuros. En general, un mismo valor hoy y dentro de un
año pesan distinto en las decisiones de los agentes, que tienden a valorar más el presente. Cuanto más pacientes sean los agentes, más valorarán el futuro y más fácil será sostener acuerdo colusorios. Por su parte, cuanto más impacientes sean, mayor será la tentación inmediata de obtener beneficios ahora aunque cueste perder beneficios después. En otros términos, la colusión surge porque los agentes son lo suficientemente pacientes para vencer la tentación del momento en pos de una renta futura relevante. 

Estos modelos presentan además una aparente paradoja: cuanto más fuerte sea el castigo, más fácil será sostener la colusión y, por tanto, menor será la necesidad de su aplicación. Esta idea ha permitido representar múltiples situaciones para predecir en qué circunstancias la colusión es más factible. @Ivaldi2003 presentan un conjunto de situaciones que facilitan la colusión, las que se resumen en el cuadro \@ref(tab:cuadro4).

\

```{r cuadro4, echo=FALSE}
base <- read.csv("bases/cuadro4.csv")
knitr::kable(base, caption = 'Variables que facilitan la colusión.')
```

Fuente: elaborado sobre la base de Ivaldi et al. (2003).


Cuando existe información asimétrica entre las empresas respecto a alguna variable relevante de mercado, mantener los precios rígidos puede ser la única forma de sostener los acuerdos colusivos. @Rotemberg1990 encuentran este resultado en un modelo que explica, además, el surgimiento de una empresa líder que fija el precio en el mercado. @Athey2004, por su parte, demuestran en términos más generales que la rigidez de precio es un mecanismo muy efectivo para sostener acuerdos de precio entre empresas competidoras.

Si no existiera prueba concreta de acuerdo entre empresas, ¿qué evidencia podría sugerir que existe colusión? Harrington (capítulo 6 de @Buccirossi2008) propone algunos patrones de conducta que son indicadores de acuerdos colusivos. Bajo ciertas condiciones, la dispersión de los precios de las empresas —varianza— es menor, y existe una relativa estabilidad de las cuotas de mercado bajo un acuerdo colusivo que bajo competencia. En el caso de licitaciones o llamados de precio, si hay colusión de los oferentes se observa que los precios de las empresas en las pujas deberían estar positivamente correlacionados entre sí a lo largo del tiempo, mientras que las cuotas de mercado —ganar o perder una licitación— deberían estar negativamente correlacionadas.

La evidencia empírica respecto a la operación de los carteles muestra que las empresas tienen contacto entre sí, y que no sólo fijan el precio o la cantidad sino también otras variables [@Levenstein2006]. La fijación del precio va de la mano del reparto de clientes, la división de zonas geográficas, el reparto de licitaciones y otras medidas adicionales que permitan a los participantes controlar las acciones de los miembros y, eventualmente, implementar sanciones. También pueden incluir pagos laterales que realizan las empresas que incumplen algunos de los puntos del acuerdo, como forma de evitar represalias. Otras veces, utilizan a terceras empresas para sostener los acuerdos.

En Uruguay, en el caso de un cartel en el mercado del tomate procesado, las empresas tenían un acuerdo de cuotas que se materializaba utilizando una única imprenta para fabricar las cajas para el envasado. Esta imprenta, a su vez, entregaba las cajas a otro de los participantes en el acuerdo, para que este controlara la cuota fijada a cada empresa participante.

Los carteles, salvo el de la OPEP, son secretos por lo que son difíciles de detectar. Ello ha llevado a los gobiernos a buscar instrumentos que permitan desalentar su conformación y desestabilizar los ya formados. El principal instrumento que se utiliza son las políticas de clemencia, que reducen o exoneran las multas a las empresas o individuos que colaboran aportando información sobre los carteles en los que participan. Sin estas normas, no hay elementos jurídicos para evitar sancionar a las empresas que colaboran. Cuando en 1994 EUA introdujo
normas de clemencia, en los siguientes cinco años se detectaron y sancionaron el mismo número de carteles que en los 90 años anteriores. En la Unión Europea se introdujeron normas de clemencia en 2002 y los casos se multiplicaron por diez. 

@Miller2009 analiza en forma sistemática el efecto de estas políticas y concluye que desalientan la formación de carteles y aumentan las capacidades de detección por parte de las agencias de competencia. Algunos autores señalan que la clemencia no es suficiente y que se requiere recompensas para los delatores. En muchos casos, principalmente en la Unión Europea y en EUA, las personas que llevan adelante las delaciones luego tienen problemas para encontrar trabajo, por lo que se requiere recompensarlas para que la sanción social sea tolerable.

Las normas sobre carteles difieren en su contenido, la forma en la que se aplican y si contienen programas de clemencia. Si bien todas las normas de competencia tienen algún capítulo que prohíbe los carteles, las legislaciones difieren si esta prohibición es en sí misma (per se) o hay que demostrar el daño (regla de la razón). En general, existe un relativo consenso respecto a que los carte les llamados duros (hard core cartels) deberían estar prohibidos en sí mismos.

Estos carteles son acuerdos entre competidores para fijar precios, restringir la producción, repartir mercados o arreglar licitaciones. Una prohibición en sí misma sólo requiere probar que la conducta existe, ya sea por su objeto o sus efectos. Ello hace más fácil la aplicación de las normas y da mayor transparencia, ya que si la aplicación es bajo la regla de la razón hay que probar que la conducta está afectando el mercado, lo que puede ser complejo y costoso. En Uruguay, hasta el 2020, sólo se puede actuar sobre carteles que tengan una posición dominante en el mercado, lo que hacía complejo la aplicación de la norma. 

En EUA los carteles duros están prohibidos en sí mismo, lo mismo que en la Unión Europea. En EUA se aplica la sección 1 del Acta Sherman (1890) que establece que “se declara ilegal cualquier contrato, combinación bajo la forma de trust u cualquier otra, o conspiración, que restrinja el comercio entre los Estados o con otros países”.
^[En el original “Every contract, combination in the form of trust or otherwise, or conspiracy, in restraint of trade or commerce among the several States, or with foreign nations, is declared to be illegal”.]
Esta norma considera prohibidos en sí mismos a los carteles duros, o las llamadas restricciones a simple vista (_naked restrains_), mientras que se aplica la regla de la razón a las restricciones auxiliares (_auxiliary restrains_). En este país, como en muchos otros, la participación en carteles es un delito penal que implica pena de cárcel. 

En la Unión Europea se aplica el artículo 81 del Tratado de la Comunidad Europea que establece “1) Serán incompatibles con el mercado común y quedarán prohibidos todos los acuerdos entre empresas, las decisiones de asociaciones de empresas y las prácticas concertadas que puedan afectar al comercio entre los Estados miembros y que tengan por objeto o efecto impedir, restringir o falsear el juego de la competencia dentro del mercado común y, en particular, los que consistan en: a) fijar directa o indirectamente los precios de compra o de venta u otras condiciones de transacción; b) limitar o controlar la producción, el mercado, el desarrollo técnico o las inversiones; c) repartirse los mercados o las fuentes de abastecimiento; d) aplicar a terceros contratantes condiciones desiguales para prestaciones equivalentes, que ocasionen a éstos una desventaja competitiva; e) subordinar la celebración de contratos a la aceptación, por los otros contratantes, de prestaciones suplementarias que, por su naturaleza o según los usos mercantiles, no guarden relación alguna con el objeto de dichos contratos.2) Los acuerdos o decisiones prohibidos por el presente artículo serán nulos de pleno derecho.” 

En este caso, las restricciones son también prohibidas en sí mismas y no aplica ningún tipo de excepción según el tamaño de los participantes. Sin embargo, otro tipo de acuerdos como la investigación y desarrollo; la producción conjunta; los acuerdos de compra; o de normalización técnica, se estudian bajo la regla de la razón. Un segundo elemento tiene que ver con la forma en la que se aplica la normativa. En principio la persecución de carteles es un procedimiento bastante similar al de cualquier otro delito, en el que hay que obtener evidencia de su existencia, demostrar la participación de las empresas, entre otros. Por tanto, muchos países recogen la información a través de allanamientos policiales, tanto a empresas como a casas particulares. Existen técnicas bastante desarrolladas para diseñar e implementar este tipo de procedimientos, que es relativamente complejo, a los efectos de evitar filtraciones que permitan a los infractores destruir evidencia.

Cuando esta evidencia no está disponible, ¿cómo es posible identificar la colusión con la información de mercado? En estos casos el objetivo es demostrar que la conducta que se observa en un mercado sólo puede ser explicable si existe un acuerdo entre las empresas. Es decir, hay que descartar explicaciones alternativas. Ello suele ser complejo porque una misma conducta puede ser resultado de la competencia o de un cartel. Si se observa que las empresas cobran todas el mismo precio, ello puede ser el resultado de la competencia, si el bien es homogéneo, pero también de un cartel. Lo que diferencia a uno de otro es el nivel de precios en uno y otro caso, pero para poder discriminar los escenarios se requiere obtener información que permita evaluar el poder de mercado, es decir, los costos de las empresas. Ello, en general, está fuera del alcance de las agencias de competencia. 

Otra forma para identificar la colusión es ver la evolución de los precios a lo largo del tiempo, lo que se conoce como la doctrina del **paralelismo consciente**. Sin embargo, pueden existir múltiples razones competitivas que expliquen un comportamiento paralelo de las empresas. Por ello muchas veces se requiere de restricciones adicionales que descarten un comportamiento competitivo, como anunciar cambios de precio, o el mantenimiento de precios de reventa (ver sección \@ref(rest-vert), restricciones verticales), lo que se conoce como la doctrina del **paralelismo plus**.

Las conductas colusorias pueden ser tres. Por un lado están los acuerdos, definidos como todo pacto, verbal o escrito, mediante el cual varios operadores económicos se comprometen a una conducta que tiene como finalidad o efecto restringir la competencia. Por otro, las decisiones o recomendaciones colectivas, que son acuerdos adoptados en el seno de asociaciones empresariales o corporaciones, bien de carácter vinculantes (decisiones) u orientativo (recomendaciones), que tienden a uniformizar el comportamiento de los asociados y a limitar la competencia entre ellos. Por último, se encuentran las prácticas concertadas que es cualquier forma de cooperación informal entre empresas independientes que, sin haber llegado a concluir en un acuerdo propiamente dicho, conscientemente sustituyen la competencia por la cooperación práctica entre ellas.

Por otra parte, como vimos, algunos países tienen en sus legislaciones políticas de clemencia. Para que esta política sea efectiva debe dar garantías de que la empresa que aporte información quedará totalmente exonerada de multa, ya que de otra forma no tendrá incentivos a colaborar. Muchas veces, la clemencia se otorga cuando el caso ya se está investigando ya que la misma puede ser mucho más sencilla si alguno de los integrantes aporta las pruebas. En última instancia, las agencias de competencia no son recaudadoras, lo que buscan es que el mercado funcione y las empresas infractoras sean descubiertas y abandonen sus prácticas anticompetitivas. Otras legislaciones también otorgan inmunidad a empresas que aporten información sobre carteles que estén conformados en otros mercados. En cualquier caso, la clave del éxito de los programas de clemencia es que deben estar claramente diseñados, ser objetivos y evitar la incertidumbre y discrecionalidad.


## Restricciones verticales {#rest-vert}

Los consumidores acceden a los bienes y servicios luego de un extenso proceso productivo. Los insumos son convertidos en productos, los productos distribuidos a tiendas que luego los ofrecen a los consumidores. Muchas veces, con posterioridad a la venta, existe otra etapa de asesoramiento o servicio posventa, o reparación del producto. En estas distintas etapas puede actuar una misma empresa. Sin embargo, lo más común es que sean empresas distintas las que lleven a cabo cada una de las etapas del proceso productivo. Si bien el producto final es el mismo, suponer configuraciones distintas a lo largo de la cadena de valor lleva a resultados diferentes de precio y características de los productos.

Mientras que en la sección anterior se analizó la vinculación horizontal entre mpresas —aquellas en el mismo eslabón de la cadena de producción— en esta sección se analizan los casos donde esta vinculación es de tipo vertical. Es decir, las empresas no son competidoras entre sí, sino que operan en mercados diferentes con lógicas distintas. Por tanto, lo que es óptimo para una empresa en un eslabón de la cadena de valor, puede no serlo para otra empresa en un eslabón diferente. La relación más fuerte entre dos unidades productivas es la integración, que es cuando forman parte de la misma empresa. En este caso,los incentivos de ambas unidades están perfectamente alineados. 

Sin embargo, integrar procesos es costoso, tanto en términos de costos productivos —economías de variedad— como de costos de transacción. Como los incentivos en cada uno de los eslabones son distintos, la máxima libertad a cada unidad productiva puede perjudicar a una o ambas partes. Las restricciones verticales surgen como una respuesta alternativa a la integración —fusión— de dos unidades productivas, con el objetivo de alinear los incentivos entre sí. Por otra parte, la diferencia entre la realidad de mercado que enfrenta cada una de las empresas que acuerdan las restricciones verticales les permite, a algunas de ellas, usarla para balancear la competencia a su favor. Es decir, las empresas pueden usar las restricciones verticales no para resolver un problema de incentivos entre ellas, sino para afectar la competencia en alguno de los mercados. Esta interpretación polarizada de las restricciones verticales se explica más como un problema de balance ya que las restricciones verticales pueden resolver temas de eficiencia, a la vez que generar problemas de competencia.

Las relaciones verticales entre empresas son complejas. Involucran múltiples dimensiones diferentes —eficiencia, incentivos, externalidades— según si esta es hacia adelante (productor–distribuidores) o hacia atrás (proveedor–productor). Asimismo, los problemas también varían cuando el análisis es intra marca, es decir cuando se estudia las relaciones entre empresas que distribuyen una misma marca, o si se analiza la competencia inter marcas. En cualquier caso, restringir el análisis a las conductas anticompetitivas sin presentar los beneficios de las restricciones verticales puede ser peligroso, ya que nunca hay una interpretación en una única dirección. Por este motivo se presentan las dos visiones asociadas a las restricciones verticales: la eficiencia y las conductas anticompetitivas.


### Eficiencia {#eficiencia}

En las relaciones verticales entre empresas se encuentran tres tipos de problemas. En primer término, muchas veces la empresa necesita incorporar ciertos activos específicos para poder producir los productos que la otra parte requiere. Según la teoría de los costos de transacción, esto la expone a la expropiación, si no se instrumentan salvaguardas. En segundo lugar, cuando se analiza la cadena de valor aguas abajo —proveedores a minoristas— el poder de mercado en cada uno de los eslabones genera externalidades al productor que ve como su demanda disminuye, producto de los aumentos de precios de las demás etapas. Por último, las inversiones específicas también generan incentivos al parasitismo entre las partes con resultados no óptimos en los mercados. En esta sección se desarrollan cada uno de estos problemas.

El análisis de defensa de la competencia en EUA, hasta la década de los 70, suscribía una visión negativa de las restricciones verticales. Como reacción, surge la teoría de los costos de transacción, la más influyente con relación a la eficiencia de las restricciones verticales. La misma requiere de un mínimo desarrollo para comprender sus conclusiones (un desarrollo extenso se puede encontrar en @Williamson1998). Esta teoría se enfoca en las transacciones, en un entorno en el cual los agentes no pueden establecer contratos completos entre sí y, además, tienen comportamientos oportunistas. Esta conjunción —contratos incompletos y oportunismo— puede generar problemas _ex post_ entre los agentes. Por lo tanto, el diseño de instrumentos para resolver las controversias, cuando la relación está en marcha, es fundamental. 

@Williamson1998 define a los costos de transacción como los costos _ex ante_ de diseñar, negociar y resguardar los acuerdos contractuales y los _ex post_ asociados a los desajustes y a la adaptación que surge cuando la ejecución del contrato sufre desvíos producto de errores, omisiones o imprevistos. Es decir, esta teoría toma en cuenta que muchos costos para las empresas no están relacionados con el propio proceso productivo, sino con el entorno contractual en el que se mueven, con proveedores o minoritas.

En este marco, llevar a cabo una transacción dentro de una empresa o en el mercado tiene costos de transacción distintos. El mercado y la empresa, que @Williamson1998 llama formas organizacionales, tienen diferentes características. Mientras las empresas tienen una visión unitaria que facilita la adaptación cooperativa, el mercado resuelve la adaptación de forma autónoma.

Por otra parte, mientras los mercados generan fuertes incentivos a los participantes, ya que su supervivencia depende completamente de su esfuerzo, las empresas tienden a mitigar los incentivos a cada unidad en pos del bien común. Por último, los problemas que surgen dentro de una empresa se resuelven a través de las jerarquías, mientras que los problemas en el mercado se resuelven en la justicia. 

Por tanto, mientras los mercados generan mayores incentivos que las empresas a la búsqueda de beneficio, tienen menos flexibilidad para adaptarse y requieren de instituciones externas para resolver los conflictos. Por su parte, las empresas se adaptan en forma más rápida y flexible, pero establecen incentivos más débiles a cada unidad en la búsqueda de beneficios. Estas características implican que tanto los mercados como las empresas tengan
costos de transacción distintos. 

Partiendo de la base de que los contratos entre las empresas son incompletos y que los individuos que las integran tendrán comportamientos oportunistas, los riesgos de usar el mercado para las transacciones aumentan cuanto mayor sean los activos específicos para desarrollar la actividad. Un activo específico es aquel que no tiene usos alternativos y, por tanto, invertir en ellos expone a la parte que hace la inversión, al oportunismo de la otra. Si la relación entre las empresas alcanza un punto no previsto en el contrato, la empresa que tiene hundidos activos específicos está en peor posición para renegociar el acuerdo, ya que la otra parte tiene incentivos a utilizar esa ventaja a su favor y expropiarle parte de sus activos. 

Por lo tanto, actuar sobre las restricciones verticales aumenta los costos de transacción de utilizar el mercado e induce la integración. Por ello, hay que tener mucho cuidado con impedir restricciones entre empresas cuando hay activos específicos en juego.
^[Un análisis de la evidencia empírica sobre los límites de la integración vertical de las empresas, que también incluye una revisión sencilla de la literatura teórica, se puede encontrar en el trabajo de @Lafontaine2007.]
Gran parte de las restricciones que se analizarán están diseñadas como forma de proteger los activos específicos de alguna de las partes. 

Un segundo problema en las relaciones verticales entre empresas es el del doble margen, o monopolios sucesivos. Este surge cuando existe poder de mercado en las etapas sucesivas al proceso de producción, y el problema del monopolio se magnifica. Lo interesante es que las partes tienen los incentivos a resolver el problema sin necesidad de intervención externa. En particular, si un productor monopolista le vende a un distribuidor monopolista, el margen que agregará este último determina que el precio final al público esté muy por encima del precio que regiría si ambos estuvieran integrados. Debido a la forma de la demanda, el productor pierde más beneficios de los que gana el distribuidor como resultado del incremento en el precio, ya que al fijar precio en el tramo elástico de la demanda se traduce en una caída más que proporcional en la cantidad vendida. Ello crea las condiciones para que productor y distribuidor negocien, ya que ambos pueden ganar si lo hacen. El resultado final de esta negociación entre empresas monopólicas, dependerá del poder relativo de cada una y, a prori, no es posible decir qué parte saldrá más favorecida.

Existen tres soluciones al problema del doble margen, las que se presentan suponiendo que todo el poder de negociación está en manos del productor. La primera es que el productor imponga un precio máximo de reventa al distribuidor, conocido como mantenimiento de precio de reventa (o _resale price maintenance_, RPM por sus siglas en inglés). Cualquier precio menor al que fijaría el distribuidor sin este requerimiento, mejora tanto a los consumidores como al productor. 

La segunda es que el productor ofrezca un contrato al distribuidor que imponga una cantidad mínima de compra. Si esta cantidad es igual a la que vendería el productor al público, en ausencia del distribuidor, entonces el distribuidor deberá fijar el precio asociado si quiere vender todas las unidades que compró. Esta solución es la inversa de la primera: en vez de fijar el precio, se fija la cantidad. 

Una tercera solución es implementar una tarifa en dos partes que tiene un componente fijo y otra variable que depende de la cantidad que compre el distribuidor. Esta solución también se conoce como franquicia, ya que el pago fijo se asemeja a la compra de la licencia de la franquicia. Esta solución implica que el productor vende los productos al costo y obtiene beneficios a través del componente fijo. Como el componente fijo no distorsiona la cantidad que compra la empresa distribuidora —aunque sí influye en su decisión de comerciar—, al comprar al costo toma la misma decisión que haría la empresa productora; es decir, el precio que fija es el que establecería aquella como monopolista. Luego, la empresa productora puede obtener la renta monopólica de la distribuidora a través del componente fijo.

El tercer tipo de problema que surge en la relación vertical entre empresas productoras y distribuidoras es más complejo, ya que depende de la forma específica que adopte la misma. El elemento común a todos ellos es el parasitismo de las inversiones ajenas. En esta situación pueden observarse tanto casos donde no hay restricción vertical entre las partes, como otros donde sí operan restricciones verticales. Entre los primeros, una lista no taxativa de ejemplos son los siguientes: (i) dos distribuidores tienen que realizar inversiones para publicitar una marca que benefician a ambos; (ii) un productor realiza inversiones específicas en un distribuidor (por ejemplo, capacitación) que otros productores pueden utilizar; (iii) un proveedor puede utilizar la marca del productor (ejemplo, McDonalds) para obtener tráfico y vender productos que le reportan ingresos, pero que el dueño de la marca no aceptaría; (iv) un productor utiliza a un distribuidor para colocar sus productos (ejemplo, Starbucks) aprovechando su imagen. 

En todos los casos, hay una parte que aprovecha inversiones realizadas por otra a su favor. En la realidad estos efectos no se observan dado que las partes instrumentan restricciones entre sí para impedir el parasitismo. Sin embargo, la solución de este problema pasa por crear algún tipo de exclusividad para alinear los incentivos de las partes, lo que a su vez genera el problema del doble margen. Por tanto, la solución al problema del parasitismo está atada y requiere, también, resolver el problema del doble margen.

Entre los casos en que operan restricciones verticales, los siguientes son ejemplos de problemas específicos y sus soluciones. La distribución de productos requiere muchas veces que los distribuidores realicen actividades específicas para potenciar el uso de la marca del productor. Si los distribuidores no pueden apropiarse de los retornos de estas inversiones, no tendrán incentivos al esfuerzo. Una solución es establecer restricciones territoriales —por ejemplo, la distribución en determinadas zonas geográficas, o la franquicia de una marca en un país— o distribución exclusiva. En ambos casos se establece el monopolio de un distribuidor sobre un área geográfica para que internalice los esfuerzos o inversiones que realice. Sin embargo, este acuerdo de distribución territorial o exclusividad tiene que incluir una tarifa en dos partes o un RPM de forma de que el distribuidor no fije precios monopólicos. Estos acuerdos de distribución exclusiva con un instrumento muy utilizado por los productores, dado que tienen otros efectos positivos. Al asignar zonas exclusivas, los productores
pueden controlar en forma más eficiente la forma en la que se atiende cada mercado, además de generar subsidios cruzados al restringir la competencia de otros distribuidores en zonas que tienen picos de demanda.

En otros casos la imposición de un precio mínimo basta para incentivar a los distribuidores, como medida alternativa a la distribución exclusiva. Por ejemplo, si aquellos tienen que realizar acciones específicas para promocionar el producto, como por ejemplo exhibirlo o tener personal capacitado para atender a los consumidores, entonces algunos distribuidores pueden optar por no hacer las inversiones y vender el producto más barato, dado que sus costos son menores a los que sí ofrecen el servicio. Un precio mínimo basta para evitar que los distribuidores se parasiten entre sí.

Un problema común que se presenta en la relación entre productores y distribuidores es el de la reputación. Como fuera mencionado, tanto productores como distribuidores proveen reputación de sus productos o servicios. Por ejemplo, los relojes Rolex o Mont Blanc son marcas de muy alta calidad y reputación. Para poder distribuir sus productos se requiere cumplir con una serie de condiciones, es decir la empresa selecciona a sus distribuidores. Esta distribución selectiva tiene que estar acompañada por RPM de forma de evitar el problema del doble margen. En general, las agencias de competencia miran que las condiciones establecidas para la distribución selectiva sean generales y no discriminatorias.

Si el problema de reputación es a la inversa —el distribuidor tiene la marca— entonces el productor tiene que pagar una tarifa de acceso, de forma de evitar el parasitismo y la sobre demanda. Un caso típico es el de los supermercados, que cobran por el acceso a la góndola, peaje que regula los incentivos de los productores a utilizar la marca de los distribuidores.


### Prácticas anticompetitivas

Si bien las relaciones verticales entre empresas presentan complejidades, las soluciones, sin embargo, están al alcance de las partes. Los mismos incentivos que se analizaron como parte de la eficiencia en las relaciones verticales, son los que generan los comportamientos anticompetitivos que pueden facilitar la colusión entre productores; utilizar a los distribuidores como mecanismo para aumentar los precios a los consumidores; y utilizar a los distribuidores para cerrar el acceso al mercado a otros productores.

Si dos o más productores quieren formar un cartel y venden sus productos a través de distribuidores, entonces otorgarles libertad de acción dificulta el control de los posibles desvíos del acuerdo. Si un productor observa un precio en un distribuidor, menor al acordado, no puede saber si este precio es producto de un desvío del productor o lo ha fijado el distribuidor. Por tanto, si los productores quieren que el acuerdo colusivo sea operativo, tienen que fijar un precio mínimo de reventa a los distribuidores de forma de obligarlos a no sabotear el acuerdo. Este precio mínimo se analizó previamente en el caso de inversiones específicas por parte de los distribuidores, lo que demuestra que un mismo instrumento puede utilizarse con fines opuestos según el contexto. 

Un mecanismo alternativo, pero que permite obtener el mismo resultado, es que los productores elijan un distribuidor único para sus productos. En este caso, el distribuidor puede actuar como un monopolista que opera mirando el mercado de ambas empresas, lo que les permite a los productores fijar precios monopólicos al
consumidor.

El segundo problema anticompetitivo surge cuando se analiza la competencia intra marca y refiere a la falta de compromiso del productor. Si un productor tiene un producto relativamente valioso, distribuirlo a través de varias empresas le puede generar problemas. Si el producto se vende a través de un distribuidor, este estará dispuesto a pagar un alto precio por el producto, debido a las perspectivas de obtener una renta importante al venderlo a los consumidores. Pero una vez vendido el bien, con el plus que otorga ser el único distribuidor del mismo, el productor puede ir a otro distribuidor e intentar venderle el producto a un precio menor, lo que le permite tener una ventaja sobre el otro distribuidor, y así sucesivamente. Los distribuidores prevén que, sin una garantía de exclusividad, el productor no querrá mantener su promesa y se negarán a pagar un precio alto por el producto de la empresa productora.

La forma de recuperar la credibilidad es instrumentar algún tipo de restricción vertical, como territorios exclusivos para los distribuidores o un precio mínimo de reventa (RPM). Con el primer instrumento, el productor restringe la competencia entre distribuidores y, con ello, la posibilidad de renegociar el acuerdo. Es decir, garantiza el monopolio a los distribuidores en las zonas establecidas. El segundo señala a los distribuidores que no intentará rebajar el precio al que les vende y que, si lo hace, ello no significará una ventaja para el distribuidor (ya que no pueden arbitrarse entre sí). En última instancia, la existencia de múltiples distribuidores es una tentación que el productor busca resistir imponiéndose limitaciones. Ello le permite recuperar la credibilidad y aumentar el precio final a los consumidores y los beneficios.

Por último, las restricciones verticales permiten que los productores utilicen a los distribuidores o a los proveedores de insumo para cerrar el acceso al mercado de competidores. En el primer caso, un productor puede cerrar el mercado a otro simplemente ofreciendo contratos de exclusividad a los distribuidores. En general, si la empresa tiene posición dominante, ello dificulta el ingreso de nuevos productores al canal de distribución, ya que estos necesitan disponer de recursos para romper los acuerdos entre la empresa instalada y sus distribuidores. En el segundo, el contrato puede realizarse con un proveedor de insumos al que se puede ofrecer un contrato de exclusividad de compra que le permita a la empresa enfrentar en forma más beneficiosa la competencia en su mercado, dejando en desventaja a otras firmas que no tienen igual acceso a insumos específicos. En cualquier caso, para que estas estrategias sean exitosas, las empresas que las realizan tienen que tener una posición dominante en el mercado. 

Las restricciones verticales, en resumen, pueden tener tanto efectos beneficiosos que permiten aumentar el bienestar de los agentes, como pueden utilizarse como mecanismos para ejercer prácticas anticompetitivas. Las conductas de las empresas tienen que analizarse caso a caso y determinar, en cada uno, su impacto sobre la competencia. Establecer reglas per se para restricciones verticales es un riesgo, ya que en algunos casos aumentarán los costos de transacción de utilizar el mercado y los riesgos a los que se exponen las empresas por transar entre sí. Penalizar una conducta más que otra, cuando tienen el mismo efecto, lo único que hará es incentivar a las empresas a realizar la conducta permitida. A vía de ejemplo, el RPM tiene efectos anticompetitivos similares a la fijación de cantidades —o imposición de un surtido completo.


### Aplicación

En la Unión Europea, las prácticas verticales se analizan igual que las conductas de abuso de posición dominante, de la cual son expresión. Sin embargo, hay lineamientos específicos para este tipo de práctica que, a pesar de haber sufrido modificaciones, son controvertidos.
^[Véase @UE2010.]
Estos lineamientos, presentan una particular aversión a los acuerdos de RPM que, como se analizó, no son el único instrumento para alcanzar una conducta anticompetitiva. Se aplican a empresas con cuotas de mercado mayores al 30%, con excepción de conductas especialmente graves (como el RPM) donde no operan excepciones, y siempre que las restricciones no impliquen plazos mayores de 5 años. 

La metodología analiza nueve puntos: (i) la naturaleza del acuerdo; (ii) la posición de mercado de cada una de las partes; (iii) la posición de mercado de los competidores; iv) la posición de los compradores del producto; (v) las barreras a la entrada; (vi) la madurez del mercado; (vii) si el bien es intermedio o final; (viii) la naturaleza del producto; y (ix) otros elementos. Asimismo, se analizan una serie de conductas y se listan los beneficios y riesgos para la competencia de cada una de ellas.

Algunas conductas consideradas por la Comisión de la Unión Europea son:

1. **Acuerdos de marca única**: son aquellos que consisten en inducir al comprador a concretar sus pedidos de un tipo de producto concreto a un único proveedor. Entre estas conductas se incluye la imposición de compras mínimas y las cláusulas de no competencia —es decir, compras mayores al 80% de los productos a un único proveedor—. Los riesgos que señala la Comisión en estos acuerdos, son la exclusión de potenciales competidores, la colusión entre proveedores y la pérdida de competencia inter marca.

1. **Distribución exclusiva**: es la práctica por la cual el proveedor acepta vender sus productos exclusivamente a un distribuidor para su reventa en un territorio determinado. Los riesgos de esta conducta son la exclusión de competidores potenciales, la colusión entre proveedores y la pérdida de competencia intra marca.

1. **Asignación de cliente exclusivo**: cuando un proveedor acuerda vender sus productos solamente a un distribuidor para la reventa a un grupo de clientes. En general, es eficiente si existen inversiones específicas, aunque puede aparejar riesgos de exclusión de competidores potenciales o la colusión entre proveedores.

1. **Distribución selectiva**: restringe el número de distribuidores autorizados y las posibilidades de reventa. A diferencia de la distribución exclusiva, la restricción en el número de distribuidores depende de criterios de selección relacionada con la naturaleza del producto. La práctica implica riesgos de exclusión de competidores potenciales, de colusión entre proveedores y de pérdida de competencia intra marca.

1. **Franquicia**: son acuerdos que contienen licencias de derechos de propiedad intelectual relativos a marcas o signos registrados, y conocimientos técnicos para el uso y la distribución de bienes y servicios. Sirve para transferir conocimientos, y se requiere para proteger este activo. Los pagos de acceso inicial son cánones fijos que los proveedores pagan a los distribuidores en el marco de una relación vertical al principio de un período, para obtener acceso a su red de distribución y remunerar servicios proporcionados a los proveedores por los minoristas. Incluye las tasas por asignación de espacio, las tasas de mantenimiento, los pagos para tener acceso a las campañas de promoción de un distribuidor, entre otros. El riesgo que se enfrenta con esta práctica es la exclusión de competidores potenciales y además facilita la colusión.

1. **Mantenimiento de precio de reventa (RPM)**: son acuerdos o prácticas concertadas —nótese la similitud del lenguaje con la colusión— cuyo objeto directo o indirecto es el establecimiento de un precio de reventa fijo o mínimo o un nivel de precio fijo o mínimo al que debe ajustarse el comprador. Para la Unión Europea este tipo de conducta es especialmente grave y no tiene exoneración alguna, siendo la práctica a la que más espacio dedican los lineamientos de la Comisión. La lista de potenciales riesgos incluye la colusión (de proveedores o de distribuidores), la reducción de la competencia entre productores o minoristas, el incremento de los precios de los distribui dores y del margen del productor, la exclusión de productores pequeños, así como la reducción en la innovación en distribución.


## Fusiones y Adquisiciones

El tema más controvertido en defensa de la competencia refiere al control de las estructuras de mercado. En el comienzo de las actividades de defensa de la competencia, las legislaciones estudiaban el abuso de posición dominante o los carteles, mientras que el control de las fusiones se introdujo con posterioridad. En EUA, mientras el Acta Sherman es de 1890, la primera norma de control de estructuras de mercado, la [Ley Clayton](https://wps.prenhall.com/wps/media/objects/751/769950/Documents_Library/clayton.htm), data de 1914. Por su parte, en Europa hay un movimiento similar ya que si bien las normas de control de las conductas de las empresas se establecen con el Acuerdo Constitutivo de la Comunidad Económica Europea en 1962, el control de las fusiones comienza en el 2004 con la [Regulación No. 139/2004](https://eur-lex.europa.eu/legal-content/ES/TXT/PDF/?uri=CELEX:32004R0139&from=ES). Es decir, en general los países comenzaron con normas que regulan conductas de los agentes y con posterioridad pasaron a aplicar normas que regulan la estructura del mercado. 

Sin embargo, este control varía entre países. Por ejemplo, mientras que las legislaciones de competencia en el mundo regulan la fusión de una empresa, en EUA se han dado casos en los cuales el Departamento de Justicia ordena la separación de empresas, lo que resulta impensable en otros países.

El principal problema del análisis de fusiones es que se realiza antes de que la fusión se concrete e implica proyectar una situación futura del mercado, lo que resulta complejo y no está exento de controversias. Una vez consumada o denegada una fusión, múltiples elementos inciden en su resultado, el que no puede ser atribuido completamente al accionar ni de las empresas ni de los organismos de aplicación de las normas de competencia. Realizar un análisis prospectivo de la situación de mercado, en caso de que una fusión se materialice, es costoso
y complejo. Corresponde señalar también que los casos de denegatorias de fusión son la excepción más que la regla, aunque muchas veces las autoridades de competencia condicionan la misma a que las empresas desinviertan activos.

Las fusiones pueden ser de tres tipos. Las fusiones son **horizontales**, cuando las partes son empresas competidoras. Esta fusión transforma a dos empresas competidoras en una única empresa. Ello tiene impactos positivos sobre la eficiencia toda vez que permita reducir los costos de producción (ya sea mejor utilización de activos fijos o economías de escala), pero también puede facilitar la colusión o prácticas explotativas. 

Estas fusiones no son idénticas a una colusión. Cuando dos empresas se transforman en una, pueden racionalizar el uso del personal y de las instalaciones, lo que no sucede cuando son unidades separadas. Por tanto, las fusiones horizontales pueden generar mejoras de eficiencia. Estas eficiencias generan la necesidad de balancear los intereses de productores y consumidores. 

@Williamson1968 plantea esta dicotomía de intereses a través de un simple ejemplo: una fusión permite reducir los costos de las empresas, lo que aumenta el bienestar social, pero a la vez incrementa el precio a los consumidores, lo que disminuye el bienestar social. Si, como resultado, el excedente total se incrementa, esta medida va en sentido contrario al excedente del consumidor que disminuye, producto del aumento de precio. Por tanto, si se adopta el excedente del consumidor como medida del bienestar, no se puede aceptar ninguna fusión que incremente precios, independientemente de las reducciones de costos; mientras que si se adopta el excedente total, fusiones que aumenten los precios pueden ser aprobadas. Es decir, la fusión produce un problema distributivo. 

En general los órganos de defensa de la competencia concentran su interés en determinar si el resultado final de la fusión será un incremento de los precios, mientras que las eficiencias de costo son de segundo orden. Si producto de una fusión se puede predecir un aumento de precios, entonces aquella nunca será aprobada. Esta vinculación entre precios y eficiencias también se obtiene en los principales modelos económicos que analizan las fusiones. Estos demuestran que las eficiencias de costo —reducción de costos variables— tienen que ser muy importantes para que se trasladen a precio. Ello, en general, perjudica a las empresas que no integran la fusión, por lo que buscarán oponerse a la misma.

Por otra parte, la fusión de empresas puede impactar también sobre la posibilidad de que las empresas formen un cartel ex post. Una fusión —con eficiencias— tiene un impacto a priori ambiguo sobre la probabilidad de que las empresas coludan después de que la fusión ocurra. Por un lado, facilita la colusión dado que hay menos empresas en el mercado y ello aumenta la posibilidad de que alcancen un acuerdo. Por otro, si las empresas fusionadas ganan en eficiencia, aumenta la asimetría entre las empresas del mercado lo que dificulta la colusión. Se puede demostrar que la probabilidad de colusión aumenta si las eficiencias no son muy importantes, es decir, si las asimetrías no son grandes. 

En resumen, si las ganancias de eficiencia entre las empresas fusionadas no son importantes, aumenta la probabilidad tanto de que la nueva empresa ejerza comportamientos explotativos —prácticas unilaterales— como que se conformen carteles en el mercado —prácticas concertadas.

Las fusiones **verticales** involucran empresas en distintos eslabones de la cadena de valor. Son una alternativa a las restricciones, por tanto tienen los mismos riesgos y beneficios. Las fusiones verticales, a diferencia de las horizontales, buscan en general resolver problemas de eficiencia como los mencionados en la sección \@ref(eficiencia). Los problemas de doble margen, los incentivos a la inversión y el problema de parasitismo se resuelven si las empresas se integran.

Pero estas fusiones pueden servir también a fines anticompetitivos, si tienen como objetivo resolver el problema de compromiso o llevan a la exclusión de competidores. El problema de compromiso surge cuando la empresa no puede comprometerse a no arbitrar a sus distribuidores, lo que lleva a que la competencia entre ellos reduzca los beneficios extra normales que puede obtener. Si el productor se fusiona resuelve en forma sencilla este problema, ya que ahora hay un único distribuidor y puede fijar el precio que crea pertinente al consumidor. La exclusión de competidores se da cuando la fusión entre una empresa productora y su proveedor obliga a un competidor de la empresa productora a obtener sus insumos con proveedores más ineficientes, lo que incrementa sus costos y la hace menos competitiva.

Por último, las fusiones de **conglomerado** involucran empresas que participan en mercados que no están vinculados entre sí, como puede ser un productor de alimentos y otro de limpieza. Estas fusiones permiten mejorar el poder de negociación de las empresas, ya que incorpora productos a su portafolio. Pueden utilizarse para atar productos o cerrar el mercado, como cuando los productores arman canastas de productos y mejoran su posición negociadora con los distribuidores. En particular, se verifican los problemas asociados a las canastas: (i) extender el monopolio a otros mercados; (ii) cerrar el mercado a rivales; e (iii) inducir exclusividades o servir para mejorar descuentos. 

Para analizar las fusiones es clave conocer el mercado relevante. En la medida en que este análisis prevé predecir el escenario competitivo con posterioridad a la fusión, hay que entender claramente el mercado y los agentes que participan en él. Excepcionalmente, a veces no es necesario un análisis detallado del mercado si se cuenta con información y un análisis estadístico adecuado para evaluar el impacto de la fusión ex ante. 

Un caso paradigmático fue el análisis de la fusión entre dos distribuidores minoristas de insumos para oficina Staples y su rival Home Depot, realizado por el Departamento de Justicia y la Comisión Federal de Comercio (FTC) de EUA (@Baker1999). La FTC observó la fusión en base a un estudio detallado en el que demostró que Staples cobraba precios 9% mayores en aquellas ciudades donde no competía con Home Depot. Basándose en ese análisis, las empresas abandonaron el intento de fusión, aunque en 2015 estaban intentando fusionarse nuevamente. Lo interesante de este caso es que no fue necesaria una definición explícita del mercado relevante, debido a que el efecto de la fusión pudo predecirse. 
^[Aun así, el mercado relevante fue definido como el de venta de insumos de oficina a través de grandes tiendas de artículos de oficina. El mercado relevante geográfico fue definido como el área metropolitana de la ciudad.]

Lo que sí resulta claro es que el análisis de las fusiones es complejo y costoso para las empresas y para las agencias de competencia. Por ello, parece prudente afinar el interés en aquellas fusiones que pueden tener un impacto sobre el mercado, es decir, las que involucran a empresas dominantes.

En muchos países, como en Uruguay, existe un doble umbral para el análisis de fusiones: por monto y por porcentaje de mercado. Si la fusión involucra a dos empresas cuya facturación excede un determinado umbral, entonces deben solicitar autorización previa. Lo mismo ocurre si las empresas pasan un determinado umbral de mercado relevante. Este último indicador, sin embargo, se ha comenzado a abandonar en la medida en que no resulta objetivo para las empresas. En efecto, deben esperar a que el órgano de aplicación decida cuál es el mercado relevante para conocer si pasan o no el umbral establecido. 

Por otra parte, los umbrales de facturación son objetivos para las empresas, aunque pueden permitir que se fusionen empresas de un tamaño pequeño respecto a la economía, pero relevante en su mercado. Algunos países han redactado lineamientos para las fusiones, entre los que destacan las [_Horizontal Merger Guidelines (2010)_](https://www.ftc.gov/sites/default/files/attachments/merger-review/100819hmg.pdf) de EUA, las [_Non Horizontal Merger Guidelines (2008)_](https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:C:2008:265:0006:0025:en:PDF) y las [_Horizontal Merger Guidelines (2004)_](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:52004XC0205(02)&from=EN) de la Unión Europea. 

Las _Merger Guidelines_ en EUA establecen umbrales seguros por debajo de los cuales la fusión no será investigada, utilizando para ello el _HHI_. En particular, si las empresas cumplen los siguientes requisitos la fusión se aprueba, en caso contrario se analiza: (i) $HHI \leq  1.000$; (ii) $1.000 < HHI \leq 1.800$ y $\bigtriangleup HHI \leq 100$; y (iii) $HHI > 1.800$ y $\bigtriangleup HHI \leq 50$.

Un régimen de análisis particular tienen las fusiones donde alguna de las empresas involucradas se encuentra en quiebra. Las normas de competencia establecen algunas reglas para este tipo de fusión. La comparación relevante en este caso es entre la fusión de las empresas y la situación en la que la empresa sale del mercado. En general, las reglas que se siguen para que se acepte una fusión de este tipo son: (i) la empresa en quiebra no puede cumplir sus próximas obligaciones; (ii) no puede reorganizarse en forma exitosa bajo las normas de bancarrota; (iii) no existen compradores alternativos que mantengan la empresa en funcionamiento; y (iv) si la fusión no se produce, la empresa sale del mercado. Si estos cuatro pasos se cumplen, entonces podría aprobarse una fusión que involucre a una empresa competidora en quiebra.

Quizá el punto más controvertido en el análisis de fusiones es el de las eficiencias de las empresas fusionadas. Si existen importantes ganancias de eficiencia, entonces será beneficioso desde el punto de vista social que se fusionen dos empresas competidoras. Las eficiencias de este tipo de fusiones pueden involucrar economías de escala o de alcance, sinergias en I+D, racionalización de la distribución y el marketing, entre otros. 

Sin embargo, las fusiones horizontales que reducen costos fijos, si bien mejoran el bienestar social —eficiencia productiva— no se traducen en reducciones de precio, ya que en su determinación sólo se toman en cuenta los costos variables. Por tanto, una reducción de costos fijos, aunque beneficioso para las empresas, no servirá para que una fusión sea aprobada.

El resultado del análisis de las fusiones no tiene porqué implicar aceptación o rechazo. Algunas veces los órganos de competencia establecen condiciones para aprobar las fusiones, si se detectan efectos sobre el bienestar. Estas condiciones son de dos tipos. Por un lado, se pueden establecer condiciones estructurales que establecen que las empresas deben desinvertir determinados activos, como ser marcas, productos, plantas; o deben permitir el acceso a cierta infraestructura. El objetivo es permitir que competidores nuevos o existentes puedan utilizar esos activos para competir de mejor forma con la empresa fusionada. 

Sin embargo, estas condiciones enfrentan dos tipos de problemas. Primero, la empresa vendedora tiene incentivos a engañar al comprador respecto a la importancia relativa del activo, o a venderlos a empresas fantasmas u otras que no sean competidoras directas. Segundo, si los activos son transferidos a empresas competidoras, ello restablece la simetría en el mercado y aumenta la posibilidad de colusión ex post de la fusión. Por otro lado, se pueden establecer condiciones al comportamiento de las empresas fusionadas que restringen los derechos de propiedad sobre el uso de los activos, como las patentes. 
Estas condiciones también pueden restringir la publicidad de los productos, limitar la posibilidad de realizar canastas entre productos, o limitar las restricciones de no competencia a los funcionarios desplazados de las empresas. 25 
^[Cuando ocurren fusiones y algunos funcionarios de alto rango son cesados, las compensaciones que reciben incluyen como contrapartida cláusulas que limitan la posibilidad de trabajar para empresas competidoras o crear otras que compitan con la empresa que los despide.]

En otros casos, se le puede requerir a la empresa fusionada que reporte sus precios de venta por un tiempo, de forma de monitorear la evolución del mercado. En cualquier caso, las soluciones de comportamiento trasforman a las autoridades de competencia en un regulador, tarea que es difícil y compleja de llevar a cabo.

En conclusión, el análisis de fusiones es un trabajo complejo. Requiere un análisis detallado del mercado y su competencia. Hay que predecir el comportamiento futuro de los precios, si las fusiones son horizontales; que se produzca un cierre del mercado a competidores, si son verticales; o que se generen portafolios que puedan ser utilizados para bloquear el acceso a empresas rivales, si son de conglomerado. También hay que ponderar adecuadamente las posibles eficiencias que la fusión genere. Por último, si la fusión tiene efectos positivos y negativos sobre el mercado, deben diseñarse condicionamientos que mitiguen los efectos negativos, a la vez que permitan aprovechar los positivos.


## Reflexiones Finales

La esencia de una economía de mercado es que las empresas compitan entre sí por los clientes. Cuando ello ocurre, los productos mejoran, se hacen más accesibles y las empresas introducen nuevos bienes y servicios que permiten mejorar el bienestar de los consumidores. En este marco, la recompensa es la fidelidad de los clientes, que se traduce en la rentabilidad y tamaño relativo otras estrategias que les permite consolidar o mantener un poder de mercado del que no gozarían en otro caso. Asimismo, estas conductas no reportan bene ficios a los consumidores, que pierden variedad, nuevos productos o poder de compra.

El análisis de defensa de la competencia es una herramienta útil para entender la competencia en el mercado. No se requiere que exista una norma de competencia para su aplicación, ya que es una metodología general que sirve para entender dónde se encuentran los principales cuellos de botella competitivos. En particular, el instrumento del mercado relevante es una herramienta interesante para describir los mercados y comprender su funcionamiento. Muchas veces, sirve para poner el foco no sólo en los comportamientos de las empresas, sino también en las regulaciones de los mercados. 

Las empresas desarrollan comportamientos que son consistentes con las reglas de juego que reciben, en particular, con las regulaciones existentes o inexistentes. Contar con una metodología para analizar casos de defensa de la competencia, permite focalizar rápidamente una investigación, sirve para concentrar recursos y, en última instancia, establece prioridades. 

¿Cómo llevar a cabo una investigación por temas de competencia? Cuatro pasos eliminatorios que ayudan a guiar una investigación de defensa de la competencia. En primer lugar, ¿la conducta denunciada tiene sentido? No siempre las denuncias refieren a problemas de competencia y es importante descartarlos rápidamente. Detenerse a analizarla y comprender la racionalidad económica que explica las conductas analizadas es un primer paso importante que resuelve muchos problemas jurídicos posteriores.

En segundo lugar, ¿el infractor puede o podría tener posición dominante? La respuesta en este caso no debería ser “claramente sí”, sino “claramente no”. A priori puede no ser claro si una empresa o un conjunto de empresas tienen posición dominante, pero si puede ser obvio si no la detentan. Si las empresas claramente no tienen posición dominante, entonces el caso debería ser archivado pues continuar con él representa un costo en términos de recursos, pero también de posteriores situaciones incómodas para los órganos de aplicación.

En tercer lugar, ¿qué prueba es necesaria para probar o descartar una conducta anticompetitiva? Recolectar y procesar información es costoso en términos de recursos y tiempo. Un primer paso es buscar antecedentes de otros países que sirven para ahorrar el proceso de comprender el mercado y entender sus particularidades. También es importante poder contar con informantes calificados que aporten información cualitativa sobre el mercado. Si bien estos informantes no tendrán información detallada, son útiles para entender los detalles del de las empresas. Sin embargo, no siempre las empresas tienen los incentivos correctos a competir por sus clientes. Otras veces, buscan confabularse en su contra, desalientan a potenciales rivales de entrar al mercado, o llevan a cabo mercado, cómo operan las empresas y cuáles son los elementos en los que hay que centrar el análisis. Asimismo, estos informantes permiten saber dónde está la información que se requiere para sancionar o no una conducta, o para determinar la posición de la presunta infractora.

Por último, no puede dejar de señalarse que los casos de defensa de la competencia son siempre motivo de escrutinio y presiones políticas. Las empresas involucradas son siempre actores relevantes en sus mercados y tienen a su disposición recursos que a veces el sector público no dispone. Asimismo, pueden ejercer presiones políticas o movilizar a la prensa. Esas son las reglas de juego. Por tanto, cualquier decisión que se tome debe ser considerada como un antecedente de posibles futuros casos. Sean los antecedentes fuente o no de jurisprudencia, mantener una línea coherente ayuda a percibir la fortaleza de los órganos de aplicación.