# Instituciones regulatorias para economías en desarrollo {#instituciones-reg}

Jorge Ponce

\

En el pasado reciente diversos países de América Latina, así como también en otros continentes, han llevado adelante diversos procesos de reforma en los mercados de servicios públicos tales como telecomunicaciones, energía eléctrica, agua y saneamiento. El éxito de estos procesos ha sido variado. Diversas razones que hacen a las diferencias en el entorno institucional, los procesos políticos e incluso la historia concreta, los diferentes puntos de partida y el estadio de desarrollo de los países, podrían determinar el diferencial en los resultados.

Por ejemplo, @Bergara2005 argumentan que la política relativa a servicios públicos en Argentina ha sido altamente volátil y llevada adelante sin el desarrollo de una institucionalidad regulatoria adecuada. Como resultado, identifican situaciones extremas que van desde la captura de los reguladores por parte de la industria a la expropiación de las firmas privadas por parte del gobierno. Esto, en un entorno institucional signado por la casi imposibilidad de recurrir al sistema judicial para resolver controversias y la rápida limitación de los poderes de las agencias regulatorias por parte del sistema político, por ejemplo restringiendo sus cometidos, capacidad técnica y recursos financieros. @Spiller2003 también argumentan que los mecanismos para hacer cumplir los compromisos han sido extremadamente débiles y que los “servidores públicos” no visualizaban objetivos de largo plazo, alentando el incumplimiento de las normas y la corrupción.

En tanto, las reformas llevadas adelante en Chile obtuvieron resultados más estables al desarrollarse en un marco de consistencia institucional. La relativa fortaleza institucional posibilitó el establecimiento de sistemas de regulación por precio límite, fijado para cumplir con una meta de rentabilidad sobre costos y capital de una empresa modelo eficiente. Este tipo de regulación determinala provisión de incentivos de alto poder a las firmas y ha operado en un marco de estrecha coordinación para mantener la eficiencia en el uso de los fondos públicos. Además, la relativa fortaleza institucional de los reguladores se ha basado en su capacidad técnica, generada por contar con recursos humanos y económicos considerablemente mayores que en el resto de la región.

Estos ejemplos muestran que los países en desarrollo presentan particularidades que, de una manera u otra, determinan la posibilidad de realizar determinado tipo de reformas, así como también sus resultados, una vez que las mismas son llevadas adelante. La práctica ha demostrado entonces que las teorías regulatorias tradicionales, elaboradas para ser aplicadas en países desarrollados, son de una aplicabilidad mucho más limitada en países menos desarrollados e incluso pueden aparejar graves consecuencias en términos de bienestar social. De esta forma, entender el contexto institucional y sus implicaciones resulta de crucial importancia para el diseño de las instituciones regulatorias en economías en desarrollo.

Este capítulo considera algunas de las principales limitaciones institucionales que ocurren con frecuencia en economías en desarrollo y analiza las dificultades que las mismas imponen para el diseño de la regulación, así como las posibles soluciones para paliar esas dificultades. A los efectos de tener un punto de referencia a partir del cual comparar los hallazgos, se introduce (en la sección \@ref(modelo)) un modelo simple y comúnmente utilizado para analizar la regulación de actividades económicas en economías desarrolladas. A partir del mismo, se extiende la contribución seminal de @Laffont2005 para analizar las implicaciones de considerar aspectos distintivos de las economías menos desarrolladas. En particular, la sección \@ref(desafios) estará dedicada a explorar cómo el modelo puede ser adaptado para analizar algunas limitaciones institucionales comunes a estas economías: baja capacidad técnica para la regulación y la supervisión, baja rendición de cuentas, compromiso limitado y falta de credibilidad, baja eficiencia fiscal, corrupción, baja capacidad de hacer cumplir las normas y alta posibilidad de captura del regulador.

El capítulo provee entonces un panorama general de los principales aspectos a considerar a la hora de diseñar instituciones regulatorias en economías en desarrollo y de los posibles caminos a seguir para obtener resultados que beneficien a la sociedad en su conjunto. En los comentarios finales, ofrecidos en la sección \@ref(coment-fin), se resumen las principales características que la regulación eficiente debería mostrar según los diferentes estadios de desarrollo de las economías.

Antes de entrar de lleno al análisis del diseño de las instituciones regulatorias para economías en desarrollo se provee, en la siguiente sección, una breve introducción a las razones, los objetivos y las dificultades de la regulación de la actividad económica.


## Regulación: razones, objetivos y dificultades

¿Qué es regulación? Regulación generalmente refiere a un conjunto específico de reglas aplicadas a determinado conjunto de agentes con un propósito. Más en general, de acuerdo a @Baldwin2011, **regulación** es cualquier influencia deliberada por parte del Estado, como por ejemplo a través de los sistemas impositivos, de franquicias, etc. Es interesante distinguir el concepto de regulación del concepto íntimamente relacionado de supervisión. Mientras que regulación refiere al conjunto específico de reglas y normas que restringen el accionar y proporcionan incentivos (guían) a los agentes en determinados mercados, la **supervisión** refiere a la observación del cumplimiento de la regulación. Por tanto, la supervisión representa un importante esfuerzo para recolectar información y para hacer cumplir las normas.

Pero, ¿por qué es necesaria la regulación y la supervisión de determinadas actividades económicas? ¿Cuál es su objetivo? En términos generales, la regulación y supervisión se justifican por la existencia de fallas de mercado. Esto es, situaciones en las que el funcionamiento libre de los mercados no es suficiente para obtener los resultados o comportamientos buscados por el interés público. 

En otros términos, si el funcionamiento del mercado proveyera resultados adecuados desde el punto de vista del bienestar social no sería necesario introducir regulación alguna. A modo de ejemplo, varios procesos de reestructura en la provisión de servicios públicos tales como electricidad, gas o agua potable generalmente determinan la existencia de un proveedor monopólico operando en el sector privado. 

En ausencia de intervención pública, bajo la forma de regulación y supervisión del mercado, el monopolista restringirá la cantidad (y posiblemente la calidad) provista y cargará un precio excesivamente alto a los consumidores. Incluso sus decisiones de inversión podrían determinar que importantes sectores de la población, por ejemplo aquellas áreas de menor densidad poblacional, no puedan acceder a los servicios aún si estuvieran dispuestos a pagar el precio solicitado. Entonces, algún tipo de regulación se hace necesaria para balancear el bienestar de los consumidores y del monopolista, a los efectos de alcanzar un nivel superior de bienestar social.

Existe un acuerdo generalizado, tanto en la industria como en la academia, en cuanto a que el objetivo de la regulación de servicios públicos es promover la eficiencia en la provisión de los bienes y servicios regulados, tanto desde un punto de vista estático como dinámico (esto es promoviendo los procesos de inversión que posibiliten reducir costos en el futuro). Además, al tiempo de promover la eficiencia, la regulación debe proteger a los consumidores del potencial abuso de la posición dominante de la firma monopólica, así como a los inversores y a los operadores de los servicios de la potencial influencia y oportunismo del sistema político.

Pero, ¿por qué los consumidores no son capaces de implementar y hacer cumplir algún tipo de regulación directamente? Además de una razón evidente que es el diferente poder de negociación de consumidores y firma monopólica (muchas veces explicada a su vez por la diferente información a la que unos y otros acceden), existen otras razones tales como lo que en la jerga económica se conoce como problema de polizón en la provisión de bienes públicos. Esto es, el costo privado de cada consumidor de llevar adelante la regulación superará ampliamente el beneficio del cual el consumidor se podrá apropiar debido a que los otros consumidores, aun no habiendo incurrido el costo de regular, disfrutarán de una parte de los beneficios generados por la regulación. De esta manera, la regulación sólo podrá ser llevada adelante si alguna institución regulatoria, actuando en nombre de los consumidores, colectiviza tanto los costos como los beneficios generados por la introducción de la regulación.

Entonces, tan importantes como las reglas son las estructuras y los procesos en los que se sustenta la regulación. En otros términos, tan importante como el qué regulación introducir son el quién la llevará adelante y el cómo se desarrollará el proceso regulatorio. A modo de ejemplo, las estructuras que podrían afectar el resultado de la regulación incluyen la distribución de los poderes entre diferentes agencias para desarrollar la regulación, los objetivos de estas agencias y los procedimientos de votación en ellas utilizados. 

En cuanto a los procesos, aspectos tales como el momento en el que se produce la intervención pública, el poder del regulador, las dimensiones sobre las que puede actuar y los canales de comunicación al interior de la jerarquía regulatoria, cobran particular importancia. En general, reglas, estructuras y procesos definen las instituciones regulatorias. Del diseño de estas instituciones para la regulación dependerá el resultado final de la misma. A su vez, este diseño deberá contemplar los diferentes costos de transacción que las características del entorno contractual imponen. 

En particular, es posible que una regulación que funciona adecuadamente en un país no brinde los resultados esperados en otro. Al análisis de estas diferencias, en función del grado de desarrollo de los países y de sus implicaciones para el diseño de instituciones regulatorias, estará dedicado el resto de este capítulo. Antes de proseguir con la introducción del modelo básico de regulación que servirá de guía para el análisis subsiguiente, brindaremos una exposición conceptual de las principales dificultades que, en general, el diseño de las instituciones regulatorias enfrenta.

Una vez que los consumidores delegan en una agencia regulatoria el control de los aspectos regulatorios sobre una determinada industria aparecen una serie de dificultades. En primer lugar, el control que un regulador puede ejercer sobre una firma determinada es sólo imperfecto por al menos dos razones. Primero, debido a la asimetría en la información que maneja la firma con respecto al regulador. A menudo el regulador desconoce la tecnología exacta de producción, sus costos o la elasticidad de la demanda que la firma enfrenta y tiene escaso conocimiento de la estructura de incentivos interna de la firma o de los contratos que pueda tener con sus proveedores. 

Segundo, si bien a menudo los reguladores tiene pocos cometidos a cumplir, también tienen relativamente pocos instrumentos para llevar adelante sus funciones. Más imperfecciones al proceso de control se agregan una vez que se tiene en cuenta que los reguladores no rinden cuenta directamente a los consumidores sino al sistema político (ya sea a través de la ramas Ejecutiva o Legislativa). Generalmente, los políticos están en desventaja informacional con respecto a los reguladores, no sólo por su acceso diferencial a la información relevante, sino también por su relativa inexperiencia a la hora de considerar aspectos que pueden ser extremadamente técnicos. Además, los propios políticos difícilmente reciban los incentivos correctos de los consumidores para actuar en pos del interés social, debido al mismo problema del polizón que impide a los consumidores controlar directamente a la firma. 

En cambio, los consumidores utilizan el sistema de votación, que resulta ser imperfecto, a la hora de garantizar la
rendición de cuentas de los políticos. De esta manera, cada una de las capas que conforman la estructura regulatoria puede ser vista como una relación de principal-agente con sus propios problemas de información asimétrica. En este sentido, el regulador (el principal) posee menos información que la firma (su agente), el sistema político posee menos información que el regulador que le debe rendir cuentas y, finalmente, los consumidores sólo pueden observar imperfectamente el esfuerzo y la eficiencia de los políticos que han votado. 

El hecho que el principal tenga menos información que su agente determina una serie de implicaciones, dentro de las cuales la más importante es que el principal requiere encontrar una solución de compromiso entre la eficiencia, en términos económicos, y la extracción de rentas por parte de la firma. Por ejemplo, un regulador puede no observar cuál es el verdadero costo de producción de la firma (un problema conocido en la literatura económica como de **selección adversa**) o, una vez que la firma está operando, el nivel de esfuerzo realizado por el empresario puede no ser verificable por parte del gobierno (un problema de **riesgo moral**) con lo cual se verá obligado a brindarle alguna pago para que revele su información (una **renta informacional**) y pueda lograrse una asignación eficiente de recursos. 

Por lo general, este compromiso entre rentas de la información y eficiencia en la producción se logra a través de mecanismos de **incentivos** que se encuentran implícitos en **contratos** entre el principal y el agente. En el caso de la relación entre el regulador y la firma, estos contratos toman la forma de regulaciones específicas. En lo que sigue se analizará el diseño de estos contratos.


## Un modelo básico de regulación {#modelo}

En esta sección se introduce un modelo canónico, muy similar al utilizado por @Laffont2005 para el análisis de la regulación en economías desarrolladas. La metodología y los resultados de este modelo servirán de punto de referencia para, en la siguiente sección, analizar los desafíos que las características de las economías en desarrollo imponen para el diseño de la regulación y las posibles soluciones sugeridas por la teoría. 

En la presentación utilizaremos expresiones matemáticas comúnmente utilizadas en la literatura sobre el tema. Si bien a los lectores más familiarizados con este tipo de modelos estas expresiones les facilitarán la lectura, a aquellos lectores menos familiarizados puede dificultársela. Hemos realizado un esfuerzo para que los conceptos puedan ser igualmente comprendidos sin reparar en tales expresiones matemáticas, por lo cual sugerimos a aquellos lectores menos familiarizados pasarlas rápidamente en una primera lectura.


### Principales elementos del modelo

El modelo considera: (i) consumidores; (ii) una firma, monopolio natural, a cargo de la provisión de un servicio público tal como agua, electricidad, telecomunicaciones o transporte; (iii) un gobierno benevolente; y (iv) un regulador y supervisor del mercado.

1. **Consumidores**. Los consumidores obtienen utilidad al consumir el producto ofrecido por la firma. Cuando consumen una cantidad q de la producción del monopolio, el nivel de utilidad obtenido por los consumidores estará definido por $S(q)$ (creciente pero con utilidad marginal decreciente: $S′ > 0$ y $S′′ < 0$). La demanda está representada por $P(q)$ (esto es, una relación decreciente entre el precio y la cantidad demandada), de tal forma  que el bienestar neto de los consumidores por el consumo del producto ofrecido por el monopolio es: $S(q) – qP(q)$, donde $qP(q)$ es el monto pagado a la firma por una cantidad $q$.
Los consumidores, además, pagan impuestos al gobierno. La recolección de impuestos está sujeta a ciertas ineficiencias y costos de transacción que determinan que la recolección de una cantidad $t$ de impuestos cueste a los consumidores $(1 + λ)t$, donde $λ > 0$ es el costo de oportunidad de los fondos públicos. Entonces, el bienestar neto de los consumidores por todas sus actividades será:
$$V = S(q) – qP(q) – (1 + λ)t$$
1. **Firma e información**. La producción tiene costos que están representados por la siguiente función: $$C(q) = (β – e)q + K$$
El costo fijo de producción es K , mientras que el costo marginal es $c = β – e$. La asimetría de información entre la firma y los consumidores (así como también con el gobierno que los representa) puede ser fácilmente mode lada a través de este último término. En particular, mientras que el costo fijo es conocido por todas las partes y el costo marginal $(c = β – e)$ puede ser observado ex post por el gobierno, los componentes del costo marginal son información privada de la firma. 
Más precisamente, $β$ representa las características específicas de la firma que están fuera del control directo del empresario: la firma puede ser eficiente en su producción $(β = \underline β$) o in eficiente $(β = \overline{β})$. Dado que el gobierno no observa $β$, enfrenta un problema de **selección adversa**. La firma conoce el valor de $β$ , pero el gobierno sólo conoce la probabilidad con la cual una firma es eficiente $ν = Pr (β = \underline β$) .
Entonces, una firma eficiente puede querer hacerse pasar por una ineficiente para conseguir mayores transferencias por parte del gobierno. En tanto, e es el término del costo marginal que es directamente controlable por el empresario, representa su nivel de esfuerzo. Para mantener la simplicidad se asume que este esfuerzo reduce uno a uno el costo marginal de la firma.
Esforzarse implica una desutilidad para el empresario $ψ(e)$, la que es creciente $(ψ′ > 0)$ y con tasa marginal de desutilidad también creciente $(ψ′′ > 0)$. Dado que el gobierno no puede observar el nivel de esfuerzo del empresario, este parámetro $e$ representa el **riesgo moral**: luego de obtenida cierta transferencia por parte del gobierno el empresario podría preferir no esforzarse.
La firma recibe además una transferencia t del gobierno, la que es financiada con impuestos a los consumidores. De esta forma, el beneficio neto de la firma es:
$$U = qP(q) – (β – e)q – K – ψ(e) + t$$
En este punto realizaremos dos supuestos. Primero, que la firma puede decidir no producir una vez que ha conocido su tipo (esto es, el componente $β$ de su costo marginal). En otras palabras, esto impone una restricción de  participación para la firma tal que $\overline U ≥ 0$ y $\underline U ≥ 0$, donde $\overline U$ es la utilidad de la firma cuando $\beta = \overline \beta$ y $\underline U$ es la utilidad de la firma cuando $U = \underline U$. 
^[A lo largo del texto las variables con una línea superpuesta corresponderán a las de una firma ineficiente, de costo $β = \overline β$, mientras que las variables con una línea subyacente corresponderán a una eficiente, de costo $β = \underline β$.]
De esta manera, el gobierno estará restringido en sus instrumentos para motivar a la firma ya que no podrá ofrecer contratos que le brinden una utilidad negativa. 
Segundo, asumiremos que el gobierno desea que tanto la firma del tipo eficiente como la del tipo ineficiente participen. Recuerde que la firma es en realidad una sola --un monopolio-- pero que su tipo o costo puede ser alto ($\beta = \overline \beta$, firma ineficiente) o bajo ($β = \underline β$, firma eficiente). Este supuesto implica que la provisión, aún ineficiente, del servicio público es preferida a su no provisión.

1. **Gobierno**. El gobierno es benevolente y desea maximizar el bienestar agregado de toda la sociedad,
^[Este supuesto de gobierno benevolente implica dejar de lado, por el momento, los posibles problemas de agencia entre consumidores y sistema político. Más precisamente, bajo este supuesto los objetivos del gobierno están perfectamente alineados con los de los consumidores. En este sentido, no hay problemas de principal-agente entre consumidores ya que los políticos representan fielmente sus intereses.]
esto es de consumidores y la firma monopólica:
$$W = U + V = S(q) – (β – e)q – K – ψ(e) – λt$$
Para ello el gobierno utiliza contratos con la firma que estipulan el costo marginal $(c)$, la cantidad del producto $(q)$ y la transferencia que recibirá la firma $(t)$. Más precisamente, el gobierno puede utilizar un menú de contratos diseñados para cada tipo de firma: $(\underline c, \underline q, \underline t )$ para la firma eficiente y para $(\overline c, \overline q, \overline t)$ para la firma ineficiente.

1. **Regulador/Supervisor**. El gobierno utiliza un regulador y supervisor del mercado para reducir su asimetría de información con respecto a la firma. El supervisor puede hacer conocer al gobierno el verdadero valor del parámetro de costo de $β$ de la firma. Más precisamente, el supervisor tiene acceso a una tecnología que le permite obtener una señal $r$ que puede ser informativa sobre el parámetro de costo de la firma: con probabilidad $ξ$ el  supervisor conoce el verdadero costo de la firma $(r = β)$ y con probabilidad $1 – ξ$ no recibe información alguna.
El gobierno enfrenta un problema de asimetría de información con el supervisor similar al que tiene con la firma: el supervisor puede preferir ocultar la información que ha obtenido y necesita recibir incentivos para revelarla. Entonces, el gobierno tiene que elaborar un contrato con el supervisor estipulando la transferencia a ser pagada al supervisor como una función de la información por este proporcionada. Esta transferencia es financiada con impuestos de forma que una transferencia de un importe $s$ cuesta a los consumidores $(1 + λ)s$. Entonces, cuando se incorpora el ingreso del supervisor al bienestar general el costo social de la transferencia al supervisor λs tiene que ser considerado:
$$W = S(q) – (β – e)q – K – ψ(e) – λt – λs$$
Que el supervisor pueda ocultar la información y que la firma observe tanto la señal que ha obtenido el supervisor como la información que este suministra al gobierno, abren la posibilidad de que la firma intente capturar al supervisor para que este mantenga desinformado al gobierno. 
En la práctica, son comunes las situaciones en las cuales puede ser de interés de una firma capturar a su supervisor. Por ejemplo, un artículo que apareciera en la prensa financiera daba cuenta que al recibir nuevos poderes para regular el mercado de productos derivativos en los Estados Unidos de América,
^[Fuente: Bloomberg, 13 de octubre de 2010: [“Wall Street Lobbyists Besiege CFTC to Shape Derivatives Rules”](http://www.bloomberg.com/news/articles/2010-10-14/wall-street-lobbyists-besiege-cftc-to-influence-regulations-on-derivatives).]
la _Commodity Futures Trading Commission_, que hasta entonces era una “pequeña y dormida agencia” (tal como su entonces Presidente, Mary Schapiro, la nombrara en los años noventa) se convirtió en uno de los puntos más concurridos por los cabilderos de la industria.
Los mecanismos a través de los cuales una firma puede intentar capturar al supervisor pueden ser tan variados como las razones para la captura: desde “simples regalos”, promesas de futuro empleo en la industria, sobornos, presiones políticas y hasta amenazas de ser conducido a juicio por las acciones que pudieran perjudicar los intereses de la firma. 
Dado que es imposible introducir en nuestro modelo esta variedad de mecanismos, realizaremos el supuesto que el resultado de los mismos puede ser representado por el valor de una transferencia monetaria. Por ejemplo, la promesa de un empleo en la firma puede ser representada por el valor presente de las compensaciones a recibir, mientras
que la amenaza de ser llevado a juicio puede ser representada por el valor presente de los costos judiciales que el supervisor evitaría al ser indulgente con la firma. Dadas las características de las transferencias en las cuales se resume la captura del supervisor por parte de la firma (por ejemplo por su baja transparencia e incluso potencial ilegalidad), asumiremos que el supervisor sólo accede a una fracción $k ε (0,1)$ de la misma.


### Puntos de referencia bajo un marco institucional completo

En la siguiente sección se discutirán los desafíos que la presencia de un marco institucional más débil en economías en desarrollo impone para el diseño de la regulación. En esta sección, se resolverá el modelo sin considerar tales debilidades, a los efectos de proporcionar un punto de referencia con respecto al cual evaluar los resultados de la próxima sección. 

Consideraremos diferentes situaciones: (a) cuando el supervisor informa el valor de $β$; (b) cuando el supervisor no reporta el valor de $β$; (c) cuándo tiene incentivo el supervisor para reportar la información; (d) cómo puede el gobierno minimizar el costo de proveer incentivos; y (e) cómo se define el poder de los incentivos.


#### Cuando el supervisor informa el valor de $\beta$

En este caso desaparece la asimetría de información entre la firma y el gobierno. Entonces, para maximizar el bienestar social el gobierno debería fijar una transferencia a la firma (contingente en su tipo ya que es conocido por el gobierno, esto es en el valor de $β$ de tal forma que no queden rentas excedentarias para la misma $(\underline U = \overline U=0)$. Además, en este caso el nivel de esfuerzo de la firma es eficiente. Esto es: $ψ′(e) = q$, la utilidad marginal del esfuerzo es igual al costo marginal de esforzarse. Una vez establecidos el valor de la transferencia, $t$, y el costo marginal de la firma, $c = β – e$, solo resta la fijación de la cantidad, $q$, o equivalentemente la fijación del precio $p$. 

La única diferencia entre el problema que enfrenta el gobierno en este caso y el problema de fijación de precio de monopolio, comúnmente estudiado en los cursos introductorios de economía, es que las transferencias son financiadas con impuestos que introducen distorsiones y costos a la sociedad. Por lo tanto, el resultado clásico de fijación de un precio por encima del costo marginal (un _mark up_) inversamente proporcional a la reacción de la demanda ante variaciones en el precio (a la elasticidad de la demanda) se mantiene en este caso, pero el _mark up_ toma en cuenta la distorsión introducida por los impuestos (representada por el parámetro $λ$). En su expresión matemática, el precio se fija de forma tal que: 
$$\frac{p-\left(\beta-e\right)}{p}=\frac{\lambda}{1+\lambda}\times\frac{1}{\eta}$$
donde $η$ es la elasticidad de la demanda.


#### Cuando el supervisor no reporta el valor de $β$

En este caso el gobierno desconoce el tipo de la firma. Det odas maneras, el gobierno puede utilizar un menú de contratos diseñados para cada tipo de firmas. Esto es, un mecanismo de revelación directo tal que, dado un mensaje de la firma, se estipula la transferencia, el costo marginal y la cantidad correspondientes: ${(\underline c, \underline q, \underline t), (\overline c, \overline q, \overline t)}$.
^[El principio de revelación garantiza que no hay pérdida de generalidad por considerar mecanismos de revelación directos. Ver @Laffont1993 para una descripción detallada
de este principio.]
Para que estos contratos sean aceptados por la firma tienen que cumplir con la restricción de participación: $\overline U \geq 0$ y $\underline U \geq 0$.

Además, para que cada tipo de firma encuentre óptimo revelar su tipo en forma verdadera, el contrato diseñado para ese tipo tiene que ser al menos tan bueno como el diseñado para el otro tipo de firma. Esto introduce dos restricciones adicionales conocidas como restricciones de compatibilidad de incentivos. Más precisamente, la firma eficiente $(β = \underline β)$ deberá encontrar óptimo revelar su tipo y obtener el contrato ${(\underline c, \underline q, \underline t)}$ que hacerse pasar por una firma ineficiente y obtener el contrato correspondiente ${(\overline c, \overline q, \overline t)}$:

\[
\underline{U}=\underline{q}P\left(q\right)-\left(\underline{\beta}-\underline{e}\right)\underline{q}-K-\psi\left(\underline{e}\right)\geq\overline{q}P\left(\overline{q}\right)-\left(\overline{\beta}-\overline{e}\right)\overline{q}-K-\psi\left(\overline{e}\right)+\overline{t}
\]

o lo que es lo mismo:
$$\underline U \geq \overline U + \triangle \beta \overline q$$
donde $\triangle \beta = \overline \beta - \underline \beta$

De la misma manera, la firma ineficiente no debería tener incentivos a hacerse pasar por una firma eficiente:

\[
\overline U \geq \underline U = \triangle \beta \underline q
\]

Un resultado estándar de la teoría de incentivos bajo información asimétrica es que las restricciones que se cumplirán con igualdad son la de participación de la firma ineficiente y la de compatibilidad de incentivos de la firma eficiente. Entonces, la firma ineficiente, al igual que en el caso anterior, no recibirá renta excedentaria alguna: $U= 0$. En cambio, la asimetría de información implica que la firma eficiente, debido a que puede hacerse pasar por la ineficiente, deba obtener una renta estrictamente positiva para revelar su verdadero tipo: $U = Δ\beta \overline q$. Esta renta es comúnmente conocida como **renta de la información**, ya que deriva del hecho que la firma eficiente tiene más información que el gobierno. Es preciso notar que, al ser financiada con impuestos, esta renta de la información tiene un costo $\lambda \triangle \beta \overline q$ para la sociedad.


#### ¿Cuándo tiene el supervisor incentivo a reportar la información?

La asimetría de información también puede implicar que el supervisor, aun habiendo obtenido la señal de que la firma es eficiente, pueda preferir no reportar esta información al gobierno. Cuando el supervisor oculta la información, la firma eficiente recibe una renta $U = Δ\beta \overline q$. En cambio, recibiría una renta nula si el supervisor reporta su tipo al gobierno. Por tanto, la firma eficiente estará dispuesta a utilizar hasta la suma de $Δ\beta \overline q$ para que este no revele su tipo al gobierno. Dadas las características de las transacciones que determinan la captura por parte de la firma, el supervisor enfrentará sólo $k Δ\beta \overline q$ (recuerde que $k ε (0,1)$) del monto utilizado por la firma.

Un resultado directo de la observación anterior es que si el gobierno desea prevenir la captura del supervisor por parte de la firma deberá ofrecer al primero una compensación de por lo menos $s = k Δ\beta \overline q$ cada vez que este último reporte que la firma es del tipo eficiente $(r = \underline β)$. Es fácil apreciar que el gobierno siempre encontrará óptimo ofrecer esta compensación al supervisor ya que de otra forma el costo social será superior debido a que será necesario otorgar una renta de información a la firma eficiente igual a $\underline U = Δβ \overline q$. Esta renta es mayor que la compensación requerida por el supervisor para reportar su señal debido a la ineficiencia generada por las transacciones tendientes a lograr la captura: $\underline U = Δβ \overline q \geq kΔβ \overline q = s$ ya que $k ε (0,1)$.

Cuando el supervisor obtiene la información que la firma es ineficiente y reporta $r = \overline β$, la firma no tiene incentivos para que esta información sea ocultada ya que de todas formas recibirá una renta nula. Por tanto, tampoco tendrá incentivos para capturar al supervisor y el gobierno no necesitará compensar a este último por este reporte.


#### ¿Cómo puede el gobierno minimizar el costo de proveer incentivos?

Cuando el gobierno ignora que la firma es eficiente, la renta que esta obtiene es socialmente costosa debido a que las transferencias son financiadas con impuestos que generan distorsiones. Además, la compensación requerida para que el supervisor reporte su señal al gobierno aumenta con el tamaño de la renta, lo que implica costos sociales adicionales. Por estas razones, el gobierno preferirá reducir la renta de la firma eficiente: $\underline U = Δβ \overline q$.

Para ello, el gobierno debe hacer menos atractivo para la firma eficiente el nivel de producción de la firma ineficiente (esto es, bajar $\overline q$) de forma que se reduzcan los incentivos de la primera para hacerse pasar por la segunda. Esto genera distorsiones para la firma ineficiente ya que estará autorizada a producir menos que el nivel eficiente, con lo cual también se reducirá su nivel de esfuerzo.


#### Incentivos de bajo y alto poder

Hasta ahora hemos supuesto que el gobierno es capaz de controlar la cantidad ofrecida por la firma (indistintamente el precio), la transferencia y, debido a que puede observar $c = β – e$, también el costo marginal. De todas maneras, el gobierno podría implementar los contratos óptimos ${(\underline c, \underline q, \underline t), (\overline c, \overline q, \overline t)}$ a través de un mecanismo de incentivos donde el gobierno determine la cantidad y ofrezca a la firma una regla de reembolso de una parte de los costos a través de transferencias. En este caso, el nivel de esfuerzo de la firma (y por tanto su costo marginal) quedaría determinado endógenamente por la misma a los efectos de maximizar su utilidad.

El mecanismo de incentivos propuesto por el gobierno puede ser definido como de **bajo poder** o de **alto poder según su grado de impacto**. Un mecanismo será de alto poder si brinda a la firma un fuerte incentivo a reducir sus costos (por ejemplo a esforzarse más) al permitirle la apropiación de los beneficios derivados del aumento en su eficiencia. Por ejemplo, una **regulación de precio límite**, donde el gobierno fija el precio máximo de venta y una transferencia independiente del costo marginal, permite a la firma apropiarse completamente de cualquier reducción en los costos, con lo cual
la firma realizará un nivel eficiente de esfuerzo. Por el contrario, en un mecanismo de incentivos de bajo poder la firma tendrá menos predisposición a reducir sus costos debido a que ello aparejaría relativamente menores transferencias.


## Regulación en economías en desarrollo: desafíos y soluciones {#desafios}

En esta sección se discutirán algunas características de las economías en desarrollo y se analizarán las implicaciones para el diseño de instituciones regulatorias. El análisis estará basado en el modelo presentado en la sección anterior.
^[El lector interesado en profundizar en el análisis de los temas contenidos en esta sección puede referirse a los trabajos de @Estache2009 y a la contribución seminal de @Laffont2005.]


### Baja capacidad técnica para la supervisión

Los sistemas contables y de auditoría de algunos países en desarrollo pueden adolecer de carencias que hace más difícil para el supervisor obtener la información sobre el verdadero tipo de la firma. Además, muchas veces el propio supervisor se ve impedido de penalizar a la firma por no cumplimiento. En otras ocasiones su personal no es suficiente, o no posee la experiencia y el conocimiento requerido, con lo cual la brecha de información entre el supervisor y la firma se ensancha. En términos del modelo anterior, estas características del entorno institucional se traducirían en una menor probabilidad de obtener una señal sobre el tipo de firma: un menor valor de $ξ$.

Cuando el gobierno está informado con menos frecuencia, la firma eficiente deberá recibir una renta con más frecuencia para revelar su verdadero tipo. Entonces, en términos esperados la firma recibirá mayores rentas. Esto es consistente con la evidencia empírica que indica que en países en desarrollo las firmas reguladas reciben retornos que exceden aquellos que le compensan por los mayores riesgos asumidos.
^[Ver, por ejemplo, @Sirtaine2005 y @Guasch2007.]
Además, las mayores transferencias son financiadas con impuestos que generan distorsiones, con lo cual el bienestar social será menor.

Llevando la incapacidad técnica al extremo, por ejemplo si los sistemas contables o de auditoría son inexistentes, es necesario alejarse del supuesto bajo el cual hemos venido trabajando de que el costo marginal $c = β – e$ es observable por parte del supervisor. En este caso el gobierno pierde la posibilidad de con trolar el costo marginal y el esfuerzo de la firma ineficiente para así reducir la renta informacional de la empresa eficiente, como se analizara en la sección anterior. El gobierno sólo puede controlar la cantidad (equivalentemente el precio) y la transferencia. Entonces, podrá usar un mayor _mark up_ para reducir la cantidad producida por la firma ineficiente, así reducir su atractivo para la firma eficiente y, por tanto, su renta debido a la información asimétrica. El incrementar el _mark up_ de la firma ineficiente es una herramienta menos potente que el control directo del costo marginal y, entonces, también reduce el bienestar social.

Volviendo al caso más común de una capacidad limitada de supervisión, el gobierno podría aumentar el poder de los incentivos para mitigar los problemas introducidos por la menor probabilidad de obtener información de la firma. Debido a que es menos frecuente que el gobierno conozca el verdadero costo de la firma, las compensaciones para que el supervisor revele la información también serán menos frecuentes. Estas compensaciones eran una razón para distorsionar el nivel de producción y el esfuerzo de la firma ineficiente a la baja (recuerde que la compensación al supervisor es una fracción de la renta de información de la firma eficiente, la que a su vez es una función creciente del
nivel de producción de la firma ineficiente). 

Como estas compensaciones son ahora menos preocupantes, existen razones para que el nivel de esfuerzo y de producción de la firma ineficiente aumente. Esto puede lograrse aumentando el poder de los incentivos para la firma eficiente de forma que pueda apropiarse de una mayor parte del beneficio ocasionado por la reducción de costos. 

Otras medidas propuestas por @Laffont2005 consisten en aumentar la competencia en el mercado y en rediseñar las instituciones de supervisión. Una mayor competencia podría ayudar al supervisor a obtener más información y constituye una presión adicional para mantener bajo el precio de la firma. De todas formas, la regulación de mercados parcialmente competitivos no está exenta de problemas. El supervisor debería ahora reducir el poder de mercado y regular los precios de acceso (esto es, por ejemplo, los precios para acceder a una red de transmisión eléctrica). 

Por otra parte, la escasez de recursos técnicos calificados puede ser paliada mediante el rediseño de las instituciones de supervisión. Por ejemplo, a través de la creación de agencias regulatorias unificadas que permitan un mejor aprovechamiento de los recursos humanos calificados, hagan más eficiente el procesamiento de información y más ágil el
intercambio de conocimiento e información.

Además de la escasa capacidad técnica para la supervisión, que como fuera analizado anteriormente aumenta los problemas de información asimétrica, es común que en los países en desarrollo la capacidad técnica también sea reducida en aspectos regulatorios tales como el conocimiento de los instrumentos y las formas de implementar la regulación. Este tipo de incapacidad cognitiva y falta de experiencia de los reguladores también tiene importantes implicaciones. Por ejemplo, es más probable que los contratos diseñados por reguladores con limitada capacidad técnica en países en desarrollo sean incapaces de prever muchas de las contingencias que podrían ocurrir (la magnitud del problema es aún mayor si se tiene en cuenta que en estos países, generalmente, ocurren
contingencias más extremas que en países desarrollados, tales como grandes
devaluaciones o cambios políticos). 

En otros términos, es probable que los contratos sean más incompletos, en el sentido que no serán contingentes en todas las posibilidades en las que sería óptimo que lo fueran. Como evidencia de esto puede citarse el hecho que las disputas por “falta de claridad” en los contratos son más frecuentes en las economías en desarrollo.

Al ser los contratos más incompletos a causa de la baja capacidad regulatoria y, por tanto, no estar previsto un importante número de eventos que podrían ocurrir, la renegociación de los contratos se vuelve más probable.
^[En la sección \@ref(credibilidad) se discutirá en profundidad las implicaciones de la renegociación causada por la falta de compromiso del gobierno y la pérdida de credibilidad en la regulación.]
El proceso de renegociación _per se_ introduce ineficiencias y el resultado final dependerá, en gran medida, del poder de negociación de las partes. Una consecuencia directa de esto es que la firma postergue inversiones, anticipando un proceso incierto de renegociación en el futuro que podría dejarle con menores retornos que los suficientes para hacer rentable la inversión. 

Otra consecuencia, es que es más probable que la firma obtenga mayores rentas en términos esperados. Por un lado, el poder de negociación del gobierno es más probable que sea menor, una vez que los contratos con una firma ya están en marcha, con lo cual la firma obtendría una mejor posición frente a la renegociación del contrato. Por ejemplo, una vez que un proveedor ya está instalado y ha realizado sus inversiones, el
reemplazarlo podría ser costoso para el gobierno debido a la fuerte señal negativa que enviará a otros inversores. Por otro lado, los contratos son incompletos pero podrían estar sesgados a favor de la firma, debido a que esta posee mejor conocimiento técnico para incluir en los contratos contingencias que podrían afectarla en el futuro y, de esta forma, obtener mayor poder de negociación.

La consideración de contratos incompletos posee implicaciones sobre el poder de los incentivos y sobre el diseño de otras instituciones regulatorias. Para visualizar los efectos sobre el poder de los incentivos piense que existen contingencias que pueden afectar el costo marginal, que no han sido consideradas en los contratos. Si el gobierno ha ofrecido incentivos de alto poder a la firma a través, por ejemplo, de una regulación de precio límite o máximo, difícilmente obtenga buena información sobre el costo marginal. 

En cambio, si ha seguido una política de reembolso de una proporción de los costos de la firma debería tener un buen conocimiento del costo marginal, con lo cual estará en una mejor posición de negociación cuando alguna contingencia no prevista suceda. Entonces, la imposibilidad de prever todas las contingencias, por ejemplo debido a la escasa capacidad técnica en países en desarrollo, brinda un argumento para el diseño de esquemas de incentivos de más bajo poder. 

Por su parte, también brinda un argumento para el diseño de las instituciones regulatorias. Desde que los problemas introducidos por los contratos incompletos están determinados por lo que sucede en la etapa de renegociación, sería eficiente que las partes pudieran fijar su poder de negociación ex ante, así como también sus posiciones por defecto. Algunas formas de implementar esto es a través de un proceso de arbitraje, donde el poder de negociación sea decisión de un panel de expertos o mediante el uso de organizaciones internacionales que contribuyan a fijar posiciones por defecto, a través del uso de sistemas de penalidades y garantías.

A modo de resumen, la menor capacidad técnica para la supervisión en países en desarrollo reduce la información disponible para el gobierno. Mecanismos de incentivos de mayor poder, mayor competencia y la unificación de agencias regulatorias son respuestas para mitigar los efectos negativos de este problema.

La menor capacidad técnica también podría hacer los contratos más incompletos, determinando una reducción de la inversión y un aumento de la renta de la firma. En este caso, los efectos negativos pueden ser mitigados mediante la implementación de medidas para hacer el proceso de renegociación relativamente justo y eficiente. A diferencia del caso anterior, donde la menor capacidad técnica aumentaba la asimetría de información, en el caso donde el entorno contractual es más incompleto los esquemas de incentivos de menor poder son los que ayudan a mitigar los efectos negativos.


### Baja rendición de cuentas {#rendicion}

La relativa debilidad institucional de algunos países en desarrollo determina que los mecanismos de rendición de cuentas sean menos potentes. En este caso, la captura del supervisor por parte de la firma puede resultar más fácil debido a que, por ejemplo, el supervisor no debe rendir cuentas al gobierno de manera habitual.

En términos del modelo, una baja rendición de cuentas que facilite la captura por la firma del supervisor puede ser modelada por un aumento del parámetro $k$, ya sea porque es relativamente más fácil para la firma mantener sus acciones ocultas o porque las sanciones en caso de ser descubierta son menores. La predicción inmediata del modelo es que, para evitar la colusión entre firma y supervisor, la compensación a este último por reportar que la firma es eficiente, $s = kΔβ \overline q$, debería ser mayor y, por tanto, el bienestar social sería menor. 

Comorespuesta a este problema, el gobierno podría modificar los contratos ofrecidos de forma que los incentivos contenidos en ellos sean de más bajo poder. Al bajar el poder de los incentivos, el gobierno reduce la tentación a capturar al supervisor ya que las rentas de información hacia la firma eficiente serán menores.

Hay que tener en cuenta que el resultado anterior asume que los costos de la firma pueden ser observados. Pero si la baja rendición de cuentas también afecta los procesos contables y de auditoría de tal forma que los costos de la firma puedan ser exagerados, entonces la respuesta óptima del gobierno sería reducir el uso de contratos basados en los costos, como por ejemplo aquellos que permitan el reembolso de una parte de los mismos, generando un sesgo hacia la utilización de esquemas de incentivos de más alto poder tales como contratos de renta fija o precio máximo para la firma. De esta manera, el efecto neto de una más baja rendición de cuentas sobre el poder de los incentivos es ambiguo y depende de qué proceso es más afectado por la baja rendición de cuentas.

De todas formas, la predicción del modelo no parece ser validada por la evidencia observada en países en desarrollo. En general, los supervisores en estos países no reciben mayores compensaciones que los supervisores en países con mayor rendición de cuentas. En cambio, es más frecuente observar casos de captura en países menos desarrollados que en países con un entorno institucional más fuerte. Esta brecha entre la realidad y la predicción del modelo se debe a que en este último la posibilidad de captura es completamente eliminada, mediante una compensación suficientemente elevada para el supervisor.

Para reconciliar las predicciones del modelo con la evidencia empírica consideremos la siguiente extensión del modelo, donde con alguna probabilidad positiva el supervisor puede ser benevolente (en el sentido que soportará las presiones y nunca aceptará ser capturado) o no benevolente (interesado solamente en su utilidad privada como hasta ahora). 

Aunque el gobierno no conozca el tipo de supervisor, con esta sencilla extensión las predicciones del modelo se acercan más a lo observado en países en desarrollo. En particular, el gobierno ya no estará siempre interesado en prevenir la captura del supervisor ya que si lo intenta (mediante el pago de una compensación suficientemente alta) y este últimos es benevolente, la compensación no alterará en nada el resultado (esto es, no captura) pero será socialmente costosa debido a la ineficiencia en el financiamiento a través de impuestos. 

Entonces, en economías en desarrollo donde $k$ es grande pero hay posibilidades que el supervisor sea benevolente, el gobierno podría encontrar óptimo permitir cierto grado de captura del supervisor por parte de la firma. Si bien esto reduce el bienestar de la sociedad, ya que el supervisor informará al gobierno con menos frecuencia, la reducción de bienestar debido al costo de los impuestos necesarios para prevenir la captura podría ser mayor.

Hasta ahora hemos analizado la situación donde un gobierno benevolente (potencialmente) utiliza un supervisor interesado en su utilidad privada (esto es no benevolente) para estar informado. En la práctica, sin embargo, la baja rendición de cuentas en países en desarrollo alcanza también al gobierno y entonces la preocupación es que el propio gobierno sea capturado directamente por grupos de interés y, en términos del modelo, favorezca a la firma por sobre los consumidores. 

En este caso, el gobierno estará menos preocupado por la distorsión introducida por los impuestos para financiar la renta que tiene que recibir la firma. Por lo tanto, el gobierno ofrecerá incentivos de mayor poder a la firma debido a que estará menos preocupado en reducir su renta.

En resumen, la existencia de mecanismos más débiles para la rendición de cuentas en las economías en desarrollo facilita la captura, disminuye el flujo de información hacia el gobierno y reduce el bienestar social. En términos generales, una solución pasa por reducir la importancia que posee la información para la captura de rentas por las diversas partes involucradas. En particular, una forma de reducir la dependencia en la información privada de la firma es bajando el poder de los incentivos para hacer menos atractiva la colusión. Esto también puede ayudar a mitigar las distorsiones introducidas por un gobierno no benevolente. 

Sin embargo, hay que tener en cuenta que la baja rendición de cuentas también puede determinar la existencia de sistemas contables y de auditoría ineficientes donde los costos puedan ser fácilmente exagerados, en cuyo caso un gobierno benevolente preferiría la introducción de esquemas de incentivos de más alto poder. El resultado neto dependerá, entonces, de cuál problema es el predominante. 

De todas formas, es necesario tener en cuenta que en algunos países en desarrollo, donde la institucionalidad para la rendición de cuentas es muy ineficiente, puede ser óptimo permitir algún grado de captura del supervisor, ya que evitar completamente la misma podría resultar prohibitivamente costoso desde el punto de vista social.


### Compromiso limitado y falta de credibilidad {#credibilidad}

Una forma de compromiso limitado que puede afectar el bienestar social está dada por la posibilidad de renegociación. Si una vez revelada cierta información, como por ejemplo el grado de eficiencia de la firma, las partes encuentran óptimo renegociar, entonces el contrato original no será creíble. Para devolver credibilidad, el gobierno deberá restringirse y sólo podrá usar contratos que sean eficientes ex post (o sea que no sea atractiva su renegociación), con lo cual el bienestar social será menor.

Para fijar ideas piense que la firma ineficiente ha revelado su tipo al seleccionar el contrato diseñado para ella. Conocida esta información, tanto el gobierno como la firma encontrarán óptimo no distorsionar a la baja el nivel de producción, de forma que la firma ineficiente realice el nivel óptimo de esfuerzo. En otras palabras, una vez conocido que la firma es ineficiente, la provisión de incentivos de bajo poder no será óptima y, por tanto, el cumplimiento del contrato original no será creíble. Si este incumplimiento del contrato es anticipado, la firma eficiente tendrá mayores incentivos a hacerse pasar por una firma ineficiente. Entonces, para eliminar esta posibilidad, que se origina en la eventualidad de renegociación, el contrato ofrecido a la firma eficiente debería incluir una renta de información mayor. De esta manera, el bienestar social sería menor a causa de la posibilidad de renegociación.

Dentro de las razones por las que el gobierno puede preferir la renegociación se encuentra la insatisfacción por el nivel de rentas ofrecidas a las empresas. Por ejemplo, el gobierno puede desear que las empresas no obtengan más que determinada renta. En este caso, si la renta requerida por la firma eficiente para no hacerse pasar por la firma ineficiente excede ese umbral, entonces la falta de compromiso del gobierno favorecería la imposición de un sistema de incentivos de menor poder. 

Al reducir el poder de los incentivos, el gobierno restringe la posibilidad de la firma de obtener rentas mayores, haciendo menos atractivo para la firma eficiente el hacerse pasar por una firma ineficiente y, por tanto, mitiga los efectos negativos de la falta de compromiso. De esta forma, esquemas de incentivos de menor poder, como por ejemplo aquellos que fijan una **tasa de retorno** para la firma, serían más convenientes que esquemas de alto poder, tales como un **precio límite**, en economías donde la falta de compromiso es un problema. 

La evidencia empírica aporta elementos a favor de este resultado. Por ejemplo, @Guasch2007 y @Guasch2008 encuentran que en América Latina los regímenes de precio límite generalmente han causado más renegociaciones que esquemas de incentivos de menor poder.

Otras potenciales soluciones al problema de falta de compromiso podrían venir por el lado del financiamiento de la firma. Por ejemplo, una mayor participación del gobierno en la propiedad de la misma o una mayor proporción de la deuda, por sobre los aportes de capital privado, reducirían las rentas hacia la firma y podrían mitigar los problemas de falta de compromiso.

Mientras que la posibilidad de renegociación es importante, la posibilidad de que el gobierno sea incapaz de comprometerse en absoluto y pueda romper el contrato en el futuro, aún sin que la firma quisiera renegociar, es también importante en economías en desarrollo. Si este fuera el caso, la falta de compromiso y credibilidad en los contratos determinaría una elevada incertidumbre para la firma, en cuanto a los retornos futuros de los que se podría apropiar. 

A su vez, esta incertidumbre implicaría que importantes y necesarias inversiones, por ejemplo inversiones en infraestructuras que requieren largos períodos de tiempo para su recupero e involucran activos específicos y no transferibles, no sean llevadas adelante, determinando una situación de subinversión en países en desarrollo. Esto es consistente con la evidencia empírica que documenta que una mayor estabilidad del gobierno, que a su vez está correlacionada con la capacidad de compromiso, está relacionada con mayores niveles de inversión [@Banerjee2006].

La imposibilidad de comprometerse en forma creíble del gobierno también tiene implicaciones dinámicas. Una vez que el gobierno toma conocimiento que la firma es eficiente se verá tentado a utilizar esta información para extraer las rentas de la firma. Al anticipar este comportamiento oportunista por parte del gobierno, la firma eficiente tendrá menos incentivos a revelar su tipo, lo que será costoso para la sociedad debido a las rentas de información que le deben ser transferidas. Si en cambio el gobierno tuviera la capacidad de comprometerse a no utilizar la información para volverse más demandante con la firma, el bienestar general podría ser mejorado.

Mientras que los problemas analizados hasta aquí tienen lugar una vez que la firma ha contratado con el gobierno, la falta de compromiso y la probabilidad de renegociación también podrían afectar las etapas previas, tales como los procesos licitatorios, e incluso pueden comprometer la viabilidad de ciertas reformas. Por ejemplo, la incertidumbre sobre el respeto futuro de los contratos y la posibilidad que el gobierno pueda modificarlos unilateralmente podrían ser un motivo para que las empresas reduzcan el valor de sus ofertas en un proceso licitatorio. Además, es altamente posible que la firma adjudicataria no sea en realidad la firma más eficiente, sino la firma que considera que tendrá una buena posición en caso de renegociación o, en otros términos, que tiene una baja chance de ser expropiada.

La baja credibilidad puede también dar razones a los ciudadanos para oponerse a procesos de reforma. Por ejemplo, algunos procesos de reforma comienzan con un período de aumento de precios que se espera posibilite a la firma realizar inversiones para mejorar la eficiencia, que luego permitirán una reducción permanente de precios en beneficio de los consumidores. En este caso, si el compromiso para cumplir con la baja de los precios futuros es bajo, los consumidores podrían preferir oponerse a la reforma ya que anticipan que terminarán pagando precios más altos.

Una posible solución para mitigar los problemas introducidos por la posibilidad de renegociación viene dada por el diseño de las instituciones regulatorias. En particular, mediante la creación de un regulador (esto es, un agente que diseñe los contratos a ser ofrecidos a la firma) independiente del gobierno se podría incrementar la capacidad de compromiso y la credibilidad de las regulaciones.
^[En general el diseño de reglas y procesos para la etapa de renegociación pueden mejorar la capacidad de compromiso. En particular, la creación de más de un regulador independiente puede, bajo ciertas condiciones, ser una mejor opción a la unificación bajo un solo regulador. En la Sección \@ref(captura) se brinda una discusión de los beneficios de la separación con respecto a la unificación que puede ser complementada por el análisis en @Estache1999.]

La razón para ello es simple: un regulador independiente podrá tener una función objetivo diferente de la del gobierno y, por tanto, una capacidad diferente de compromiso. Si, por ejemplo, el regulador pone un mayor peso que el gobierno en el bienestar de la firma, entonces el primero tendrá menos incentivos a renegociar los contratos que el segundo, ya que estará menos interesado en reducir las rentas obtenidas por la firma. Al igual que en el caso de renegociación, en el caso de subinversión por falta de compromiso del gobierno la creación de un regulador independiente ayudaría a mitigar los problemas. El regulador permitiría la aplicación de incentivos de más alto poder, con los cuales la firma se vería impulsada a invertir. 

La evidencia empírica ha encontrado que la existencia de un regulador independiente no solamente reduce la ocurrencia de renegociación, sino que también está relacionada a un mayor tamaño de la red, en el caso de inversiones en el sector de las telecomunicaciones. Otros aspectos, tales como la reputación, podrían determinar una mayor capacidad de compromiso del regulador con respecto al gobierno.

A modo de resumen, la capacidad de compromiso limitado del gobierno y la falta de credibilidad en la regulación pueden manifestarse de varias maneras y, por tanto, las soluciones pueden variar dependiendo del problema predominante. En términos generales, las soluciones pueden transitar desde el diseño de esquemas de incentivos de menor poder (para mitigar los problemas originados por la renegociación de los contratos impulsada desde el gobierno) a la creación de un regulador independiente y sesgado a favorecer a la firma (para mitigar los problemas originados tanto por la posibilidad de renegociación como por la falta de compromiso y comportamiento oportunista del gobierno).


### Baja eficiencia fiscal

La baja eficiencia de los sistemas impositivos en los países en desarrollo hace aún más acuciantes algunos de los problemas analizados previamente. Por ejemplo, el potencial de generar capacidad técnica para la supervisión y de retener capital humano calificado, así como la posibilidad de generar instituciones capaces de mejorar el compromiso y la credibilidad de las regulaciones dependen crucialmente de la eficiencia fiscal. Además, una baja eficiencia fiscal también potencia los problemas producidos por una ineficiente rendición de cuentas, al hacer la provisión de incentivos al supervisor más costoso para la sociedad.

Una implicación directa de una más baja eficiencia fiscal (o lo que es lo mismo de un mayor costo de oportunidad de los fondos públicos), que está representada en el modelo por un mayor parámetro $λ$, es que el precio que enfrentarán los consumidores será mayor.
^[Recuerde que en términos del modelo presentado en la Sección \@ref(modelo) la fijación de precios se realiza de acuerdo a la siguiente expresión: $\frac{p-\left(\beta-e\right)}{p}=\frac{\lambda}{1+\lambda}\times\frac{1}{\eta}$, con lo cual un mayor costo de oportunidad de los fondos públicos determina una brecha mayor entre el precio y el costo marginal de producción.]
Una razón para ello está en que, dada la ineficiencia general en la recaudación de impuestos, cobrar impuestos a la firma es relativamente más eficiente para el gobierno. De esta manera, es posible que firmas en sectores que son subsidiados en países más avanzados deban pagar importantes impuestos en países menos desarrollados. Además,
la baja eficiencia fiscal podría brindar una razón para aumentar los beneficios de la firma, ya que estos sirven de base para la recaudación impositiva. De esta manera, es de esperar mayores transferencias y más monopolios públicos en los países en desarrollo.

Otra implicación de una más baja eficiencia fiscal es que el gobierno preferirá utilizar esquemas de incentivos de menor poder. Esto es, en los hechos, una respuesta para mitigar los problemas introducidos por la ineficiencia en la recaudación de impuestos y el uso de los fondos públicos. Debido a que el costo de oportunidad de estos fondos es elevado en economías en desarrollo, el costo de transferir una renta de información a la firma eficiente, así como el costo de compensar al supervisor por sus reportes, también serán mayores. Dado que estos costos están asociados al nivel de producción de la firma ineficiente, el gobierno podrá reducir los mismos, reduciendo la producción de esta firma. Para ello, podrá bajar el poder de los incentivos de forma que el nivel de es-
fuerzo será menor, el costo marginal mayor y, por tanto, la producción de la
firma ineficiente menor.

Otro aspecto crucial para las economías en desarrollo, sobre el que tiene implicancia directa la ineficiencia impositiva, está dado por el escaso alcance, cobertura y desarrollo de las redes de servicios públicos. Los fondos públicos, además de ser utilizados para realizar transferencias a la firma, compensar las agencias de supervisión y generar instituciones regulatorias, son utilizados para desarrollar infraestructuras a través de la inversión pública. En los países en desarrollo la expansión de las redes de servicios públicos tales como electricidad, telefonía y agua potable es sumamente necesaria y, posiblemente, más costosa que en otras economías debido a características geográficas y urbanísticas.

Pero es justamente en estas economías donde la capacidad de extender los servicios mediante el uso de fondos públicos está más limitada por la ineficiencia fiscal. A su vez, esto determina redes de servicios públicos de menor escala que el mínimo que sería necesario para atraer inversores extranjeros (los que también podrían no encontrar atractivo el mercado debido a los problemas de compromiso analizados en la sección previa). Como resultado, algunos sectores de la sociedad podrían ver restringido su acceso a los servicios públicos.

Además, el acceso a los servicios públicos también se podría ver restringido debido a efectos indeseados de algunas políticas públicas impulsadas con el objetivo de hacer abordable los servicios para los consumidores. Por ejemplo, una política que prohíbe la discriminación de precios por parte de la firma puede tener el loable objetivo de posibilitar que consumidores en zonas alejadas (como zonas rurales) compren el servicio al mismo precio que consumidores en zonas más densamente pobladas (por ejemplo, en las ciudades). 

Pero, por lo general, el costo de suministrar el servicio en zonas alejadas es mayor, con lo cual la firma podrá preferir no suministrar el servicio en dichas zonas. Existe entonces una tensión entre hacer abordable el servicio y la posibilidad que los consumidores puedan acceder al mismo. ¿Cómo es posible mitigar estos problemas de acceso? Una posible solución es permitir a la firma la utilización de subsidios cruzados, donde la actividad en las zonas menos costosa subsidie la actividad en las zonas más costosas. 

Si la ineficiencia fiscal es tal que el costo de los fondos públicos es extremadamente elevado, el gobierno podría igualmente garantizar el acceso a toda la población mediante la imposición de un requerimiento de cobertura universal, donde la firma deba satisfacer la demanda de toda la población, al tiempo que podría reducir el costo de las transferencias necesarias, permitiendo que la propia firma obtenga rentas extraordinarias en las zonas menos costosas, de forma de subsidiar internamente la actividad en las zonas más costosas.

A modo de resumen, la mayor ineficiencia fiscal en los países en desarrollo potencia algunos de los problemas analizados previamente y, además, puede determinar la existencia de mayores precios para los consumidores y mayores impuestos para la firma que en economías con mayor eficiencia en la recaudación y uso de fondos públicos. Una respuesta para mitigar estos problemas consiste en reducir el poder de los incentivos, para así reducir el costo fiscal de proveer los mismos. 

Otra importante implicación está dada por la existencia de redes de servicios públicos más pequeñas y fallas en la cobertura. Una respuesta a este problema es la utilización de subsidios cruzados, para cuyo diseño es necesario considerar la tensión entre la posibilidad de pagar por el servicio de los consumidores y el deseo de la firma de brindar acceso a los mismos.


### Corrupción

En la sección \@ref(rendicion) se analizaron los efectos producidos por el hecho de que en países en desarrollo la rendición de cuentas es más débil. En particular, se concluyó que el atractivo para que la firma capture al supervisor se reduciría si los esquemas de incentivos fueran de menor poder. El modelo presentado también puede ser utilizado para el análisis de otros tipos de corrupción que comúnmente son cometidos por otros agentes, posiblemente más relevantes que el supervisor, en economías en desarrollo,
^[A modo de ejemplo, sobre finales del año 2014 tomó conocimiento público un esquema de sobornos por un monto cercano a los cuatro mil millones de dólares en la petrolera brasilera Petrobras.]
así como también para entender el resultado de ciertos procesos de reforma en estos países.

Generalmente, los países en desarrollo han recibido de asesores internacionales la recomendación de descentralizar la supervisión. Esto es, por ejemplo, separar de una agencia central o nacional ciertas actividades que serán llevadas adelante por agencias locales. Este tipo de estructura puede ser fácilmente representada en términos del modelo de la sección \@ref(modelo). En esa sección se analizó la jerarquía formada por el gobierno, el supervisor y la firma. El análisis de la descentralización focaliza en una jerarquía formada por una agencia central, una agencia local y la firma. Entonces, en esta jerarquía la firma tendrá incentivos para capturar a la agencia local y, como resultado, será más probable que la agencia local oculte información a la agencia central.

Además de los motivos contemplados en el modelo básico (donde la captura es modelada como una transferencia), en la práctica la agencia local puede tener otras razones para coludir con la firma. Por ejemplo, si esta agencia es un gobierno local sus intereses para mantener una firma (aún ineficiente) operando en su territorio pueden estar sustentados por el mantenimiento de puestos de trabajo o la recaudación de impuestos locales. 

Este tipo de actividades, a su vez, pueden facilitar el logro de los objetivos de los políticos locales tales como ser promovidos o reelectos. En China, por ejemplo, los gobiernos locales son reconocidos por su colusión con pequeñas e ineficientes firmas de carbón para que estas no sean cerradas por el gobierno central. 

Más recientemente, el vínculo de los gobiernos locales ha sido muy fuerte con las empresas constructoras y una parte importante de sus ingresos proviene de actividades relacionadas con el sector inmobiliario (aproximadamente un 40% según algunas estimaciones). En estos casos, el modelo indica que la agencia central deberá compensar a la agencia local para que esta reporte, en forma verdadera, la información que posee y, de esta forma, la corrupción y sus efectos negativos puedan ser mitigados.

La propia composición de la agencia supervisora puede afectar el grado de corrupción ya que diferentes objetivos de los supervisores pueden determinar diferentes incentivos. Por ejemplo, un supervisor puede estar interesado en su carrera en la industria luego de abandonar la agencia supervisora, mientras que otro puede ser un profesional retirado de la industria que, para mantener influencia en el proceso regulatorio, se une a las tareas del supervisor y un tercero puede ser un político para el cual la agencia supervisora es un primer escalón en su carrera política. Claramente los dos primeros grupos de supervisores darán un valor de continuación más alto al hecho de coludir con la firma. 

Esto sugiere que darle más peso a los políticos dentro de la agencia supervisora sería beneficioso para mitigar los efectos de la corrupción. De todas maneras, esta recomendación no es consistente con la sugerencia tradicional de utilizar supervisores técnicos por sobre políticos. El modelo es también de utilidad para analizar la corrupción por parte del propio gobierno así como para comprender por qué algunas reformas, que podrían mejorar el bienestar general en países en desarrollo, no obtienen el apoyo de la ciudadanía en general. 

Por ejemplo, Bergara y Pereyra (2005) documentan que los distintos intentos de privatización y apertura en Uruguay fueron rechazados mediante la utilización de mecanismos de democracia directa, en tanto @Martimort2009 encuentran que varias encuestas, en países de América Latina, indican que el descontento de la ciudadanía con los procesos de privatización está correlacionado con la percepción de una creciente corrupción.

Lo anterior puede ser racionalizado en términos del modelo al considerar una jerarquía compuesta por la ciudadanía, el gobierno y la firma en un entorno de baja rendición de cuentas del gobierno a su electorado (la ciudadanía). Cuando la firma es regulada por el gobierno, la corrupción toma la forma de una mayor transferencia de fondos públicos hacia la firma. Cuando la actividad es privatizada, los efectos de la corrupción pasarán a los consumidores (la ciudadanía) directamente a través de mayores precios. Además, si el costo de los fondos públicos es relativamente elevado, debido a la baja eficiencia de los sistemas impositivos en países en desarrollo, que el costo de aumentar los precios, entonces la corrupción será menos costosa y más frecuente, en el caso que la actividad sea privatizada. 

Además, generalmente la ineficiencia fiscal está asociada a sistemas de impuestos y subsidios relativamente opacos para los ciudadanos, en tanto la obtención de rentas extraordinarias a través de un aumento de los precios del producto es más susceptible de ser identificada por los ciudadanos.

En términos generales, el modelo de la sección \@ref(modelo) es lo suficientemente versátil tanto para sugerir caminos que mitiguen los efectos negativos de la baja rendición de cuentas y la corrupción en países en desarrollo, como para analizar los riesgos de descentralización y privatización. Una enseñanza de estos análisis es que identificar el tipo de corrupción predominante en cada situación es vital para proponer la solución que mejor mitigue el problema.


### Baja capacidad de hacer cumplir las normas

En la sección \@ref(credibilidad) se analizaron las implicaciones de una baja capacidad de compromiso por parte del gobierno. En esta sección se discutirá, brevemente, qué sucede cuando hay una baja capacidad de hacer cumplir las normas y, por tanto, la firma puede salirse de lo estipulado en el contrato, incluso cuando esta acción sea desventajosa para el gobierno. 

Dada la fortaleza de las instituciones en los países desarrollados es poco probable que una firma pueda desviarse si esto no está en el interés del gobierno. En cambio, @Estache2009 presentan ejemplos de países menos desarrollados tales como Ghana, donde el monopolista de la telefonía fija entró en el segmento de la telefonía móvil a pesar de tenerlo expresamente prohibido, o de Tanzania donde el supervisor intentó restringir la operación de la compañía proveedora de telefonía móvil pero esta no estuvo de acuerdo y se expandió nacionalmente. 

Una posible explicación para esta relación entre el nivel de desarrollo y la capacidad para hacer cumplir las normas es que a medida que el nivel de desarrollo aumenta la eficiencia del sistema impositivo aumenta y, entonces, los gastos en mejorar la eficiencia para hacer cumplir las normas también aumentan, ya que los fondos públicos son menos costosos.

En términos del modelo presentado no es difícil mostrar que una firma ineficiente puede tener incentivos a renegociar el contrato cada vez que la utilidad que obtiene, luego del proceso de renegociación, es mayor que la utilidad especificada en el contrato.
^[@Guasch2006 documentan que el 41% de los contratos de concesión de infraestructura otorgados en América Latina entre 1990 y 2000 fueron renegociados a instancias de las firmas concesionarias.]
En particular, Laffont (2005) muestra que esto sucede si la firma ineficiente sólo descubre su nivel de eficiencia luego de haber aceptado el contrato ya que, en este caso, el contrato óptimo ofrecido por el gobierno implicará un pago negativo para la misma. Desde que los procesos de renegociación son ineficientes y generan costos, por ejemplo porque insumen tiempo, una baja capacidad de hacer cumplir los contratos redundará en una caída del bienestar social. Entonces, puede resultar valioso generar algún tipo de institución para mejorar el cumplimiento de las normas. En particular, este tipo de institución será más necesaria cuando la eficiencia de los procesos de renegociación es más baja. 

En la sección \@ref(credibilidad) se discutió como un regulador independiente y sesgado hacia la firma podía mitigar los problemas de baja inversión ocasionados por la falta de compromiso del gobierno. De manera similar, en el caso que los problemas sean a consecuencia de una baja capacidad de hacer cumplir los contratos, un regulador independiente, pero sesgado hacia los consumidores, podría ser beneficioso.


### Alta posibilidad de captura del regulador {#captura}

A lo largo de las secciones previas se ha abordado repetidamente el problema que el supervisor puede ser capturado por la firma para no reportar al gobierno la información sobre su eficiencia. En esta sección se profundizará el análisis de las causas y consecuencias de una más alta posibilidad de captura en economías en desarrollo y se discutirán posibles soluciones. Se focalizará en el diseño de las instituciones para la supervisión y, en particular, en la conveniencia y la posibilidad de utilizar más de un supervisor en estas economías, a los efectos de mitigar la posibilidad y el costo de la captura regulatoria.

En el contexto del modelo de la sección \@ref(modelo), la separación de la supervisión en dos agencias independientes puede ser visualizada como un mecanismo para mitigar los efectos de la captura. Esto es posible debido a que el gobierno podrá utilizar la información proporcionada por uno de los supervisores para evaluar la información brindada por el otro (un mecanismo conocido en la literatura como _yardstick competition_). Al utilizar la correlación entre las señales que cada supervisor recibe, el gobierno es capaz de extraer de ellos sus rentas en forma gratuita.
^[De todas formas existirá un costo asociado a la duplicación de los supervisores.]

En lo que sigue se discutirá la intuición detrás de los resultados teóricos de los principales trabajos que han analizado la conveniencia de separar la supervisión para mitigar los efectos de la captura por parte de la industria.
^[Esta sección está basada en los trabajos de @Laffont1999 y @Laffont2005. @Boyer2012 presentan una aplicación para el caso de la industria bancaria y la separación entre supervisión micro y macro-prudencial.]
A modo de adelanto, la conclusión es que la separación de poderes es más valiosa en países en desarrollo que en países más desarrollados.
^[Otras razones que pueden determinar que la separación de poderes sea deseable tienen que ver con que la separación puede ser beneficiosa cuando la capacidad de compromiso intertemporal es limitada, para mitigar la ocurrencia de potenciales errores e incluso para proveer poderosos incentivos reputacionales.]
Pero, desafortunadamente, las mismas razones que determinan este resultado también implican que sea más difícil implementar la separación en estos países y garantizar un adecuado nivel de eficiencia.

Considere una simple extensión del modelo antes presentado donde en lugar de haber una señal sobre el nivel de eficiencia de la firma hay dos señales, cada una de las cuales proviene de la aplicación de una tecnología de supervisión diferente. El caso en el cual un único supervisor maneja ambas tecnologías es análogo al discutido en la sección \@ref(rendicion) y, entonces, la respuesta óptima a la amenaza de captura del supervisor por parte del gobierno es bajar el poder de los incentivos. Entonces, los esquemas de incentivos deberían ser de más bajo poder en los países en desarrollo.

Adicionalmente, el gobierno también puede modificar el diseño institucional y disponer que cada tecnología de supervisión sea responsabilidad de un super visor independiente del otro. En este caso, es posible probar que la separación de poderes permite un ahorro en el pago de compensaciones a los supervisores para que estos revelen sus señales y, por tanto, también permite la implementación de mecanismos de incentivos de mayor poder. Una razón detrás de este resultado es que el gobierno podrá utilizar la señal proporcionada por un supervisor para compensar (o penalizar) al otro supervisor. 

Para fijar ideas, asuma que la correlación entre las señales de los supervisores es perfecta. En este caso, si el gobierno recibe información de un supervisor pero no del otro, el gobierno sabrá con certeza que este último está ocultando su señal y podrá penalizarle. Como los supervisores conocen que este será el caso si ocultan información, en equilibrio ambos reportarán sus señales al gobierno aún sin la necesidad de recibir una compensación a cambio. 

En este caso particular, el gobierno estará plenamente informado sin costo alguno para proveer incentivos a los supervisores y la regulación óptima, con un gobierno benevolente, podrá ser implementada. Otra razón por la cual se puede ahorrar la compensación necesaria para que cada supervisor revele su información está dada por la relativamente más desventajosa posición de cada uno de ellos vis-à-vis la firma. Bajo separación cada supervisor estará sólo parcialmente informado y, por tanto, la firma tendrá menos incentivos para capturar a un supervisor que es relativamente más débil, con lo cual la compensación necesaria para lograr que estos revelen su señales también será menor.
^[Laffont y Martimort (1999) muestran que los beneficios de la separación también existen si un supervisor observa el reporte del otro supervisor antes de decidir si ceder a las presiones de la firma, tal como ocurre frecuentemente en la práctica.]

No es difícil mostrar que la ganancia de bienestar asociada a la separación de poderes aumenta con el parámetro $k$ (con una más baja rendición de cuentas) y con el parámetro $λ$ (con una menor eficiencia en el uso de los fondos públicos).

En cambio, la ganancia se reduce con una más baja capacidad técnica para la supervisión. Entonces, el valor de la separación de supervisores, para combatir el problema de captura por parte de la industria, es mayor en países menos desarrollados cuando estos poseen tecnologías de supervisión similares a las de los países avanzados. Sin embargo, el resultado se vuelve ambiguo cuando se tiene en cuenta que los países en desarrollo también poseen tecnologías de supervisión menos eficientes.

Además, las propias características de los países en desarrollo hacen más costosa la implementación de las reformas estructurales necesarias para garantizar una separación efectiva. En particular, es sumamente probable que cuanto más baja sea la capacidad de hacer que los supervisores rindan cuentas, más alta será la posibilidad que los propios supervisores coludan entre sí y no reporten la información al gobierno. Esta más alta probabilidad de que la separación de poderes sea puenteada por la colusión entre supervisores se suma a los mayores costos de compensarles (debido a la mayor ineficiencia impositiva) y a que, generalmente, los costos de transacción son mayores en las economías en desarrollo.

A modo de resumen, la mejora en las instituciones mediante la separación  de supervisores es más valiosa en las economías en desarrollo que en las más desarrolladas, para mitigar los efectos de la captura por parte de la industria y el comportamiento oportunista de los supervisores. Esto es así debido a los mayores costos de los fondos públicos, a la más baja rendición de cuentas y a la existencia de tecnologías de supervisión menos eficientes. 

Desafortunadamente, estas mismas razones determinan que las reformas estructurales necesarias sean más difíciles y costosas de implementar y que, de implementarse, muestren resultados menos eficientes. De esta manera, la recomendación de política con respecto a la separación de poderes será ambigua, a menos que se atiendan en forma simultánea varios de los problemas de las economías en desarrollo previamente analizados.


## Comentarios  {#coment-fin}

Este capítulo ha analizado los distintos problemas a los que se enfrenta el diseño de instituciones regulatorias en países en desarrollo. En términos generales, la existencia de asimetría de información entre las partes (firmas, reguladores, gobierno, ciudadanía, etc.) permite a algunos de estos agentes obtener rentas que no existirían si todas ellas tuvieran la misma información. Estas rentas de la información pueden ser mitigadas, aunque no eliminadas, a través del correcto diseño de las regulaciones y de las instituciones para la supervisión. 

El diseño de las agencias reguladoras y los instrumentos disponibles dependerán de cuáles sean los principales cuellos de botella y restricciones que enfrente el gobierno. Esto determina una fuente importante de diferencias entre las regulaciones necesarias para economía desarrolladas y economías en desarrollo. De esta forma, es crucial mantener un adecuado balance entre las reglas de juego que permitan la provisión de bienes y servicios de calidad a un precio razonable y las intervenciones diseñadas para mitigar los problemas de asimetría de información entre las partes.

La experiencia en países en desarrollo ha mostrado que los efectos de un marco institucional más débil, sobre los resultados de las regulaciones, han sido importantes. El análisis contenido en las secciones previas sirve de guía para ver cómo la consideración explícita de las características distintivas de los países en desarrollo necesariamente implica que la regulación óptima en estos países tenga que apartarse, en aspectos clave, de la regulación óptima para países desarrollados.

Una síntesis de potenciales problemas y posibles soluciones es la siguiente:
* Baja capacidad técnica:
  * Implementar esquemas de incentivos de más alto poder (si es posible diseñar contratos completos).
  * Unificar agencias supervisoras.
  * Fomentar la competencia del mercado.
  * En un entorno de contratos incompletos, limitar el poder de los esquemas de incentivos e implementar mecanismos de arbitraje para fijar _ex ante_ el poder de negociación de las partes.
  
* Baja rendición de cuentas:
  * Implementar esquemas de incentivos de más bajo poder.
  * Balancear la baja de poder de los esquemas de incentivos si la escasa rendición de cuentas también afecta la observación de costos.

* Compromiso limitado y falta de credibilidad:
  * Implementar esquemas de incentivos de más bajo poder.
  * Dotar de mayor independencia al regulador.
  * Propiciar un mayor peso de la deuda en el financiamiento de la firma.

* Baja eficiencia fiscal:
  * Implementar esquemas de incentivos de más bajo poder.
  * Si se generan deficiencias en la cobertura, permitir el subsidio cruzado.

* Corrupción:
  * Reformas que potencialmente incrementan el bienestar social podrían carecer de apoyo de los ciudadanos.

* Baja capacidad de hacer cumplir las normas:
  * Dotar de mayor independencia al regulador.

* Alta posibilidad de captura del regulador:
  * Implementar esquemas de incentivos de más bajo poder.
  * Separar las tareas de supervisión en varios supervisores independientes.

Algunas de las recomendaciones sugeridas por la teoría económica de la regulación, que fueran analizadas en las secciones previas, para diferentes problemas en países en desarrollo tienen su correlato con lo efectivamente observado en estos países a través de sus diferentes etapas de desarrollo. @Laffont2005 argumenta, por ejemplo, que las diferentes etapas de la regulación del mercado eléctrico en Europa del Este, los procesos de nacionalización en el resto de Europa o la regulación de firmas privadas en los Estados Unidos pueden ser identificadas con los resultados previos.

En una etapa de menor desarrollo (etapa 1) la falta de capacidad técnica es tal que los sistemas contables y de auditoría son inexistentes. En este caso el gobierno no posee muchas más opciones que proponer esquemas de incentivos de alto poder, tales como contratos de renta fija o de precio máximo, que dejan a la firma la posibilidad de apropiarse de cualquier reducción de los costos. Estos contratos poseen un alto costo social, en términos de rentas de información hacia la firma, el que puede ser mitigado mediante la calibración adecuada de los parámetros de los contratos, tal como se analizara previamente.

A medida que los sistemas contables y de auditoría se desarrollan y se ponen en funcionamiento (etapa 2), el gobierno estará mejor informado y tiene la oportunidad de utilizar otros esquemas de incentivos de menor poder tales como el reembolso parcial de los costos de la firma. De todas formas, el grado de desarrollo todavía no es suficientemente alto y otros de los problemas analizados previamente, tales como baja rendición de cuentas e ineficiencia de los sistemas impositivos, están aún presente. Entonces, a medida que los países acceden a etapas superiores de desarrollo, la regulación se debería mover, quizás en forma discreta, hacia esquemas de incentivos de menor poder.

Finalmente, a medida que se alcanzan etapas superiores de desarrollo (etapa 3), la eficiencia en el uso de los fondos públicos mejora paulatinamente. Esto posibilita un retorno gradual a la utilización de esquemas de incentivos de más alto poder.

Otra implicación del análisis previo es que cierta independencia de los reguladores y separación de los supervisores puede ser conveniente para mitigar los problemas ocasionados por la baja capacidad de compromiso y de rendición de cuentas en economías en desarrollo.